### ISSUE TITLE
[BUG] Texture bug when using OptiFine

### ISSUE THREAD

**Issue by NorthHusky** [GregTechCEu/GregTech#1001]
**Versions**
Forge: 14.23.5.2860
OptiFine: preview_OptiFine_1.12.2_HD_U_G6_pre1
GTCEu: gregtech-1.12.2-2.3.1-beta

Texture bug appears when using Optifine with Anisotropic Filtering set to any mode, this issue is on both your version of the GregTech CEu mod and the original GregTech CE.
![image](https://user-images.githubusercontent.com/105886827/171224554-05bb7093-4b8b-48f3-91d6-8fd4f8312713.png)
![image](https://user-images.githubusercontent.com/105886827/171228108-ec5d448f-4448-484c-83c2-cf679c1b51ee.png)

As you can see, when the Anisotropic filtering setting is turned off, the bug does not appear.
![image](https://user-images.githubusercontent.com/105886827/171225753-55bc0c52-bedf-4428-b9f5-0ce44d428798.png)

I apologize if my English is wrong, I'm from Ukraine))

**Comment by htmlcsjs** [comment]
do you have any other mods installed, (like a certan funny asm mod)

**Comment by NorthHusky** [comment]
Yes, I have loliasm-5.3 (reworking of the VanillaFix mod), but if you remove this mod, nothing will change and the texture bug remains.

**Comment by htmlcsjs** [comment]
you have gregicality legacy and gtce installed, instead of ceu, going to close this issue

**Comment by NorthHusky** [comment]
@htmlcsjs 
This happens in your GregTech CEu mod, here is a test on a clean build of Minecraft in the screenshot
![image](https://user-images.githubusercontent.com/105886827/171257080-ce4d1b81-a6d8-47bb-8b56-5fa82bf2fbb6.png)
![image](https://user-images.githubusercontent.com/105886827/171257525-668d6fcb-4afc-4a5a-8042-f363d29e88f8.png)
![image](https://user-images.githubusercontent.com/105886827/171257742-49bcecb4-c9fe-4640-9e9d-ecf1d86b9102.png)

**Comment by htmlcsjs** [comment]
can confirm, however we probably cant fix it because of its probally an incompatibility with codechickenlib and optifine.

**Comment by NorthHusky** [comment]
@htmlcsjs Do you think it makes sense to write to the author of the CodeChickenLib library? Perhaps he can fix this incompatibility.

https://github.com/TheCBProject/CodeChickenLib/issues

**Comment by Irgendwer01** [comment]
> @htmlcsjs Do you think it makes sense to write to the author of the CodeChickenLib library? Perhaps he can fix this incompatibility.
> 
> https://github.com/TheCBProject/CodeChickenLib/issues

@NorthHusky it will have no use as the 1.12 version of CCL is unsupported by the author and he will no provide no fix for this.

**Comment by NorthHusky** [comment]
@Irgendwer01 Do you know how you can replace the anisotropic filtering setting so that there are no bugs on the water?

**Comment by Syrcan** [comment]
Given this is a non game breaking optifine issue, I am closing this.
