### ISSUE TITLE
[BUG] Tantalum Carbide Ingot to Plate Recipe in Bending Machine Eating Ingots

### ISSUE THREAD

**Issue by shawnbyday** [GregTechCEu/GregTech#1002]
**Describe the bug**
Whenever I try use the Bending Machine to make Tantalum Carbide Ingot by hand I get 1:1 ratio. When I use AE2 it seems I'm getting a 2:1 ratio. So each plate costs 2 ingots to make. I've checked my recipe and it is correct.

**Versions**
Forge: 14.23.5.2860
GTCEu: 2.2.3-beta
_Modpack:_ Nomifactory with GTCEu
_Addons:_ None

**Setup**
_Does this issue happen on Singleplayer, a Server, or both_: I'm playing on a server.
_Does this issue happen on a newly generated world_: Unsure.

**Steps To Reproduce**
1) Make recipe to craft 1 Tantalum Carbide Plate from 1 Tantalum Carbide Ingot in the Bending Machine.
2) Craft by hand = 1:1, craft by AE = 2:1 ratio.

**Expected behavior**
Expected recipe to work properly.

**Screenshots**
Screenshot of recipe pattern:
![image](https://user-images.githubusercontent.com/33701188/171303067-4ad58601-ab12-490a-a33b-0a6a52f364a8.png)

**Comment by Syrcan** [comment]
If this is really a bug, we're gonna need more info on this.
I do not understand why it would happen to Tantalum Carbide specifically, or why it would be because of AE2 request.
One explanation I could find is that you have another duplicate pattern in a random interface, which makes the requests cycle between each interface.

**Comment by lordclips** [comment]
Have you checked that there isn't also a second plate somewhere floating around in your AE system? Mostly related to the above comment, since it might actually explain why it for some reason just eats a second ingot

**Comment by shawnbyday** [comment]
Ugh you guys are right. I troubleshooted this for like 2 hours before I submitted this ticket initially. I just spent another 2 hours and finally figured out I had another recipe for that in my alloy smelter like a nub. You can close this. Sorry :(

**Comment by TechLord22** [comment]
We're glad you figured it out! And... even more glad it wasn't a serious voiding issue after all. So thank you :)
