### ISSUE TITLE
[Suggestion] GT Powered Wire Cutters

### ISSUE THREAD

**Issue by shawnbyday** [GregTechCEu/GregTech#1007]
**Is your feature request related to a problem? Please describe.**
NOT related to a problem

**Describe the solution you'd like**
Implement wire cutters similar to the electric wrench and screwdriver.

**Comment by AlfarelSynthesis** [comment]
These already exist.

**Comment by shawnbyday** [comment]
> These already exist.

What are they called?

**Comment by AlfarelSynthesis** [comment]
> > These already exist.
> 
> What are they called?

May have missed the word "electric" 😳

**Comment by PSR2144-3933** [comment]
already added in latest version

**Comment by Zorbatron** [comment]
Added in #2404
