### ISSUE TITLE
[BUG] Terminal Console App rendering issue

### ISSUE THREAD

**Issue by lordclips** [GregTechCEu/GregTech#1012]
**Describe the bug**
Solar Panel is an attention craving motherfucker in the Console app

![2022-06-05_01 22 49](https://user-images.githubusercontent.com/72330305/172036497-15f23a93-4bcc-4922-bd03-d16d2c4022c9.png)
![2022-06-05_01 22 53](https://user-images.githubusercontent.com/72330305/172036503-5e057246-2293-4d82-bc5c-acbe12a5f377.png)

**Versions**
Forge: Whatever 2.3.1 uses
GTCEu: 2.3.1

**Steps To Reproduce**
1. Make machine
2. Put solar panel on machine
3. ???
4. Profit
5. But also use Console App
6. Open Machine gui
7. See solar panel indicator peeking through into the GUI of the machine.

**Expected behavior**
The solar panel is put in its proper place.

**Additional context**
Just a fun fact, discovered this fixing something else.

**Comment by brachy84** [comment]
Will probably be fixed with the ModularUI rework ~~in 4 years~~

**Comment by lordclips** [comment]
Considering I have like, most applicable things open in my IDE atm ill try to see if I cant find it anyway, but if not then yeah, its a fairly niche issue to have

Console app is just kind of a messy one

**Comment by brachy84** [comment]
Everything ui related is "kind of" messy

**Comment by lordclips** [comment]
Fair 'nuf. Figure I might as well just do it since I'm here and in waiting for the UI rework, just as a nicety

**Comment by lordclips** [comment]
Turns out it is generically a cover issue

**Comment by lordclips** [comment]
I checked and it looks like SlotWidget being a Native Widget and using vanilla Slots is probably what it is but I am unlikely to reasonably fix that, so this'll just sit open while the ModularUI rework works its way through

**Comment by Syrcan** [comment]
Terminal rendering issues are known as in shown in #446. So closing this specific issue.

**Comment by ALongStringOfNumbers** [comment]
This is a different issue than the one in 446, so reopening.

**Comment by Syrcan** [comment]
Alright, time to actually close it since I transferred it to #446, so it can rest in peace with other terminal issues.
