### ISSUE TITLE
[BUG] GC Moon Blocks are being seen as ores

### ISSUE THREAD

**Issue by ReclipseTheOne** [GregTechCEu/GregTech#1013]
GT sees Moon Turf/Dirt/Rock (Galacticraft) as copper ore even though the blocks don't have any OreDict tags.

**Comment by ReclipseTheOne** [comment]
More exactly as copper ore :(

**Comment by hjae78** [comment]
You will have to be more specific

**Comment by brachy84** [comment]
This is a known issue. Blame Minecraft and forge for not providing proper blockstate -> item conversion methods. Blame GC for putting ores and non ores into the same block. Blame GT for not even trying to handle it properly

**Comment by brachy84** [comment]
How it works is, we get the block at certain position, convert to an item try get a ore prefix from it. If the name of the prefix starts with `ore` it is considered an ore. The issue happens in the blockstate to item conversion.
