### ISSUE TITLE
[Suggestion] Make central monitor elements moveable

### ISSUE THREAD

**Issue by Discusser** [GregTechCEu/GregTech#1014]
**Is your feature request related to a problem? Please describe.**
I have a Central Monitor and I want to have 2 displays like this;
![image](https://user-images.githubusercontent.com/47938380/172059092-644bb294-57a6-412f-bdc8-1490f554ae68.png)
The only issue is that this is not possible, because you can't change the top left position of an element. So when you try making it you get this instead:
![image](https://user-images.githubusercontent.com/47938380/172059086-36137d36-a4fe-4a21-8f68-809c2c1abe90.png)

**Describe the solution you'd like**
This can be solved by using a bigger screen but that's not always a good solution, which is why I think that there should be a way to move the elements manually to perfectly align them.

**Comment by Syrcan** [comment]
Our rendering magician has moved on to other projects so there's low chances we end up implementing this.
Closing this issue for this reason.
