### ISSUE TITLE
[BUG] Energy Hatch Takes Power From ALL Sides

### ISSUE THREAD

**Issue by shawnbyday** [GregTechCEu/GregTech#1016]
**Describe the bug**

**Versions**
Forge: 14.23.5.2860
GTCEu: 2.2.3-beta
_Modpack:_ Nomifactory 1.2.3 with GTCEu

**Setup**
_Does this issue happen on Singleplayer, a Server, or both_: Server

**Steps To Reproduce**
1) Can connect cable to any side of energy hatch. Will take power even if not connected to the input side.

**Expected behavior**
Expected to only be able to input power from one side.

**Comment by ALongStringOfNumbers** [comment]
This is not a bug, but rather the intended behavior for energy input hatches.

**Comment by shawnbyday** [comment]
Ok. You don't have to give me an explanation but if you have time for one, I'm curious as to why this is intended? It seems silly and explosionish.

**Comment by ghzdude** [comment]
The current behavior is the same for busses and hatches, in that you can insert/extract from any side instead of only one face.

**Comment by nemo48rus** [comment]
Thats not bug, that is feature!
Great feature.
Just dont clue 2 mechs with 1 interface. Thats easy.

**Comment by DStrand1** [comment]
Closing this as not a bug
