### ISSUE TITLE
[BUG] Dont display all information from many multiblocks.

### ISSUE THREAD

**Issue by nemo48rus** [GregTechCEu/GregTech#1023]
**Describe the bug**
Big separator with 16x parallels dont display full information at screen. Cant set smaller text.
Autoclave have similar "problem".
**Versions**
Forge: 14.23.5.2860
GTCEu: 2.3.1-beta
_Modpack:_ TerraFirmaGreg 3.3.4
_Addons:_ Grecality Multiblocks

**Setup**
Server

**Steps To Reproduce**
1) Put Mars dust to separator

**Expected behavior**
I should see all the text

**Screenshots**
![image](https://user-images.githubusercontent.com/106464618/172926563-75273fa8-539f-47b1-9dff-6e65c7594f5e.png)

**Comment by htmlcsjs** [comment]
i think this is a pack related issue, we dont add mars dust or that top infomation
