### ISSUE TITLE
[Suggestion] Remove tiny dusts

### ISSUE THREAD

**Issue by NaCl0526** [GregTechCEu/GregTech#1027]
for example
![image](https://user-images.githubusercontent.com/62875887/173362275-6662b644-98fa-4746-b908-55fbcd8ccca5.png)
3tiny pile of bauxite dust can be replaced by 33% alumina dust

**Comment by nemo48rus** [comment]
Bauxite is source of rutile dust.
Rutile source of Titan.
Titan need to make ME (AE2).
That is nerf. What for?
If you have your modpack - just change exit of ores in txt.

**Comment by lordclips** [comment]
There is such thing as statistical equivalence. 33% chance of 1 full dust is statistically equivalent to 3 100% chances of 3 tiny dust.

It is not a nerf.

**Comment by NaCl0526** [comment]
This will reduce the sorting pressure

**Comment by YoungOnionMC** [comment]
Sorting and packaging of dusts is a fun mechanic needed for ore processing
