### ISSUE TITLE
[BUG] Ore miners causing game/server crash

### ISSUE THREAD

**Issue by chris1380** [GregTechCEu/GregTech#1031]
**Describe the bug**
Building EV/IV/LuV ore miners without a fluid input hatch makes the game generate crash reports without crashing the game and also the gui woul
Powering them with EU crashes the game/server. 

**Versions**
Forge: 
GTCEu: 
_Modpack:_ nomi-ceu version 1.2.3a (https://www.curseforge.com/minecraft/modpacks/nomi-ceu)

**Setup**
_Does this issue happen on Singleplayer, a Server, or both_: Both
_Does this issue happen on a newly generated world_: Yes

**Steps To Reproduce**
1) Build EV/IV/LuV ore miners without a fluid input hatch.
2) Right-click the controller
3) Game gives error message, crash log: https://pastes.dev/aQ5LrDoKl7
4) Power the multiblock
5) Game/server crashes

**Additional context**
Miner works fine if properly add fluid input hatch.

**Comment by ghzdude** [comment]
this issue is already known and has been fixed with #1030
