### ISSUE TITLE
[SUGGESTION] Change Pump tooltip from "The best way to empty Oceans!"

### ISSUE THREAD

**Issue by Mobius0526** [GregTechCEu/GregTech#1036]
**Describe the bug**
The pump cannot empty the ocean
Water regenerates

**Versions**
Forge: 14.23.5.2860
GTCEu: 2.3.0
_Modpack:_ gcp
_Addons:_ if applicable add all addon names and corresponding versions

**Setup**
_Does this issue happen on Singleplayer, a Server, or both_:
_Does this issue happen on a newly generated world_:

**Steps To Reproduce**
1) I use the pump（block）

**Expected behavior**
The pump empties the ocean

**Screenshots**

**Additional context**

_Please fill in as much useful information as possible. Also please remove all unused sections._

**Comment by Syrcan** [comment]
Our pump isn't meant to empty the ocean, the tooltip is a remain of GregTech 5, where water is finite.
It's a tooltip problem.

**Comment by DjArt** [comment]
How about implementing finite water?
