### ISSUE TITLE
[BUG] Chest Assembling takes 25 seconds longer than Ender Chest Assembling

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/GregTech#1039]
**Describe the bug**
In Assembler:
Chest: 4EU/t, 40 seconds
Ender Chest: 4EU/t, 15 seconds

I don't think chest is more complex than ender chest

**Versions**
GTCEu: 2.3.1

**Setup**
dev env

**Comment by tracer4b** [comment]
Many of the vanilla item assembler recipes take far too much time tbh. 40s is far too long for something which could otherwise be hand crafted with the same efficiency, even at 4 EU/t.
I wouldn’t mind decreasing all such recipe times to 3-5s

**Comment by Syrcan** [comment]
I agree, these recipes are more remnants of GT5.
