### ISSUE TITLE
[BUG] Wrong recipe UHV 16A Dynamo Hatch

### ISSUE THREAD

**Issue by Xikaro** [GregTechCEu/GregTech#1043]
**Describe the bug**
Wrong recipe UHV 16A Dynamo Hatch
He is made from himself.

**Versions**
Forge: 14.23.5.60
GTCEu: 2.3.1

**Screenshots**
![Screenshot_26](https://user-images.githubusercontent.com/55663835/175796596-fa40462e-ccbd-4c85-992c-736ba7a65e31.png)

**Comment by Quarri6343** [comment]
Duplication of #710
