### ISSUE TITLE
[BUG] galacticraft and gregtech Incompatibility 

### ISSUE THREAD

**Issue by LeviSimioni** [GregTechCEu/GregTech#1056]
**Describe the bug**
gregtech oil is overlapping galacticraft oil, causing me to not be able to progress (if possible a solution other than uninstalling the mod)

Forge: 14.23.5.2847
GTCEu: gregtech-1.12.2-2.3.1-beta
_Modpack:_ https://www.curseforge.com/minecraft/modpacks/dungeons-dragons-and-space-shuttles (I tried to add just the gregtech)

this issue happen on Singleplayer
Does this issue happen on a newly generated world_: NO

**Steps To Reproduce**
1) enter the world
2) galacticraft oil does not appear

I want gregtech oil to appear along with galacticraft oil, or for me to be able to combine the two

![Screenshot_2](https://user-images.githubusercontent.com/108428807/176515011-b9aab238-d2e3-40dd-8331-3f8014222c9d.png)

It's my first post here, I hope you understand my problem. thanks for listening

**Comment by Syrcan** [comment]
This issue belongs to modpack dev'ing. This is because of how Forge handle fluid registry.
