### ISSUE TITLE
[BUG] Wireless Digital Interface Cover is broken

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/GregTech#1061]
**Describe the bug**
You are no longer able to use it to bind machines and the monitor in the same dimension remotely
You still can attach the cover to a machine but it does nothing

**Versions**
GTCEu: 2.3.3

**Setup**
dev env

**Additional context**
It is because of #973

**Comment by ALongStringOfNumbers** [comment]
Could you clarify a little bit what you mean by "bind machines and the monitor in the same dimension remotely"? Are you saying that it does not do anything anymore? That you can place it on a machine, but it won't show up on the central monitor?

**Comment by Quarri6343** [comment]
> Are you saying that it does not do anything anymore? That you can place it on a machine, but it won't show up on the central monitor?

Exactly
It is still broken in the latest master branch

**Comment by KuroPeach** [comment]
In the new dev, it can't provide the monitor coordinates to the target machine, and the monitor can't detect the target machine
