### ISSUE TITLE
[Suggestion] QuarkTech armor must restore the player's water stats TFC

### ISSUE THREAD

**Issue by SpeeeDCraft** [GregTechCEu/GregTech#1066]
**Is your feature request related to a problem? Please describe.**
QuarkTech armor restores the player's food reserves, but there is also thirst in TFC, and it does not restore it.

**Describe the solution you'd like**
If you have a tank of fresh water in your inventory (it's from TFC, that's what you can drink), then as soon as the player wants to drink, she will take water from the tank and give the player a drink.

**Comment by Syrcan** [comment]
This is special compatibility with TFC which does no belong to CEu. An addon mod may add a special armor to fit these needs, if desired.
