### ISSUE TITLE
[BUG] Breaking a wrench in hand produces an unusable hotbar slot

### ISSUE THREAD

**Issue by ntdesmond** [GregTechCEu/GregTech#1070]
**Describe the bug**
Breaking the wrench tool by using it on blocks leads to a hotbar slot being unusable with GT machines until this slot is filled with some item 

**Versions**
Forge: `14.23.5.2860`
GTCEu: `2.3.1-beta`, also tested on `2.3.4-beta`, the bug persists
_Modpack:_ [GSE 2.2.2](https://github.com/GregTechCEu/gregtech-skyblock-edition/releases/tag/2.2.2) (latest as for now)

**Setup**
_Does this issue happen on Singleplayer, a Server, or both_: Both, but LoliASM doesn't report crash when in multiplayer
_Does this issue happen on a newly generated world_: yes

**Steps To Reproduce**
1) I did craft a wrench (any material)
2) I spam-clicked a GT block with a wrench until it loses all durability and breaks
3) Now whenever I click a GT machine that can be wrenched, it just does nothing (LoliASM reports crash)
4) This hotbar slot remains unusable until I put another item into it. Slot may be immediately emptied then — it will work properly

**Expected behavior**
My hand should not be treated as a wrench :trollface: 

**Screenshots**
None, but here is a video:

https://user-images.githubusercontent.com/29694249/179066917-3de21e99-80eb-4a5f-967a-952dda58c093.mp4

UPD: I forgot to attach the log file, here it is: https://pastes.dev/5MpJGmHVEt

**Comment by Syrcan** [comment]
Looks like one of the many issues that will be fixed with #690... in a decade or so.
