### ISSUE TITLE
Gregtech machines not fully overclocking.

### ISSUE THREAD

**Issue by mmahoney1** [GregTechCEu/GregTech#1072]
In Nomifactory (GTCEu Port), I have a line of MV machines.  The overclock button says MV, but the power usage and speed does not match what I believe the overclock should be.  The overclock button seems to set machine overclock to 1 tier below what is selected (MV = LV, LV=ULV, etc).

Attached pictures is gold in an MV macerator set to MV overclock.  I believe power usage should be closer to 32 EU/t and speed should be 2.5 - 3 s.

I am also basing this off of Gregetch CE and am not sure how overclocking may have been changed in the unofficial port.  Please correct me if I am missing something obvious.  I have also attached shot of GTCE overclock calc for the same process.

![image_2022-07-17_005303387](https://user-images.githubusercontent.com/39351057/179387537-95a4f7cf-1e41-44c0-99da-a7658841ccf4.png)

![image_2022-07-17_005855227](https://user-images.githubusercontent.com/39351057/179387680-6113eae5-6849-4519-aa63-d4e72a4636c0.png)

**Comment by ghzdude** [comment]
In GTCEu, you no longer get an overclock from ULV to LV. This is intended behavior.

**Comment by mmahoney1** [comment]
Ok, so all overclock calculations should technically start at LV instead of ULV?
