### ISSUE TITLE
[BUG] Hypochlorous Acid recipe is chemically imbalanced

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/GregTech#1076]
**Describe the bug**
![キャプチャ1411](https://user-images.githubusercontent.com/39122497/179725582-7bcb80c7-fb2f-44f5-9d49-36ddadbf45a7.PNG)
https://github.com/GregTechCEu/GregTech/blob/4bf7fbb151bba27fe01861a9c33ed09dc06f995c/src/main/java/gregtech/loaders/recipe/chemistry/ReactorRecipes.java#L271

**Comment by tracer4b** [comment]
This is intended, the full yield can be reached with Mercury
![image](https://user-images.githubusercontent.com/61507029/179749414-b20996f6-0be1-4202-ade5-7d8271054781.png)
