### ISSUE TITLE
[BUG] GT copy command not working

### ISSUE THREAD

**Issue by tracer4b** [GregTechCEu/GregTech#1077]
**Describe the bug**
When trying to click chat messages to copy a metaitem ID, material ID, or ore prefix after running `/gt hand`, an error will be thrown in chat and the copy will not work.

**Versions**
Forge: latest
GTCEu: 2.3.4
_Modpack:_ nomi-ceu v1.3.5

**Setup**
_Does this issue happen on Singleplayer, a Server, or both_: Singleplayer
_Does this issue happen on a newly generated world_: Yes

**Steps To Reproduce**
1) Run `/gt hand` on any GT item
2) Attempt to click one of the outputs to copy its CT reference

**Expected behavior**
copy works

**Screenshots**
![image](https://user-images.githubusercontent.com/61507029/179747545-2b9f4a67-199c-4f86-8ba0-92c1e9f69c88.png)

**Comment by ALongStringOfNumbers** [comment]
I cannot reproduce this issue.

When I run the command and click on any of the items shown in chat, the item is successfully copied to my clipboard.
![2022-07-19_17-59](https://user-images.githubusercontent.com/31759736/179873118-1ffd72fd-2beb-4bfb-9ede-0d057330594d.png)

Can you reproduce this with just GTCEu, instead of in a modpack?

**Comment by brachy84** [comment]
I know that this issue exists but I never could reproduce it either

**Comment by tracer4b** [comment]
The issue doesn't happen on running CEu from git main, but it does happen on a newly installed nomi-ceu 1.3.5. The log file doesn't throw anything more on attempting it.

![image](https://user-images.githubusercontent.com/61507029/179972692-98be2388-d8ee-458e-bd58-3f7eaace691d.png) 
![image](https://user-images.githubusercontent.com/61507029/179973495-94b875f8-3766-444a-b739-127911dd9fd0.png)

**Comment by tracer4b** [comment]
After using advanced debugging techniques (removing mods until the problem reoccurs) this seems to happen when Extra Utilities 2 v1.9.9 is loaded

**Comment by Syrcan** [comment]
Thanks FTB Utilities.
Anyways the copy still works when pressing the X on the JEI UI, so that's fine, and therefore closing this issue.
