### ISSUE TITLE
Super/Quantum Chests only show Output Slot on Output Face [BUG] 

### ISSUE THREAD

**Issue by ghzdude** [GregTechCEu/GregTech#1086]
**Describe the bug**
Super/Quantum chest can show the output slot to AE instead of the internal items in the chest because of the output face.

**Versions**
Forge: 14.23.5.2859
GTCEu: 2.3.4
_Addons:_ Applied Energestics 2: Unofficial Extended Life

**Setup**
Issue occurs on both MP and SP

**Steps To Reproduce**
1. Place super/quantum chest anywhere and fill it with any item past 64
2. Place a storage bus on the output face of the super/quantum chest
3. Observe what is reported in any AE terminal
4. Move the output face of the super/quantum chest away from the storage bus
5. Observe what is reported in any AE terminal

**Expected behavior**
Super/Quantum chest should show the internal items in the chest instead of the output slot (ideally, it should show both output slot and internal items added together, but this may not be possible.)

**Screenshots**
Amount in superchest
![image](https://user-images.githubusercontent.com/44148655/180586145-fd41f03f-415a-46e0-9d9c-a660236b615c.png)

Amount showed in AE
![image](https://user-images.githubusercontent.com/44148655/180586161-ce3ed0b2-a246-46df-a3ca-90ab61336751.png)

Amount in AE after moving output face
![image](https://user-images.githubusercontent.com/44148655/180586197-ff5f56dd-7010-4573-8084-d7cd35c6e1b0.png)

**Comment by pat2rome** [comment]
If you enable "allow input from output side" the same thing happens that does when you move the output face. It sees the ones inside but not the 64 in the output slot.
