### ISSUE TITLE
[BUG] Voiding Cover cannot void fluids in pipe

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/GregTech#1088]
**Describe the bug**
I found GTTransferUtils keep failing drain fluids from the pipe

**Versions**
GTCEu: 2.3.4

**Setup**
dev env

**Steps To Reproduce**
attach voiding cover on any fluid pipe and activate it

**Expected behavior**
voiding cover can void fluids in pipe

**Screenshots**
![image](https://user-images.githubusercontent.com/39122497/180635079-251862a4-c34b-49f3-acaa-a70728e9cbff.png)

**Comment by brachy84** [comment]
This is probably because i didnt implement the `drain` methods in the pipes fluid handler. Idk why i didnt do it.
That is probably also why regulator doesnt work properly...
