### ISSUE TITLE
[BUG] After 2.3.2 patch pyrolyse ovens doesn't get coil bonuses

### ISSUE THREAD

**Issue by Malipf** [GregTechCEu/GregTech#1105]
My power setup broken after updating

Screenshots
![2022-07-30_09 00 11](https://user-images.githubusercontent.com/86558862/181877405-51ce6f72-aaf0-4bf0-9f9e-9012f2184a8e.png)
GTCEu: 2.3.1

![2022-07-30_09 07 07](https://user-images.githubusercontent.com/86558862/181877419-072188d0-7785-414b-b719-f2cbbfd2a0bb.png)
GTCEu: 2.3.4

**Comment by ALongStringOfNumbers** [comment]
This should be fixed with #1078 which will be out in the next release
