### ISSUE TITLE
[BUG] Tempered Glass looks opaque instead of translucent

### ISSUE THREAD

**Issue by Quaerere-Git** [GregTechCEu/GregTech#1112]
**Describe the bug**
Tempered Glass looks opaque instead of translucent.

**Versions**
Forge: 14.23.5.2859
GTCEu: 2.3.4-beta

**Steps To Reproduce**
Just place tempered glass in the world

**Expected behavior**
Tempered Glass looks translucent just like that in inventory.

**Screenshots**
![2022-08-03_15 32 01](https://user-images.githubusercontent.com/42565872/182551436-4d90bd95-7ce3-4d76-af26-7f8141213c51.png)

**Comment by htmlcsjs** [comment]
do you have any other mods installed

**Comment by Quaerere-Git** [comment]
![屏幕截图 2022-08-03 190523](https://user-images.githubusercontent.com/42565872/182593390-cbca9e05-7058-4cf3-b8c5-dba57b0ae99f.png)
All mods are here.

**Comment by htmlcsjs** [comment]
do you happen to use fast graphics, and are you sure thoes are all your mods, and you dont have optifine installed

**Comment by Quaerere-Git** [comment]
It is Fancy graphics, and I'm sure these are all mods I've installed.

**Comment by ALongStringOfNumbers** [comment]
Please try adding CTM and see what happens

**Comment by Quaerere-Git** [comment]
Things work fine once CTM is installed.
