### ISSUE TITLE
GT Axe with Auto-Smelt enchantment smelts only first log.

### ISSUE THREAD

**Issue by idc7** [GregTechCEu/GregTech#1133]
### GregTech CEu Version

v2.3.4 - beta

### Modpack Used

Nomifactory (GTCEu Port) 1.3.5

### Environment

host of open to LAN

### New Worlds

Yes

### Cross-Mod Interaction

Yes

### Expected Behavior

GT Axe with auto-smelt enchantment (EnderCore) should turn all logs cut (with lumberaxe function) into charcoal.

### Actual Behavior

GT Axe with auto-smelt enchantment (EnderCore) does not work correctly with the lumberaxe functionality.
It will smelt only the first block, all blocks broken by the lumberaxe function will be normal log.

### Steps to Reproduce

I have a steel GT axe and i applied auto-smelt enchantment (EnderCore). 
Then cut first log in a 2x2 spruce. 1 piece of charcoal drops and then spruce logs.

### Additional Information

Also CoFH Smelting enchant can be applied to a vanilla Axe, but not a GT axe.

I have not tried with mining hammers to see if the enchant works correctly with them, but I did see that CoFH smashing enchant always drops 2 dust per ore even with fortune 3 on the hammer too. I'm assuming this is for balance reasons and not a bug.

**Comment by DStrand1** [comment]
Closing as not applicable by #1368, Auto-Smelt effects are no longer allowed on Tree-Felling and Area-of-Effect tools like the Axe, Mining Hammer, Drill, etc
