### ISSUE TITLE
Double tank display (TOP addons issue?)

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/GregTech#1137]
### GregTech CEu Version

v2.4.0-alpha

### Modpack Used

GregTech Expert 2

### Addons Installed

GCYM v.1.13
GCYS v0.0.1
GTFO v1.7.0

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

Yes

### Expected Behavior

when I pressed shift key while viewing tank, nothing happens

### Actual Behavior

![キャプチャ1489](https://user-images.githubusercontent.com/39122497/184570217-3a7e447b-3879-4275-81ed-a012d9686bc5.PNG)

this is probably because of TOP addons

### Steps to Reproduce

place a boiler and look at it while pressing shift key

**Comment by IAmNotGEM** [comment]
# Which tank gauge(s) to display (The One Probe, TOP Addons, Both). [default: Both]
    S:fluidGaugeDisplay=TOP Addons

**Comment by IAmNotGEM** [comment]
topaddons_client.cfg
