### ISSUE TITLE
Silicon dioxide smelting recipe is inbalanced

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/GregTech#1138]
### GregTech CEu Version

v2.4.0-alpha

### Modpack Used

GregTech Expert 2

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

because of the recently ore smelting changes,
silicon dioxide which is an impure ore should be smelted into 3 nuggets in the furnace

### Actual Behavior

![キャプチャ1492](https://user-images.githubusercontent.com/39122497/184614483-c7ba5cf4-83ad-446b-a468-b01f885e1b33.PNG)

### Steps to Reproduce

this is a recipe bug

**Comment by TechLord22** [comment]
Fixed in #1831.
