### ISSUE TITLE
Electric drills behaving weirdly

### ISSUE THREAD

**Issue by CrossElectronics** [GregTechCEu/GregTech#1149]
### GregTech CEu Version

v2.3.4

### Modpack Used

Nomifactory CEu Edition 1.3.5

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

Unsure but unlikely

### Expected Behavior

* Electric Drills should always dig out the chosen area centered around the current block being looked at
* Electric Drills should be able to work whilst being charged

### Actual Behavior

![image](https://user-images.githubusercontent.com/31400327/185780752-d00571b3-6c5f-47c7-9404-70bb6f0a1640.png)
* This is an MV drill set to 3x3x3 mode. Observe the marked out region of mining. The drill constantly tries to be smart and throws me off if, say, the area to be mined contains air block (not sure, vide infra)
* And drills don't dig while it's being charged, like if you have batteries on you charging them.

### Steps to Reproduce

Use MV drill as an example:
1) Mine a 3x3x3 cube
![image](https://user-images.githubusercontent.com/31400327/185780941-2c5706a1-c5cf-48b2-a03d-d8d6c0a3c017.png)
2) Count 4 steps left, mine another 3x3x3 cube
![image](https://user-images.githubusercontent.com/31400327/185780964-7a03f965-7cdb-4cdc-9307-eaa9479ad1a9.png)
3) Now look at the 3x3x1 left in the middle, observe the area marked out and try to mine it.
![image](https://user-images.githubusercontent.com/31400327/185781027-ac9a74d6-5986-44bf-86c8-ee6a5696192e.png)
(Here I mined the block in the middle of the top row. Mining the very center block behaves weird as well)
![image](https://user-images.githubusercontent.com/31400327/185781035-2f252005-8218-411d-8968-3ce461f61db7.png)

**Comment by Syrcan** [comment]
Thank you for the investigation. Tools are currently under a rework, in #690... there's still another cataclysm to wait for until that gets merged though.
