### ISSUE TITLE
Certain CT-added recipes don't accept oredict substitutions

### ISSUE THREAD

**Issue by tracer4b** [GregTechCEu/GregTech#1154]
### GregTech CEu Version

2.4.0

### Modpack Used

nomi-ceu 1.3.5

### Environment

Singleplayer

### New Worlds

Unsure

### Cross-Mod Interaction

Yes

### Expected Behavior

Recipes are added correctly by CT2

### Actual Behavior

Certain recipes added by Crafttweaker do not accept oredict substitutions when they are supposed to. T
https://github.com/tracer4b/nomi-ceu/blob/main/overrides/scripts/expertmode.zs#L287
![image](https://user-images.githubusercontent.com/61507029/186145842-a7befc69-1f9f-47ee-9344-fbf633b64266.png)

https://user-images.githubusercontent.com/61507029/186145621-18b5d51f-4e86-43be-96e5-e1b2a8619251.mp4

https://user-images.githubusercontent.com/61507029/186143991-d198f368-1ba6-4224-a1b7-e6b8f39f94a2.mp4

This strangely only happens with certain recipes.
We have tried:
- 1k Fluid Storage (Only Workstation allowed)
- Workstation (Only non-SMD Diode allowed)
- Wetware Lifesupport Circuit Board (Works; All IV circuits allowed)

### Steps to Reproduce

View a recipe with oredict substitutions added by CT in JEI or attempt to run it in a machine.

**Comment by Caedis** [comment]
Note: Also occurs in latest dev
