### ISSUE TITLE
Cheaper "water electrolysis" by making sulfuric acid

### ISSUE THREAD

**Issue by joshop** [GregTechCEu/GregTech#1158]
### GregTech CEu Version

2.3.4

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Assuming this is unintended behavior, the below technique would not be possible.

### Actual Behavior

Electrolysing 1B water takes 45000 EU.
Combining 1B water with 1B of SO₃ to make 1B of H₂SO₄ takes 1120 EU, which can be electrolyzed (5880 EU) into the cost of the sulfur trioxide plus the usual water electrolysis results. These can be combined back into the 1B of SO₃ with only 420EU + 1400 EU, so a total of 8820 EU, substantially less. 
I don't know if this is a bug/unintended, since it requires a bit more complexity than just one electrolyzer.
A similar strategy appears to be possible with salt water, but it's not as substantial a difference in energy usage.

### Steps to Reproduce

Connect LV chemical reactor with sulfur and oxygen to another reactor with more oxygen, then to a third reactor that receives water from a source, then pipe the sulfuric acid into an MV electrolyzer and loop back the sulfur and some of the oxygen. Hydrogen and oxygen will be produced much faster than if you simply had an electrolyzer with the water.

**Comment by TechLord22** [comment]
This behavior was resolved in #1406.
