### ISSUE TITLE
[Suggestion] Configuration to disable crafting plates/double plates in a workbench using a hammer

### ISSUE THREAD

**Issue by SpeeeDCraft** [GregTechCEu/GregTech#117]
**Is your feature request related to a problem? Please describe.**
There are a lot of chemical elements in GT. And deleting each recipe is too long and hard. it would be cool if you could disable the recipe for plates and double plates in the workbench using a hammer.

**Describe the solution you'd like**
I want to have a config that disables crafting through the workbench of plates and double plates.

[Translated by Google :D]

**Comment by Syrcan** [comment]
Such TFC compatibility is unfortunately too troublesome to be handled in the main mod. We don't currently think it is worth it.
