### ISSUE TITLE
How can I make a new MetaItem?

### ISSUE THREAD

**Issue by Hydrogen897** [GregTechCEu/GregTech#1171]
### Your Question

As in the title.

**Comment by BestMod** [comment]
in

/src/main/java/gregtech/common/items/MetaItem1.java

you can register new items

**Comment by Hydrogen897** [comment]
> in
> 
> /src/main/java/gregtech/common/items/MetaItem1.java
> 
> you can register new items

Oh thanks you!But I need like Devtech1 to register MetaItem. And Devtech2 seems to have no custom MetaItem.

**Comment by brachy84** [comment]
Its better to ask these things on discord.
And be more specific with your question. Are you making a mod or are you using crafttweaker. If you are using DevTech, then do this
```zs
import mods.gregtech.MetaItem;

MetaItem.create(1, "some_id");
```
[DevTech source](https://github.com/brachy84/DevTech/blob/master/src/main/java/com/zook/devtech/api/items/MetaItem.java)

**Comment by Hydrogen897** [comment]
> 

Thanks you,and I live in China,I can‘t access Discord.

**Comment by Hydrogen897** [comment]
> Its better to ask these things on discord. And be more specific with your question. Are you making a mod or are you using crafttweaker. If you are using DevTech, then do this
> 
> ```zenscript
> import mods.gregtech.MetaItem;
> 
> MetaItem.create(1, "some_id");
> ```
> 
> [DevTech source](https://github.com/brachy84/DevTech/blob/master/src/main/java/com/zook/devtech/api/items/MetaItem.java)

Should the resource files be placed in the gregtech directory or the devtech directory.

**Comment by brachy84** [comment]
gregtech i think
i dont remember
