### ISSUE TITLE
Configurable Maintenance Hatch does not always apply its bonuses

### ISSUE THREAD

**Issue by Syrcan** [GregTechCEu/GregTech#1178]
### GregTech CEu Version

2.4.1 dev

### Environment

dev

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Setting up recipe duration to 0.9x in the Configurable Maintenance Hatch should work on all multiblocks that perform recipes.

### Actual Behavior

Some multiblocks (example: EBF, PA) ignore the bonus, and perform the recipe with the duration.
Some other multiblocks (example: Vacuum Freezer) get the bonus properly.

### Steps to Reproduce

Why do I have to fill this in 😢

**Comment by lordclips** [comment]
Issue lies in manual overrides of runOverclockingLogic that do not properly account for the hatch bonus.
