### ISSUE TITLE
B:cleanMultiblocks config causes bug

### ISSUE THREAD

**Issue by LasmGratel** [GregTechCEu/GregTech#1186]
### GregTech CEu Version

v2.4.1-beta

### Addons Installed

Gregicality Multiblocks 1.1.4

### Environment

Forge Server

### New Worlds

No

### Cross-Mod Interaction

No

### Expected Behavior

B:cleanMultiblocks=true disables cleanroom requirement for multiblocks

### Actual Behavior

After changing the config, recipes with cleanroom required (e.g. Nano CPU Wafer) processed in a multiblock will **not** take any energy input and gives "WARNING: Machine need more energy" warning. Recipe with the same energy tier in that multiblock processed normally.

### Steps to Reproduce

1) Set `B:cleanMultiblocks=true`
2) Assemble Large Chemical Reactor or Large Circuit Assembler
3) Try to craft Nano CPU Wafer, Elite Circuit Board
4) Gives "WARNING: Machine need more energy" and makes no progress on the recipe

**Comment by lordclips** [comment]
I believe I have found a potential fix but I still need to test it in game to see it isn't a fluke. Will update sometime soon.

For reference: Recipes are checked prior to running in abstractRecipeLogic but also while running, and the progression check does not check for if the config allows a cleanroom recipe to run and therefore seems to fall through.

**Comment by lordclips** [comment]
![2022-09-19_13 40 24](https://user-images.githubusercontent.com/72330305/191079712-8d2b9c1a-e2db-4857-9d68-399c5682e9fe.png)

Can now confirm the issue

**Comment by lordclips** [comment]
For context: Recipe requires EV, supplying 4A IV
