### ISSUE TITLE
Miners collecting cobblestone while it shouldn't

### ISSUE THREAD

**Issue by CrossElectronics** [GregTechCEu/GregTech#1202]
### GregTech CEu Version

v2.4.1-beta

### Modpack Used

Nomifactory CEu Edition 1.4

### Environment

Singleplayer

### New Worlds

Unsure

### Cross-Mod Interaction

Unsure

### Expected Behavior

Both miners should be able to collect ore blocks and only ore blocks from their respective working area

### Actual Behavior

![image](https://user-images.githubusercontent.com/31400327/190639271-f5e8bba1-0662-404b-bddc-9e285f524685.png)
**survival, roof of nether**: The miner placed down first is working properly while the other is constantly collecting cobblestone. Note that there are no cobblestone / stone in nether. If anything it should be netherrack.

![image](https://user-images.githubusercontent.com/31400327/190641323-bdf53e40-7604-4bc1-8b0a-a20fd771c707.png)
**creative, overworld**: The miner placed down first is working properly while the other is collecting mostly cobblestone

### Steps to Reproduce

1) Install two miners close by and power them
2) Observe the miners

### Additional Information

Is it because the latter miner is trying to mine the block that has already been mined i.e. ~~air~~ cobblestone? Since the miner logic replaces the already mined block with cobble to prevent mob from spawning.

Might be related: 
https://github.com/GregTechCEu/GregTech/blob/d9b92f3252a1c43b7a362d4f4e1e12b9f382d951/src/main/java/gregtech/api/capability/impl/miner/MinerLogic.java#L138-L146
https://github.com/GregTechCEu/GregTech/blob/d9b92f3252a1c43b7a362d4f4e1e12b9f382d951/src/main/java/gregtech/api/capability/impl/miner/MinerLogic.java#L238-L249

**Comment by lordclips** [comment]
I'll fuck around with this one and find something out
