### ISSUE TITLE
How can I make rubber plate during Steam Age?

### ISSUE THREAD

**Issue by koiNoCirculation** [GregTechCEu/GregTech#1225]
### Your Question

We know that we need tin cables to make LV machines, and we need to make 1x tin cables to do that.
But I can't do that because there's no recipe of making rubber plates without electric machines.
We know in GTNH we can use a recipe turning 2 rubber ingots into a rubber plate with a plate mold, and in earlier versions of Gregtech the tin cable can be make with tin wire and black carpet.
So how can I make a rubber plate to make tin cable from the steam age?

**Comment by rhit-grellmja** [comment]
steam alloy smelter with plate mold

**Comment by Syrcan** [comment]
There is currently a bug preventing the recipe (2 rubber bars + plate mold -> 1 rubber sheet) from displaying in JEI, however the recipe does exist.
This is fixed for next version.

**Comment by koiNoCirculation** [comment]
@Syrcan Yes, I tried to build the master code and found that recipe.
In addition, I found creosote isn't accepted by combustion generator, is that a bug or it's intended?

**Comment by Syrcan** [comment]
This is fixed now in the newest release, so I am closing this issue.
As for creosote, yes that's intended.
