### ISSUE TITLE
Freezer not working

### ISSUE THREAD

**Issue by yang-fu** [GregTechCEu/GregTech#1231]
### GregTech CEu Version

2.4.1

### Modpack Used

no

### Addons Installed

no

### Environment

singleplayer

### New Worlds

No

### Cross-Mod Interaction

Unsure

### Expected Behavior

put in hot ingot

### Actual Behavior

 The freezer has raw materials but does not work. Every time you need to remove the controller of the freezer and install it again.
But in the new world there is no such problem

### Steps to Reproduce

put in hot ingot

### Additional Information

![unknown](https://user-images.githubusercontent.com/66714394/197446484-d5686aa3-50af-4a6d-b1f8-c14201676e50.png)
![unwn](https://user-images.githubusercontent.com/66714394/197446487-3096272d-0543-4e2a-8f64-328aa10e013a.png)

**Comment by ALongStringOfNumbers** [comment]
This should hopefully have been fixed by #1195, which is out now in the new 2.4.3 release. If not, feel free to comment here and this issue will be reopened.
