### ISSUE TITLE
crash in 1.12.2 forge server

### ISSUE THREAD

**Issue by DAmanc123** [GregTechCEu/GregTech#1233]
### GregTech CEu Version

v2.4.1

### Modpack Used

no modpack

### Addons Installed

no addon

### Environment

forge server

### Side Crashed

Server

### New Worlds

No

### Steps to Reproduce

no thing

### Crash Report

[crash-2022-10-25_13.15.33-server.txt](https://github.com/GregTechCEu/GregTech/files/9857327/crash-2022-10-25_13.15.33-server.txt)

### Additional Information

have no idea

**Comment by Syrcan** [comment]
Duplicate of #1169.

**Comment by DAmanc123** [comment]
i did as you said but it crashed again
[crash-2022-10-25_14.02.22-server.txt](https://github.com/GregTechCEu/GregTech/files/9857647/crash-2022-10-25_14.02.22-server.txt)
