### ISSUE TITLE
When there is only one output bin for the reaction of a large chemical reactor, there is a time interval between the two reactions

### ISSUE THREAD

**Issue by yang-fu** [GregTechCEu/GregTech#1238]
### GregTech CEu Version

2.4.1

### Modpack Used

no

### Addons Installed

Gregicality Multiblocks
MechTech
GregTech Food Option

### Environment

singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Continuous operation of large chemical reactors

### Actual Behavior

When a large chemical reactor is used to process sulfur-containing refined oil and gas
If there is only one output bin
Even with multiple output bins
There will be a pause between each reaction, not continuous
But if you install an arbitrary output bin
There is no gap between the two reactions...
But the newly installed output bin doesn't output anything

### Steps to Reproduce

First make a large chemical reactor and put only one multiple output bins. 
At this time, there will be a time interval between the two reactions,
and then put a random output bin, and the reactions will be continuous without gaps

### Additional Information

https://user-images.githubusercontent.com/66714394/197821085-9624a17d-0337-44b1-b1d2-49b650df5cfc.mp4

**Comment by Syrcan** [comment]
This can hardly be considered a bug, as discussed on Discord. The multiblock calculate available space in the output hatches, but determines there is no room for fluid, until the output hatch actually outputs.
The way to solve this would be to make the output hatch attempt to export the fluid exactly when it receives it, which is a logic we're unsure we want to do.

**Comment by DStrand1** [comment]
> The way to solve this would be to make the output hatch attempt to export the fluid exactly when it receives it, which is a logic we're unsure we want to do
This is unsafe logic, as if you were able to send two fluid output faces towards eachother, they would infinite loop trying to send the fluid back to the other, and would crash the server

It is recommended when making multiblocks to ensure you have enough space to fit the outputs of at least 2 recipes to avoid this problem
