### ISSUE TITLE
Update zh_cn lang

### ISSUE THREAD

**Issue by Alendill** [GregTechCEu/GregTech#1292]
### GregTech CEu Version

gregtech-1.12.2-2.4.4-beta

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Need Chinese translation of "Cleanroom".

### Actual Behavior

No Chinese translation of "Cleanroom".

### Steps to Reproduce

none but please update this file to repo.

https://github.com/Alendill/gregtech-lang/blob/main/zh_cn.lang

I added the Chinese translation of "Cleanroom".

**Comment by Hydrogen897** [comment]
You can pull request this file to assets/gregtech/lang

**Comment by Alendill** [comment]
> You can pull request this file to assets/gregtech/lang

403, no authority.

**Comment by htmlcsjs** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by DStrand1** [comment]
We cannot accept this change unless it is a PR, please make one if you want your change to be added
