### ISSUE TITLE
JEI shows only MV muffler hatch can be used for Electric Blast Furnace

### ISSUE THREAD

**Issue by yuu-electrum** [GregTechCEu/GregTech#1341]
### GregTech CEu Version

2.4.5-beta

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

Yes

### Expected Behavior

JEI's ingame  multiblock pattern guide should just indicate that any Muffler Hatches can be used for Electric Blast Furnace.

### Actual Behavior

The guide above shows only MV Muffler Hatch is acceptable for Electric Blast Furnace's one.

### Steps to Reproduce

1. Search "Electric Blast Furnace" in JEI.
2. Click the Furnace for its recipe.
3. Click "Multiblock Pattern" tab shown next to the crafting recipe tab.
4. Hover on Muffler Hatch at the top layer of the previewed multiblock structure.

**Comment by ALongStringOfNumbers** [comment]
This means that the block occupying this space can only be a muffler hatch, not a casing or anything else. If you right click on the muffler hatch in the JEI multiblock preview, it will show that any tier muffler hatch can be used.

**Comment by yuu-electrum** [comment]
I got what "only this block can be used" means, thank you for your information :-)
