### ISSUE TITLE
Terminal power drain off by 20x

### ISSUE THREAD

**Issue by SRabbelier** [GregTechCEu/GregTech#1353]
### GregTech CEu Version

2.4.5-beta

### Modpack Used

Nomifactory (GTCEu Port) by tracer4b

### Environment

Open to LAN

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

World Prospector app usable for 375s on a single LV battery

### Actual Behavior

Use World Prospector for a mere 18.75 seconds (estimated)

### Steps to Reproduce

- Put one LV battery, fully charged (capacity 120k EU) into Terminal alongside Electric Prospector's Scanner (LV ), and Camera.
- Download World Prospector app from "App Store"
- Open "Battery Manager" app, observe cost for "World Prospector" is 320EU/s
- Open "World Prospector" app
- Select ore to scan for
- Use scanner for 120k/320=375 seconds

### Additional Information

My guess is the cost is per tick, rather than per second.

**Comment by ALongStringOfNumbers** [comment]
Can confirm that something is off with the terminal power drain.

**Comment by Caedis** [comment]
Issue is once the world prospector is running, it changes to calling `discharge` every tick from every second
https://github.com/GregTechCEu/GregTech/blob/master/src/main/java/gregtech/common/items/behaviors/TerminalBehaviour.java#L60
