### ISSUE TITLE
Where are the tools from GTCEu 2.5 ???

### ISSUE THREAD

**Issue by IAmNotGEM** [GregTechCEu/GregTech#1411]
### GregTech CEu Version

2.5

### Environment

singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

Yes

### Expected Behavior

1

### Actual Behavior

Where are the tools from GTCEu 2.5 ???

### Steps to Reproduce

1

**Comment by ALongStringOfNumbers** [comment]
The Tools rework was about re-implementing tools in a saner and more extensible way in code for both us and addon makers. There were no new tools that were introduced in this rework, although the possibility is now open, if we deem that such new tools are needed.
