### ISSUE TITLE
New tools cannot be reused via AE2 craft pattern

### ISSUE THREAD

**Issue by Alendill** [GregTechCEu/GregTech#1417]
### GregTech CEu Version

gregtech-1.12.2-2.5.0-beta

### Addons Installed

Mod list:
gregtech-1.12.2-2.5.0-beta
appliedenergistics2-rv6-stable-7

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

Yes

### Expected Behavior

Tools of the same material but with different durability levels can be reused as last version(2.4.+)

### Actual Behavior

Auto crafting will repeatedly craft new tools even if the tool already exists.

### Steps to Reproduce

1. I update gregtech-1.12.2-2.4.5-beta to gregtech-1.12.2-2.5.0-beta
2. Restart game.
3. Enter the world I used to played.
4. Crafted a craft pattern for the tool, like Steel hammer.
5. Crafted a Steel wrench craft pattern which using Steel hammer.
6. I started craft 10 steel wrench.
7. At last, there are 11 steel hammer in ME storage server.

**Comment by TechLord22** [comment]
As AE2 is not supported anymore, I would suggest moving to a fork, AE2 Unofficial Extended Life. It can be found [here](https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life) on CurseForge. Autocrafting with tools in recipes is functional there.

It is likely that with regular AE2, enabling substitutions will fix this issue as well, but this is not confirmed.
