### ISSUE TITLE
Tool durability got nerfed too hard by the rework

### ISSUE THREAD

**Issue by steamdwarfjr** [GregTechCEu/GregTech#1430]
### GregTech CEu Version

2.5.0

### Related Problem

Example: diamond mining drill got it's durability cut from 37120 down to 768. Almos 50 times less durability then before. Other tool materials also took a massive hit. Drills are barely better then mining hammers now.

### Your Solution

Unnerf durability back a bit? Maybe not as high as before.

**Comment by CrossElectronics** [comment]
Definitely true. The whole point of electric tool is to reduce chores. What's the point of it if you have to constantly swap tips before the charge even runs out? I cannot even clear out one vein with an HV V. Steel Drill now.
