### ISSUE TITLE
Crash when you craft an HSS-S turbine rotor

### ISSUE THREAD

**Issue by omegazion** [GregTechCEu/GregTech#1433]
### GregTech CEu Version

2.5.0

### Addons Installed

JEI 1.12.2-4.16.1.302

### Environment

Single Player

### Side Crashed

Client

### New Worlds

Yes

### Steps to Reproduce

1) Put 8 HSS-S turbine blades and 1 long magnalium rod into an HV+ assembler.
2) Grab the output. It crashes when you do.

### Crash Report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  GregTechLoadingPlugin (gregtech-1.12.2-2.5.0-beta.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 1/18/23 12:17 PM
Description: Rendering screen

java.lang.IllegalArgumentException: Material hsss does not have a tool harvest level! Is probably not a Tool Material
	at gregtech.api.unification.material.Material.getToolHarvestLevel(Material.java:192)
	at gregtech.common.items.behaviors.AbstractMaterialPartBehavior.addInformation(AbstractMaterialPartBehavior.java:77)
	at gregtech.common.items.behaviors.TurbineRotorBehavior.addInformation(TurbineRotorBehavior.java:59)
	at gregtech.api.items.metaitem.MetaItem.func_77624_a(MetaItem.java:577)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.gui.GuiScreen.func_191927_a(GuiScreen.java:143)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:137)
	at net.minecraft.client.gui.inventory.GuiContainer.func_191948_b(GuiContainer.java:175)
	at gregtech.api.gui.impl.ModularUIGui.func_73863_a(ModularUIGui.java:134)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at gregtech.api.unification.material.Material.getToolHarvestLevel(Material.java:192)
	at gregtech.common.items.behaviors.AbstractMaterialPartBehavior.addInformation(AbstractMaterialPartBehavior.java:77)
	at gregtech.common.items.behaviors.TurbineRotorBehavior.addInformation(TurbineRotorBehavior.java:59)
	at gregtech.api.items.metaitem.MetaItem.func_77624_a(MetaItem.java:577)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.gui.GuiScreen.func_191927_a(GuiScreen.java:143)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:137)
	at net.minecraft.client.gui.inventory.GuiContainer.func_191948_b(GuiContainer.java:175)
	at gregtech.api.gui.impl.ModularUIGui.func_73863_a(ModularUIGui.java:134)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: gregtech.api.gui.impl.ModularUIGui
	Mouse location: Scaled: (270, 89). Absolute: (1083, 659)
	Screen size: Scaled: (480, 255). Absolute: (1920, 1017). Scale factor of 4

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['omegazion'/4299, l='MpServer', x=-154.31, y=67.00, z=293.55]]
	Chunk stats: MultiplayerChunkCache: 598, 598
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-184,64,252), Chunk: (at 8,4,12 in -12,15; contains blocks -192,0,240 to -177,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3216 game time, 3216 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 169 total; [EntityCreeper['Creeper'/4609, l='MpServer', x=-146.50, y=33.00, z=268.50], EntityCreeper['Creeper'/5378, l='MpServer', x=-75.50, y=14.00, z=358.50], EntityItem['item.tile.rail'/4100, l='MpServer', x=-133.10, y=23.00, z=235.73], EntityItem['item.tile.gravel'/4101, l='MpServer', x=-133.15, y=24.00, z=254.55], EntityItem['item.tile.gravel'/4102, l='MpServer', x=-131.11, y=24.00, z=254.13], EntityItem['item.tile.gravel'/4103, l='MpServer', x=-134.28, y=24.00, z=254.13], EntityItem['item.tile.gravel'/4104, l='MpServer', x=-135.09, y=24.00, z=254.16], EntityItem['item.tile.gravel'/4105, l='MpServer', x=-137.87, y=24.00, z=254.63], EntityCreeper['Creeper'/4106, l='MpServer', x=-136.50, y=18.00, z=246.50], EntityZombie['Zombie'/4107, l='MpServer', x=-135.50, y=18.00, z=245.50], EntityCow['Cow'/4108, l='MpServer', x=-143.50, y=72.00, z=247.50], EntityCow['Cow'/4109, l='MpServer', x=-146.20, y=75.00, z=249.50], EntityChicken['Chicken'/4110, l='MpServer', x=-133.59, y=69.00, z=253.16], EntityChicken['Chicken'/4111, l='MpServer', x=-132.50, y=69.00, z=244.50], EntityChicken['Chicken'/4112, l='MpServer', x=-125.52, y=68.00, z=253.22], EntityChicken['Chicken'/4113, l='MpServer', x=-135.50, y=70.00, z=246.50], EntitySkeleton['Skeleton'/4116, l='MpServer', x=-122.47, y=18.00, z=289.23], EntityCreeper['Creeper'/5396, l='MpServer', x=-100.90, y=24.00, z=232.70], EntityItem['item.tile.torch'/4117, l='MpServer', x=-130.14, y=19.00, z=291.22], EntityCreeper['Creeper'/5397, l='MpServer', x=-95.50, y=24.00, z=230.50], EntityItem['item.tile.rail'/4118, l='MpServer', x=-137.88, y=18.00, z=298.13], EntitySpider['Spider'/5398, l='MpServer', x=-99.50, y=24.00, z=229.50], EntitySpider['Spider'/5399, l='MpServer', x=-99.86, y=24.00, z=231.87], EntityItem['item.tile.gravel'/4120, l='MpServer', x=-128.03, y=14.00, z=317.06], EntityItem['item.tile.gravel'/4121, l='MpServer', x=-129.85, y=14.00, z=317.88], EntityItem['item.tile.gravel'/4122, l='MpServer', x=-128.85, y=14.00, z=317.17], EntityCreeper['Creeper'/4124, l='MpServer', x=-140.50, y=17.00, z=305.50], EntityCow['Cow'/4126, l='MpServer', x=-152.17, y=68.00, z=301.25], EntityCow['Cow'/4127, l='MpServer', x=-151.82, y=68.00, z=307.21], EntityChicken['Chicken'/4128, l='MpServer', x=-135.88, y=66.00, z=320.49], EntityChicken['Chicken'/4129, l='MpServer', x=-133.50, y=67.00, z=331.50], EntityChicken['Chicken'/4130, l='MpServer', x=-124.83, y=64.00, z=331.50], EntityChicken['Chicken'/4131, l='MpServer', x=-141.59, y=67.00, z=347.84], EntityChicken['Chicken'/4132, l='MpServer', x=-130.43, y=66.00, z=336.14], EntityChicken['Chicken'/4133, l='MpServer', x=-135.76, y=67.00, z=359.11], EntityChicken['Chicken'/4134, l='MpServer', x=-140.50, y=67.00, z=352.50], EntityChicken['Chicken'/4135, l='MpServer', x=-132.57, y=67.00, z=361.22], EntityChicken['Chicken'/4143, l='MpServer', x=-114.50, y=70.00, z=232.50], EntityCreeper['Creeper'/5423, l='MpServer', x=-122.23, y=23.00, z=255.47], EntitySheep['Sheep'/4144, l='MpServer', x=-111.80, y=69.00, z=236.60], EntitySheep['Sheep'/4145, l='MpServer', x=-115.50, y=69.00, z=238.50], EntitySheep['Sheep'/4146, l='MpServer', x=-116.50, y=69.00, z=237.50], EntitySkeleton['Skeleton'/5426, l='MpServer', x=-101.50, y=21.00, z=257.50], EntityChicken['Chicken'/4147, l='MpServer', x=-110.63, y=69.00, z=235.86], EntitySkeleton['Skeleton'/5427, l='MpServer', x=-99.50, y=21.00, z=257.50], EntityMinecartChest['Minecart with Chest'/4148, l='MpServer', x=-116.50, y=24.06, z=244.50], EntitySkeleton['Skeleton'/5428, l='MpServer', x=-97.50, y=21.00, z=257.50], EntityChicken['Chicken'/4149, l='MpServer', x=-104.79, y=68.00, z=259.38], EntityItem['item.tile.torch'/4150, l='MpServer', x=-117.96, y=19.00, z=271.97], EntitySkeleton['Skeleton'/4151, l='MpServer', x=-125.50, y=19.00, z=267.50], EntityMinecartChest['Minecart with Chest'/4152, l='MpServer', x=-120.50, y=19.06, z=274.50], EntityItem['item.tile.torch'/4153, l='MpServer', x=-122.20, y=19.00, z=278.88], EntityItem['item.tile.torch'/4154, l='MpServer', x=-112.07, y=14.00, z=296.88], EntityCow['Cow'/4159, l='MpServer', x=-116.73, y=67.00, z=290.82], EntityItem['item.tile.gravel'/4160, l='MpServer', x=-124.68, y=14.00, z=316.70], EntityItem['item.tile.gravel'/4161, l='MpServer', x=-126.68, y=14.00, z=317.46], EntityItem['item.tile.gravel'/4162, l='MpServer', x=-125.43, y=14.00, z=316.94], EntityMinecartChest['Minecart with Chest'/4163, l='MpServer', x=-123.50, y=21.06, z=311.50], EntityItem['item.tile.torch'/4164, l='MpServer', x=-114.67, y=21.00, z=305.74], EntityItem['item.tile.torch'/4166, l='MpServer', x=-114.13, y=21.00, z=331.21], EntitySkeleton['Skeleton'/4171, l='MpServer', x=-108.50, y=18.00, z=232.78], EntityChicken['Chicken'/4173, l='MpServer', x=-109.86, y=69.00, z=237.29], EntitySheep['Sheep'/4174, l='MpServer', x=-107.81, y=68.00, z=243.29], EntityChicken['Chicken'/4175, l='MpServer', x=-97.50, y=67.00, z=251.50], EntityChicken['Chicken'/4176, l='MpServer', x=-110.60, y=69.00, z=241.40], EntityBat['Bat'/4179, l='MpServer', x=-104.43, y=20.10, z=258.25], EntityChicken['Chicken'/4183, l='MpServer', x=-104.65, y=68.00, z=263.50], EntityChicken['Chicken'/4184, l='MpServer', x=-99.75, y=69.00, z=258.85], EntityChicken['Chicken'/4185, l='MpServer', x=-108.50, y=68.00, z=263.50], EntityChicken['Chicken'/4186, l='MpServer', x=-98.50, y=69.00, z=259.15], EntityMinecartChest['Minecart with Chest'/4187, l='MpServer', x=-105.50, y=18.06, z=285.50], EntityZombie['Zombie'/4955, l='MpServer', x=-137.50, y=19.00, z=289.50], EntityItem['item.tile.gravel'/4188, l='MpServer', x=-109.56, y=21.00, z=285.56], EntitySkeleton['Skeleton'/4956, l='MpServer', x=-136.30, y=19.00, z=288.30], EntityItem['item.tile.gravel'/4189, l='MpServer', x=-108.51, y=21.00, z=286.40], EntityItem['item.tile.gravel'/4190, l='MpServer', x=-109.55, y=21.00, z=286.49], EntityBat['Bat'/4192, l='MpServer', x=-100.25, y=20.10, z=285.57], EntitySkeleton['Skeleton'/4961, l='MpServer', x=-143.50, y=17.00, z=222.50], EntityItem['item.tile.rail'/4194, l='MpServer', x=-102.88, y=21.00, z=287.77], EntityItem['item.tile.rail'/4195, l='MpServer', x=-96.93, y=25.00, z=295.88], EntityItem['item.tile.rail'/4198, l='MpServer', x=-103.88, y=21.00, z=291.13], EntityItem['item.tile.rail'/4199, l='MpServer', x=-101.13, y=21.00, z=302.21], EntityItem['item.tile.rail'/4200, l='MpServer', x=-103.36, y=21.00, z=302.21], EntityItem['item.tile.torch'/4201, l='MpServer', x=-107.83, y=21.00, z=306.10], EntityItem['item.tile.rail'/4202, l='MpServer', x=-96.02, y=21.00, z=306.18], EntityItem['item.tile.rail'/4203, l='MpServer', x=-103.26, y=21.00, z=304.25], EntityItem['item.item.seeds'/4205, l='MpServer', x=-109.77, y=64.00, z=345.94], EntitySkeleton['Skeleton'/5234, l='MpServer', x=-153.50, y=10.00, z=272.50], EntitySkeleton['Skeleton'/5235, l='MpServer', x=-158.50, y=10.00, z=271.50], EntityChicken['Chicken'/4216, l='MpServer', x=-82.08, y=72.00, z=238.85], EntitySkeleton['Skeleton'/4728, l='MpServer', x=-134.50, y=19.00, z=270.50], EntityCreeper['Creeper'/4219, l='MpServer', x=-87.82, y=16.00, z=252.47], EntityItem['item.item.seeds'/5500, l='MpServer', x=-115.94, y=65.00, z=311.65], EntityChicken['Chicken'/4221, l='MpServer', x=-87.80, y=71.00, z=251.58], EntityChicken['Chicken'/4222, l='MpServer', x=-93.48, y=70.00, z=250.15], EntitySkeleton['Skeleton'/5502, l='MpServer', x=-81.50, y=25.00, z=265.50], EntitySheep['Sheep'/4223, l='MpServer', x=-89.82, y=71.00, z=250.51], EntityItem['item.tile.torch'/4224, l='MpServer', x=-93.13, y=21.00, z=260.95], EntityCreeper['Creeper'/5505, l='MpServer', x=-118.50, y=14.00, z=301.50], EntitySheep['Sheep'/4226, l='MpServer', x=-89.49, y=70.00, z=258.73], EntitySkeleton['Skeleton'/5506, l='MpServer', x=-112.75, y=14.00, z=303.05], EntitySheep['Sheep'/4227, l='MpServer', x=-92.50, y=68.00, z=258.50], EntitySheep['Sheep'/4228, l='MpServer', x=-87.55, y=67.00, z=262.66], EntityMinecartChest['Minecart with Chest'/4232, l='MpServer', x=-82.50, y=26.06, z=283.50], EntityItem['item.tile.torch'/4233, l='MpServer', x=-93.97, y=25.00, z=296.35], EntityZombie['Zombie'/5257, l='MpServer', x=-83.19, y=26.00, z=265.50], EntityItem['item.tile.torch'/4238, l='MpServer', x=-95.15, y=21.00, z=318.85], EntityItem['item.tile.rail'/4239, l='MpServer', x=-95.13, y=21.00, z=304.22], EntityChicken['Chicken'/4242, l='MpServer', x=-77.50, y=71.00, z=244.50], EntityChicken['Chicken'/4243, l='MpServer', x=-85.16, y=72.00, z=240.59], EntityChicken['Chicken'/4244, l='MpServer', x=-79.50, y=71.00, z=246.50], EntityItem['item.tile.rail'/4501, l='MpServer', x=-143.75, y=19.00, z=254.66], EntitySheep['Sheep'/4246, l='MpServer', x=-77.50, y=71.00, z=244.50], EntityChicken['Chicken'/3990, l='MpServer', x=-224.57, y=70.00, z=225.79], EntitySheep['Sheep'/4247, l='MpServer', x=-76.49, y=71.00, z=245.76], EntityChicken['Chicken'/3991, l='MpServer', x=-233.50, y=72.00, z=229.50], EntitySheep['Sheep'/4248, l='MpServer', x=-76.38, y=72.00, z=242.08], EntityChicken['Chicken'/3992, l='MpServer', x=-230.08, y=71.00, z=230.60], EntitySkeleton['Skeleton'/4000, l='MpServer', x=-210.50, y=28.00, z=373.50], EntityChicken['Chicken'/4006, l='MpServer', x=-204.50, y=68.00, z=225.50], EntityChicken['Chicken'/4007, l='MpServer', x=-195.88, y=71.00, z=220.59], EntityChicken['Chicken'/4008, l='MpServer', x=-195.51, y=72.00, z=239.19], EntityChicken['Chicken'/4009, l='MpServer', x=-205.08, y=67.00, z=221.24], EntityCreeper['Creeper'/4011, l='MpServer', x=-196.50, y=11.00, z=309.50], EntitySkeleton['Skeleton'/4014, l='MpServer', x=-203.50, y=13.00, z=308.50], EntitySkeleton['Skeleton'/5554, l='MpServer', x=-89.50, y=18.00, z=315.50], EntityZombie['Zombie'/4536, l='MpServer', x=-145.73, y=22.00, z=344.50], EntityMinecartChest['Minecart with Chest'/4027, l='MpServer', x=-181.50, y=13.06, z=244.50], EntityBat['Bat'/4028, l='MpServer', x=-189.63, y=47.10, z=333.28], EntityBat['Bat'/4802, l='MpServer', x=-148.08, y=52.10, z=348.75], EntityZombieVillager['Zombie Villager'/5059, l='MpServer', x=-191.25, y=15.00, z=337.54], EntityZombie['Zombie'/4036, l='MpServer', x=-175.57, y=25.00, z=216.19], EntityItem['item.tile.torch'/4037, l='MpServer', x=-168.76, y=14.00, z=246.03], EntityItem['item.tile.rail'/4038, l='MpServer', x=-161.88, y=23.00, z=259.88], EntityItem['item.tile.rail'/4039, l='MpServer', x=-165.25, y=9.00, z=286.41], EntityItem['item.tile.rail'/4040, l='MpServer', x=-164.84, y=9.00, z=281.76], EntityItem['item.tile.rail'/4041, l='MpServer', x=-163.76, y=9.00, z=282.37], EntitySkeleton['Skeleton'/4553, l='MpServer', x=-99.50, y=21.00, z=282.50], EntityItem['item.tile.rail'/4042, l='MpServer', x=-164.95, y=9.00, z=280.66], EntityZombie['Zombie'/5066, l='MpServer', x=-116.74, y=14.00, z=291.55], EntityItem['item.tile.rail'/4043, l='MpServer', x=-165.73, y=9.00, z=291.25], EntitySkeleton['Skeleton'/4555, l='MpServer', x=-103.28, y=19.00, z=286.48], EntityItem['item.tile.rail'/4044, l='MpServer', x=-163.13, y=9.00, z=293.88], EntityCreeper['Creeper'/5324, l='MpServer', x=-143.50, y=20.00, z=239.50], EntitySkeleton['Skeleton'/4045, l='MpServer', x=-171.08, y=17.00, z=350.57], EntityItem['item.item.seeds'/4564, l='MpServer', x=-118.15, y=65.00, z=306.11], EntityPlayerSP['omegazion'/4299, l='MpServer', x=-154.31, y=67.00, z=293.55], EntityCreeper['Creeper'/5340, l='MpServer', x=-186.50, y=16.00, z=314.50], EntityMinecartChest['Minecart with Chest'/4064, l='MpServer', x=-147.50, y=20.06, z=214.50], EntityMinecartChest['Minecart with Chest'/4065, l='MpServer', x=-145.50, y=20.06, z=216.50], EntityItem['item.tile.torch'/4066, l='MpServer', x=-146.13, y=24.00, z=247.62], EntityItem['item.tile.rail'/5090, l='MpServer', x=-145.68, y=24.00, z=254.67], EntityItem['item.tile.torch'/4067, l='MpServer', x=-147.88, y=24.00, z=253.45], EntityCow['Cow'/4069, l='MpServer', x=-145.50, y=73.00, z=246.50], EntityCow['Cow'/4070, l='MpServer', x=-144.50, y=72.00, z=245.50], EntityItem['item.tile.torch'/4071, l='MpServer', x=-153.69, y=23.00, z=258.82], EntityItem['item.tile.rail'/4072, l='MpServer', x=-154.75, y=23.00, z=259.88], EntityItem['item.tile.rail'/4073, l='MpServer', x=-153.38, y=23.00, z=258.52], EntityZombie['Zombie'/5353, l='MpServer', x=-147.50, y=27.00, z=280.50], EntitySquid['Squid'/5098, l='MpServer', x=-213.48, y=58.40, z=335.10], EntityCreeper['Creeper'/4075, l='MpServer', x=-148.44, y=19.00, z=274.77], EntityCow['Cow'/4076, l='MpServer', x=-137.55, y=70.00, z=264.81], EntitySkeleton['Skeleton'/5359, l='MpServer', x=-165.30, y=15.00, z=315.49], EntitySquid['Squid'/5109, l='MpServer', x=-203.73, y=58.24, z=346.02], EntityCreeper['Creeper'/4855, l='MpServer', x=-97.50, y=21.00, z=313.50], EntityMinecartChest['Minecart with Chest'/4092, l='MpServer', x=-129.50, y=19.06, z=239.50], EntitySquid['Squid'/5116, l='MpServer', x=-184.62, y=54.04, z=284.55], EntitySquid['Squid'/5118, l='MpServer', x=-192.00, y=54.55, z=283.31], EntitySquid['Squid'/5119, l='MpServer', x=-188.60, y=50.21, z=299.66]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 716684944 bytes (683 MB) / 2415919104 bytes (2304 MB) up to 12884901888 bytes (12288 MB)
	JVM Flags: 11 total; -XX:-OmitStackTraceInFastThrow -Xms512M -Xmx12288M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID             | Version      | Source                                        | Signature                                |
	|:------ |:-------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft      | 1.12.2       | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp            | 9.42         | minecraft.jar                                 | None                                     |
	| LCHIJA | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2859.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge          | 14.23.5.2859 | forge-1.12.2-14.23.5.2859.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | codechickenlib | 3.2.3.358    | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | jei            | 4.16.1.302   | jei_1.12.2-4.16.1.302.jar                     | None                                     |
	| LCHIJA | gregtech       | 2.5.0-beta   | gregtech-1.12.2-2.5.0-beta.jar                | None                                     |

	Loaded coremods (and transformers): 
GregTechLoadingPlugin (gregtech-1.12.2-2.5.0-beta.jar)
  gregtech.asm.GregTechTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13476 Compatibility Profile Context 22.19.171.257' Renderer: 'Radeon (TM) RX 470 Graphics'
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: Radeon (TM) RX 470 Graphics GL version 4.5.13476 Compatibility Profile Context 22.19.171.257, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz

**Comment by ALongStringOfNumbers** [comment]
This should be fixed by #1408

**Comment by LAGIdiot** [comment]
This problem is not happening on current master (1fae38416de4b76fe0c3bd1c72d1463e1abc03b9). So it will be fixed in next release.
