### ISSUE TITLE
Possibility to exclude Stone Crusher from game

### ISSUE THREAD

**Issue by DjArt** [GregTechCEu/GregTech#1445]
### GregTech CEu Version

v2.5.0

### Related Problem

Stone Crusher provides some sort of infinite resources, I think that shouldn't be applicable for hard-mode game.

### Your Solution

Should be nice to able to disable it via config file.

**Comment by Caedis** [comment]
Use crafttweaker to remove and hide the recipe from jei?

**Comment by IntegerLimit** [comment]
You can also do `mods.jei.JEI.hideCategory("gregtech.rock_breaker")` to remove all recipes of Rock Breakers. I'm not sure about the `gregtech.rock_breaker` part.

**Comment by ALongStringOfNumbers** [comment]
Like the other comments in this issue have stated, the easiest way would be to remove the recipes from the rock breaker using crafttweaker, and then hide the JEI category. We are not planning on offering config options to disable individual machines.
