### ISSUE TITLE
LSB-Large Solar Boiler

### ISSUE THREAD

**Issue by GIBRID64r** [GregTechCEu/GregTech#1456]
### GregTech CEu Version

2.4.5 (I'm playing on TFG:NH, and the version there so far is like this)

### Related Problem

Tired of putting a lot of small boilers? Then the organization "Boilermakers" requires new ones, namely "Big solar boiler"!

### Your Solution

I suggest adding a Large solar boiler (I'll shorten it to LSB). Because there is already solid fuel and liquid in 1 boiler.

**Comment by GIBRID64r** [comment]
But I think most people will think that it is useless..

**Comment by ALongStringOfNumbers** [comment]
Such a multiblock is not planned, although if you desire, you, or a packmaker, can implement it through Multiblock Tweaker or though an addon mod
