### ISSUE TITLE
How does overclock work in GTCEu?

### ISSUE THREAD

**Issue by FranklinRuttoCh** [GregTechCEu/GregTech#1457]
### Your Question

Version of GTCEu: v2.5.0
Modpack: nomi-ceu v1.5.0
I am setting a pyrolyse oven to process the recipe below:
16 wood to 4 ash and 200mB heavy oil, 
which costs 192EU/t (HV) and 16.0 sec.
In order to save blocks, I place 4 pyrolyse ovens together to use less energy hatches to supply energy, like this:
![image](https://user-images.githubusercontent.com/119395637/215311578-0a22490a-e16c-4f1b-ab96-90c65339b32f.png)
![image](https://user-images.githubusercontent.com/119395637/215311606-f3c1ce8b-38ae-4c01-b740-54975af18c33.png)
The control block shows that the max energy is 4096EU/t (EV)，
When I scan the control block with a scanner, it shows that the max energy input is 4096EU/t (IV).
The actual working energy consumption of the recipe mentioned above is 192 * 4 * 4 = 3072EU/t. 
This means that the machine is overlocked to IV level, which causes the lack of energy when using a shared energy hatch.
I remember that in the same situation of GT5, the machine should be overlocked to EV tier instead of IV tier.
I wonder whether the situation I met is a **feature** or a **bug**.

**Comment by tracer4b** [comment]
Since the multiblocks each detect 1 IV Energy Hatch in their structure, their max energy input will be 4096 EU/t. So you won't be able to run both multiblocks at the same time with the same energy hatch, because they need more energy than the hatch can support. This is the correct behaviour.  

You will need to have 1 set of energy hatches for each multiblock in this case

**Comment by lily-es** [comment]
Hmm maybe it would be nice to have a way to configure the desired overclock on multiblocks like there is with singleblock machines? If that feature does not exist yet

**Comment by tracer4b** [comment]
You can control the energy hatches you put on the multiblock

**Comment by lily-es** [comment]
Yeah thats for sure. Just use 4 EV hatches in this case if you want it to run at EV. It would just be a feature that makes sharing energy hatches even nicer imo
