### ISSUE TITLE
Suggestion: Add vajra

### ISSUE THREAD

**Issue by firendlyGhost** [GregTechCEu/GregTech#1467]
### GregTech CEu Version

N/A

### Related Problem

N/A

### Your Solution

it would be cool if it was in the game for lore sake. It could be LUV, have infinite durability, have instamine, shift toggle for silk touch and for example it would be really cool if it could perform the right click functions of wire cutter and wrench to connect pipes and wires (this last part is just a suggestion it might be Op? i dont really think so but the devs might have a different viewpoint. I see it more like the multitool from GT6 (that would also be a useful item to add)

TDLR: Vajra should be in the game, for lore and also the other IC2 and gravi suit stuff is already implemented, I imagine its not too hard to implement. And it could be very useful (see example above) or just for precision insta mine.

**Comment by ALongStringOfNumbers** [comment]
This tool is not currently planned for CEu. However, since the rework of our tool system, this tool should be somewhat easy to add with an addon mod if you so desire.
