### ISSUE TITLE
Certus Quartz Dust from AE2 UEL is unusable

### ISSUE THREAD

**Issue by Americangerman1** [GregTechCEu/GregTech#1468]
### GregTech CEu Version

v1.5 (Normal)

### Your Solution

Can you add a ore dictionary entry for "Certus Quartz Dust" from "AE2 Unofficial Extended Life"? 
The dust can be gained from mineshaft chests and has no use in any recipe, and JEI only says you gain it from those chests.

### Additional Information

It takes up space in chests and drives but it seems a waste to trash it when it could be valuable in the early game. 
We can already get a dark steel boots and sword from dungeon chests and that gives a large boost to early game survival. 

It would just be a nice thing to have.

**Comment by ghzdude** [comment]
This issue does not apply to GregtechCEu, but it seems you are playing the CEu edition of Nomifactory. You may want to close this issue and post it at https://github.com/tracer4b/nomi-ceu/issues.

**Comment by IntegerLimit** [comment]
Closed with https://github.com/tracer4b/nomi-ceu/commit/ce18dbe46019b78a3d65d7e56663762e8def4490.

**Comment by TechLord22** [comment]
This appears to be a modpack-specific issue as mentioned by others. As it has also already been fixed elsewhere, I am closing this issue.
