### ISSUE TITLE
Crafting Station Inventory Tab hides 9th row making some items inaccessible

### ISSUE THREAD

**Issue by mateskr692** [GregTechCEu/GregTech#1472]
### GregTech CEu Version

v2.5.0-beta

### Modpack Used

Nomifactory GTCEu

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

All items in connected inventories should be accessible through the Connected Inventories tab rather than some being missing.

### Actual Behavior

When going to Crafting Station conncected inventories tab, some items are hidden and inaccessible even if they are in connected inventories and in the crafting tab you can them as available. I believe this is happening because Inventory tab only shows 8 columns of items and instead of wrapping the last column, it hides them behind the GUI so you cant retrieve them,

### Steps to Reproduce

Place a crafting station next to a chest and put 8 different items in the chest. They are all visible in the crafting station. Now put the 9th, different item and it doesnt show in the inventory tab

### Additional Information

![image](https://user-images.githubusercontent.com/32541962/216746507-30d2510a-211e-44dd-9c25-77ef77388c5e.png)
In the first screenshot both Iron and Gold ingots are accesible. Putting in the Lilac flower pushes the gold of of bounds making it unavailable
![image](https://user-images.githubusercontent.com/32541962/216746517-42fb7770-6e87-45e5-8e1c-79e09fd7157b.png)
Putting in the apples, pushes the Iron out of bounds and makes the gold show back in the new row
![image](https://user-images.githubusercontent.com/32541962/216746532-e054f105-8c17-4a27-829f-5a56022d1239.png)

**Comment by Caedis** [comment]
Hmm, verified. Looking into now
