### ISSUE TITLE
OreDict Filter Freezing Gaming

### ISSUE THREAD

**Issue by Correlander** [GregTechCEu/GregTech#1480]
### GregTech CEu Version

v2.5.0

### Modpack Used

Nomifactory CEU

### Environment

Forge Server, but I can reproduce in singleplayer.

### New Worlds

Yes

### Cross-Mod Interaction

Unsure

### Expected Behavior

Normally when the text hits the edge of the window it makes a new line and you are able to scroll down etc.

### Actual Behavior

Instead of a line break, it just keeps going off the edge of my screen. Eventually, it won't let you type anymore after going off the screen for a bit, but it won't freeze. It only freezes if you use operators. The only one I tested with while reproducing in singleplayer was !, which successfully froze my game. Can't say 100% for the others.
![211977153-62812fb2-5321-4927-b280-2401e7e0782a](https://user-images.githubusercontent.com/53982700/216975699-6a4b68da-6def-4b84-8c14-73c75fa29477.png)

### Steps to Reproduce

Type in the spot where you type for an oredict filter. Continue typing. If it goes out of the window something is already wrong, but even further typing a ! will make things more wrong with a game freeze.

**Comment by IntegerLimit** [comment]
Logs and more information here: https://github.com/tracer4b/nomi-ceu/issues/198

**Comment by LAGIdiot** [comment]
Confirmed on latest master 1fae38416de4b76fe0c3bd1c72d1463e1abc03b9 . Unfortunately there is nothing useful in logs
