### ISSUE TITLE
I need a 64x wire

### ISSUE THREAD

**Issue by 3453890470** [GregTechCEu/GregTech#1489]
### GregTech CEu Version

v2.5.0

### Related Problem

There are times when 16x leads are not enough, I remember there were 64x leads at GTCE, maybe.
This is not my native language and I am using a machine translation. 
Perhaps it will be a little difficult to understand?

### Your Solution

Add 64x wires

**Comment by 3453890470** [comment]
This is my first time playing GT series.
Before that I just watched the video.

**Comment by tracer4b** [comment]
You can use 16x cables from better materials in order to run more machines on the same cable.
Check under “Amperage” on cables

**Comment by 3453890470** [comment]
Well I know you are not prepared for this, bother you
