### ISSUE TITLE
different charges in armour pieces causes conflicts in energy level hud element

### ISSUE THREAD

**Issue by CosmicNovaStar** [GregTechCEu/GregTech#1494]
### GregTech CEu Version

2.5.2

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

a single or multiple percentages that indicate the charge level of suit pieces

### Actual Behavior

hud elements overlay each other which cases a mess as in the picture included
![Screenshot from 2023-02-11 11-15-34](https://user-images.githubusercontent.com/68189992/218263239-25c502e8-8587-4137-b3f6-0799404de190.png)

### Steps to Reproduce

1) get any armour piece that holds charge
2) charge it and equip it
3) do the same as in step 2 but with a different piece and charge level

**Comment by TechLord22** [comment]
This should be fixed as of #1564. If this still persists on a version including that PR, please let us know.
