### ISSUE TITLE
BUG 2.5.2-Stack number form items disapearing when held by player with an open GT GUI

### ISSUE THREAD

**Issue by firendlyGhost** [GregTechCEu/GregTech#1500]
### GregTech CEu Version

2.5.2

### Modpack Used

GT Comunity pack

### Environment

Single player and Server 

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

When you hold an item, for example trying to manually insert ingots in a plate bender, normally you can see what amount of items you are inserting (grabbing with mouse), but the moment you click on the item the numbers disapear making it seem you are holding a stack of 1

### Actual Behavior

When with a GT GUI open
the moment you click on the item the numbers disapear making it seem you are holding a stack of 1

### Steps to Reproduce

Example, making plates:
1- Have 64 ingots in your inventory
2- Open the bending machin GUI ( so far so good)
3- Left/right click the ingots in your inventory- They now appear just the item icon the, number of the stack disappears
4- place it inside the machine and the items says 64 once again.

Note: this Happens on Every single GUI i've tested, like super tanks, crates etc.

### Additional Information

BONSU BUG: updating the Gt version jave file (just that file) somehow breaks the greenhouse recipe/ disables the greenhouse block ON SERVER ONLY on the GT community pack, the item is available on SP just fine.

Screenshots to prove point:
![2023-02-12_19 32 42](https://user-images.githubusercontent.com/53128966/218333111-64ad9c98-c0b5-4cd3-9ae5-81172947b482.png)

**Comment by firendlyGhost** [comment]
![2023-02-12_19 32 46](https://user-images.githubusercontent.com/53128966/218333138-edc41392-c66f-4195-961f-6ed930d28553.png)

**Comment by firendlyGhost** [comment]
![2023-02-12_19 36 10](https://user-images.githubusercontent.com/53128966/218333155-4be00c11-0dd6-4786-aa8a-0e0a25ad0e81.png)

Chest is vanilla: Working as Intended

**Comment by kaspertfg** [comment]
This was caused in commit 81ccb5b when this line "this.drawItemStack(itemStack, mouseX - guiLeft - 8, mouseY - guiTop - dragOffset, "");" was changed in src/main/java/gregtech/api/gui/impl/ModularUIGui.java.  Reverting this change solves the issue.
