### ISSUE TITLE
Crash when adding cover to machine on an unvalkyried heavens ship

### ISSUE THREAD

**Issue by Homssu** [GregTechCEu/GregTech#1505]
### GregTech CEu Version

2.5.0-beta

### Environment

Singleplayer

### Side Crashed

Client

### New Worlds

Yes

### Steps to Reproduce

1. Build a platform in the air
2. Add a physics infuser
3. Place down an LV macerator
4. Assemble the ship
5. Try to add a cover to the LV macerator
6. Crash

### Crash Report

https://pastebin.com/ZyZiV2Em
https://pastebin.com/P53P7frb

### Additional Information

Unvalkyried Heavens version 1.0.9

**Comment by LordDarthDan** [comment]
Why would it return null?
Valkyrien simply transforms the raycast vector from world pos to ship pos:

https://github.com/LordDarthDan/Unvalkyried-Heavens/blob/master/src/main/java/org/valkyrienskies/mixin/client/MixinMinecraft.java

It only transforms the target position though, so in reality you get a very long vector from player at -100 -600 to ship at 5120000 0...

**Comment by TechLord22** [comment]
This should be fixed as of #1507.
