### ISSUE TITLE
[BUG] Shutter + Control cover on pipe ignores redstone. Doesnt work ignores signal

### ISSUE THREAD

**Issue by firendlyGhost** [GregTechCEu/GregTech#1525]
### GregTech CEu Version

2.5.0

### Modpack Used

GT comunity pack 1.5.0 (latest)

### Addons Installed

gregicality mb (not the cause)

### Environment

SP, MP, new worlds too

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

When using a shutter + controller on a a pipe i expect it to close/open the pipe based on redstone signal. It ignores it completly.

### Actual Behavior

Its ALWASY either On or Off based on if i click with the mouse on the controller GUI to work normal or inverted.

On the contrary this combination of covers works just fine on a super tank with the same config as intended 

### Steps to Reproduce

1- place pipe
2- place shutter
3- place control cover
4- try to give it resdtone signal to start or stop, for example, lever, or ME level emitter.
5- It ignore it
.
.
.

6- Try the same setup, but put the cover on the GT supertank, works like a charm, as intended

**Comment by trittimo** [comment]
Yeah I'm experiencing this issue as well.

**Comment by trittimo** [comment]
The problem appears to be in the way the neighborChanged method in BlockPipe is handling the gt6StylePipesCables configuration option. If that value is true (which it is by default), it will not run any of the neighborChanged functionality, which seems incorrect to me.

Link to problematic line: https://github.com/GregTechCEu/GregTech/blob/d4e5bf5bb344081a8d4a1e927327c7549f7e46cf/src/main/java/gregtech/api/pipenet/block/BlockPipe.java#L192
