### ISSUE TITLE
GT.Behaviours NBT tag breaks circuits

### ISSUE THREAD

**Issue by TheAirBlow** [GregTechCEu/GregTech#1535]
## Main information
**Addons Installed**: Gregicality Multiblocks 1.1.6, Multiblock Tweaker 1.8.2 \
**Actual Behavior**: The gas collector decided to do a little trolling \
**Modpack Used**: Nomifactory (GTCEu Port) \
**Expected Behavior**: For it to work??? \
**GregTech CEu Version**: 2.5.0-beta \
**Cross-Mod Interaction**: Unsure \
**Environment**: Multiplayer \
**New Worlds**: Unsure

### Steps to Reproduce
1) Destroy a machine and put it in some other dimension (for me it was space which has no air)
2) Try to use it in Lost Cities or Overworld with the correct circuit and it doesn't work

### Additional Information
![image](https://user-images.githubusercontent.com/68467762/221286098-55542699-a0d9-409f-8ad0-c54998621bfd.png)
![image](https://user-images.githubusercontent.com/68467762/221286078-841d6836-2114-4e00-9038-1c41df88ba6b.png)

The MV gas collector I had lying around worked without problems, I just had to replace the power converter. It was never moved out of The Lost Cities before.

Additionally, as this modpack has Actually Additions installed and I have advanced tooltips enabled, I decided to check NBT and metadata - NBT was completely empty and metadata matched to the HV gas collector in JEI.

Also, this is indeed The Lost Cities which according to JEI requires circuit 4, but in this case it is not a dimension but overworld's generator.

**Comment by TheAirBlow** [comment]
Turns out, the issue is that the circuit I used had `GT.Behaviours:{}`, which somehow fucked everything up.
Putting a newly-made circuit without that NBT tag worked.

**Comment by Folanlron** [comment]
Update, has been fixed for awhile..

https://github.com/GregTechCEu/GregTech/pull/1444

**Comment by TheAirBlow** [comment]
> Update, has been fixed for awhile..
> 
> #1444

Bruh
