### ISSUE TITLE
Multiple recipes are not available

### ISSUE THREAD

**Issue by YiRanMushroom** [GregTechCEu/GregTech#1569]
### GregTech CEu Version

v2.5.3-beta

### Modpack Used

Nomifactory-gtceu port

### Addons Installed

Gregicality Multiblocks 1.2.0

### Environment

Singleplayer

### New Worlds

No

### Cross-Mod Interaction

Unsure

### Expected Behavior

Import all ingredients to the assembly line and wait for the product.

### Actual Behavior

The craft can not begin while others (such as Conveyor Module (LuV),Emitter (LuV)) can be craft normally.

### Steps to Reproduce

Use ae2 to import ingredients.

### Additional Information

Wrong Zenscript of the modpack author.

**Comment by YiRanMushroom** [comment]
Same problems occurs with Multi-layer Fiber-Reinforced Circuit Board.

**Comment by YiRanMushroom** [comment]
And this is not a crafttweaker problem.

**Comment by YiRanMushroom** [comment]
It is a new bug after v2.5.3

**Comment by PrototypeTrousers** [comment]
where are the logs ? Minecraft and craftweaker ?

**Comment by YiRanMushroom** [comment]
There are no crash reports, and no errors could be seen in logs, and jei loaded the recipes correctly. I am not at home now, I will give the logs so you can see if the recipes are loaded when starting.

**Comment by PrototypeTrousers** [comment]
#1574 should fix this.

**Comment by YiRanMushroom** [comment]
I can't understand what you means and changes but I think you get it right.
