### ISSUE TITLE
Electroplating: Rhodium Plated Lumium-Palladium

### ISSUE THREAD

**Issue by supasem** [GregTechCEu/GregTech#1578]
### GregTech CEu Version

v2.5.2

### Related Problem

I am currently playing the latest version of nomifactory CEu edition and was looking at the processing line for rhodium plated lumium-palladium. The one thing I noticed off the bat was that there was no plating process for the ingot, and that it was a mere alloying process. I am not entirely sure if this process exists in other versions of GTCEu, as I am aware that NF is a modpack and has been tweaked to an extent.

### Your Solution

I propose that a new electrolyzer recipe is made for rhodium plating. Create lumium-palladium, and then electroplate using a rhodium solution (Possibly rhodium sulfate, Rh2(SO4)3). By simply putting an ingot of lumium-palladium into the electrolyzer with an amount of rhodium plating solution, the ingot will be electroplated, producing an ingot of rhodium plated lumium-palladium.

### Additional Information

Now, I realize that having a recipe like this in the electrolyzer may prevent a process where the rhodium solution could be separated via electrolysis, and for that reason, a chem reactor could be used instead. Maybe a not-consumed electrode of some sort could be used in this case to signify electroplating occurring.

**Comment by firendlyGhost** [comment]
I support this suggestion. Maybe make it a different liquid tho. 

I think the devs should look into this post

**Comment by IntegerLimit** [comment]
This is better suited to the Nomi issue page https://github.com/tracer4b/nomi-ceu/issues, so please move it there. However, I do feel like this is a good suggestion for HM.

**Comment by firendlyGhost** [comment]
i think it would be a cool idea for rhodium plated palladium, that applies to base GTCEU
