### ISSUE TITLE
Incompatible with ULV cover

### ISSUE THREAD

**Issue by FallDark** [GregTechCEu/GregTech#1585]
### GregTech CEu Version

2.5.4

### Addons Installed

Gregicality Multiblocks  1.2.0
ULV cover 2.5.0

### Environment

Singleplayer

### Side Crashed

Client

### New Worlds

Yes

### Steps to Reproduce

update gtceu to 2.5.4

### Crash Report

[crash-2023-03-09_21.16.27-client.txt](https://github.com/GregTechCEu/GregTech/files/10932382/crash-2023-03-09_21.16.27-client.txt)

**Comment by IntegerLimit** [comment]
Better suited at the ULV covers GitHub.

**Comment by IntegerLimit** [comment]
It's probably because of the storage cover PR.
