### ISSUE TITLE
Liquid-Fueled Impeller Jetpack does not function with any other combustion fuel if you have used a Jetpack with a differing fuel type during a session

### ISSUE THREAD

**Issue by tyreforhyred** [GregTechCEu/GregTech#1589]
### GregTech CEu Version

2.5.4

### Modpack Used

Gregtech Community Pack 1.6.2

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

That Jetpacks work with any combustion fuel type.

### Actual Behavior

The first fuel type that is used will be the only one that works correctly for the duration of the session. This persists over a world restart and the entire client must instead be restarted.

### Steps to Reproduce

Pick any combustion fuel type and fill a jetpack with it, use it. Now attempt to use a jetpack with a different fuel type and see that it fails.

**Comment by ALongStringOfNumbers** [comment]
From some debugging, it seems like the armor tick calls are not being made for the second set of armor
