### ISSUE TITLE
Make naquadah/ naquadria waste  distillation consistent

### ISSUE THREAD

**Issue by firendlyGhost** [GregTechCEu/GregTech#1592]
### GregTech CEu Version

2.5.3

### Related Problem

When distilling enriched Nq waste the distillation products are from the bottom: 1-sulfuric acid 2-enriched Nq solution 3- Naquadria solution.

When distilling Naquadria waste we get 1-sulfuric acid 2-Naquadria solution 3- Enriched Nq solution.

Wich makes it impossible to put ME p2p on a distillation tower that is setup to do both because it gets clogged up.

Also the distillation products have the same density so they should appear in the same collums.

### Your Solution

Its an easy fix just change one of the recipes

### Additional Information

![2023-03-11_09 27 49](https://user-images.githubusercontent.com/53128966/224476685-3625e641-0cb1-42a5-bcf5-7428ec102a9c.png)

**Comment by DStrand1** [comment]
This is on purpose, you're intended to have 2 DT's for this step

**Comment by firendlyGhost** [comment]
well too bad nothing stops players from having just one distillation tower, this literally only stops the usage of p2p without filters and such. Also Ae2 fluid interfaces and fluid storage buses are a thing so this "need to have 2 DT" is very easily bypassed. This only limits p2p which are a more lag friendly option to the interfaces and storage buses. 

But whatever, have it your way, it literally makes no sense that the distillation products go to different collumns just to "force the use of 2 DT"
