### ISSUE TITLE
Regulators have no Arc Furnace/Pulverizer recipes

### ISSUE THREAD

**Issue by crawln45** [GregTechCEu/GregTech#1602]
### GregTech CEu Version

2.5.4-beta

### Modpack Used

Nomifactory CU Version 1.5.2

### Environment

Single Player

### New Worlds

Yes

### Cross-Mod Interaction

Yes

### Expected Behavior

Have a recipe for arc furnace or Pulverizer that match the Pumps.

### Actual Behavior

Says there are no uses for regulators

### Steps to Reproduce

make a regulator, right click in JEI to see uses.  I also tried to just put it in the arc furnace.

**Comment by ALongStringOfNumbers** [comment]
Confirmed as of 09e3d19

This happens because the other components get their material information registered in their crafting recipes, but the fluid regulators do not have crafting recipes.
