### ISSUE TITLE
If the cable is placed before the converter is placed, power will not flow to the converter.

### ISSUE THREAD

**Issue by tier940** [GregTechCEu/GregTech#1614]
### GregTech CEu Version

2.5.4

### Modpack Used

GregTech Expert 2

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

The cable has to be broken and reconnected to transmit power.

### Actual Behavior

https://user-images.githubusercontent.com/11691836/225642009-7e2d0a32-e35c-4f2c-9be3-bfd9bf38a037.mp4

### Steps to Reproduce

1. `B:enableFEConverters=false` -> true
2. `B:nativeEUToFE=true` -> false
3. Then check out the video.

**Comment by ALongStringOfNumbers** [comment]
Confirmed
