### ISSUE TITLE
Expand Smart Filter machines

### ISSUE THREAD

**Issue by Kremnari** [GregTechCEu/GregTech#1655]
### GregTech CEu Version

v2.5.2

### Related Problem

The Smart Filter Cover only recognizes centrifuge, electrolyzer and sifter recipes.   It would be awesome if it could filter for other machines as well.  At least the Electromagnetic Separator and Chemical Bath, as these have occasional use in ore processing.

### Your Solution

It looks like they could be added @src/main/java/gregtech/common/covers/filter/ SmartItemFilter.java : 118
just add code links to the relevant RecipeMaps.

### Additional Information

I'd fork, build, and PR it myself, but I'm fighting with gradle... ( I haven't touched modding since 1.6 and 2011)

**Comment by ALongStringOfNumbers** [comment]
The smart item filter was designed to cover the case in ore processing where the input amount changes a lot between recipes, as seen with the varying dust sizes in the electrolyzer recipes.

The Electromagnetic Separator and Chemical Bath always have an input of 1 dust, so having the smart filter cover these cases does not really make sense. An alternative here would be using a robot arm, or conveyor, with an oredict filter, so you could filter out the dusts that you wanted to send to these machines when processing, based on their oredictionary name.
