### ISSUE TITLE
ULV Hulls take Red Alloy cables in Assembler instead of Lead cables they take normally

### ISSUE THREAD

**Issue by mateskr692** [GregTechCEu/GregTech#1674]
### GregTech CEu Version

2.5.4

### Modpack Used

Nomifactory CEu

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Every machine Hull can be made either in a crafting table recipe or in Assembler recipe, in both cases they take the same cable. Except for the ULV Hull which takes Lead cables in normal recipe but red alloy cables in Assembler recipe

### Actual Behavior

ULV Hulls take Red Alloy cables in Assembler instead of Lead cables they take normally

Crafting table recipe:
![image](https://user-images.githubusercontent.com/32541962/230329639-206b117a-6e2a-4bf6-8020-0b4179e90b9c.png)

Assembler recipe:
![image](https://user-images.githubusercontent.com/32541962/230329733-275e9eb9-c32b-4e88-8582-83c1ef671b1c.png)

### Steps to Reproduce

Just check the recipe in JEI. Tried to craft with lead cables in assembler just to be sure and didn't accept it

### Additional Information

posted as issue in Nomifactory repo and was told it's the issue with GTCEu and not the pack tweaking recipes
https://github.com/Nomi-CEu/nomi-ceu/issues/308

**Comment by ALongStringOfNumbers** [comment]
This is a Nomi-CEu issue. They are changing the recipe to take lead cables here:
https://github.com/Nomi-CEu/nomi-ceu/blob/main/overrides/scripts/electronics.zs#L198-L202

**Comment by IntegerLimit** [comment]
Oops, I missed that, and redirected it here, sorry. I'll fix it later today.
