### ISSUE TITLE
Items inside Crafting Station can be moved while scrolling through the inventory tab

### ISSUE THREAD

**Issue by mateskr692** [GregTechCEu/GregTech#1675]
### GregTech CEu Version

2.5.4

### Modpack Used

Nomifactory CEu

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

When switching to the inventory tab you shouldn't be able to accidentally pull out items/tools from crafting station while scrolling

### Actual Behavior

While scrolling through the inventory tab it is possible to extract items and tools out of the crafting station. It is because the scroll is conveniently used as 'take 1 / deposit 1' shortcut. This leads me to believe that the inventory tab renders on top of the the previous tab, having them overlap and making it possible to interact with the items you're not even seeing.

This also works with other tabs than just the storage. Checking a recipe in JEI still lets you interact with the Crafting Station, causing you to accidentally extract items, or select a recipe from saved recipes when trying to use the "+" button (move items).

### Steps to Reproduce

1. Place a crafting station and put some items/ tools inside
![image](https://user-images.githubusercontent.com/32541962/230332506-6e997df9-835f-41b0-a717-01096e64634c.png)
2. (optional) Place a chest next to the crafting station and fill it with items
3. switch to the Storage tab in crafting table and hover over a spot that overlaps with an item in the Crafting tab. For example 1st item in 3rd row is in the same place that the 1st tool slot in the crafting tab
![image](https://user-images.githubusercontent.com/32541962/230333723-ca6069dd-5d90-4fb9-aea0-1493b4f22857.png)
4. Use scroll down. This causes the tab to scroll down to show other items (as expected) but also takes out the item from the Crafting slot (not intended). In this example notice that after scrolling a screwdriver is now in my inventory and after switching to the Crafting tab the tool in first slot is indeed empty
![image](https://user-images.githubusercontent.com/32541962/230334061-373003ac-39e6-4637-881a-8b3b91024d05.png)
![image](https://user-images.githubusercontent.com/32541962/230334285-2af6656e-0481-4833-95ef-bad2c42f027b.png)

Similarly its possible to extract items while in JEI tab:
1. Hover over some item
![image](https://user-images.githubusercontent.com/32541962/230335356-ce83b086-8106-4845-971b-dd682db6fba3.png)
2. Press R to open JEI recipe tab (dont move your mouse)
![image](https://user-images.githubusercontent.com/32541962/230335522-f56292c9-5e99-45e5-b849-97e18e8667da.png)
3. Scroll down a little and come back to the crafting station, the items that you were hovering on got extracted
![image](https://user-images.githubusercontent.com/32541962/230335827-8c18a3ff-70d4-4415-9d9f-28d78287e2e6.png)

For the conflict with JEI crafting recipe:
1. Craft some items so they are in the history to the right and clear the crafting grid
![image](https://user-images.githubusercontent.com/32541962/230336466-a7cb845c-904d-42c5-bbcd-a8a9d4e42ced.png)
2. Open JEI and Press the "+"button to move the items. In my case the button to move items for iron block is in the same spot as 6th saved recipe so after clicking it instead of moving items to make iron block it clicked the recipe in history to craft iron rod
![image](https://user-images.githubusercontent.com/32541962/230336648-294c0253-d304-45c2-85c2-ccf782911d5d.png)
![image](https://user-images.githubusercontent.com/32541962/230336822-b34c7f87-73a9-462e-8a4f-db72e2d4444e.png)

**Comment by zhwith** [comment]
This is a known issue with Mouse Tweaks, setting the scroll handling config to 0/non-smooth fixes it.

**Comment by mateskr692** [comment]
I made a fresh install with just the GTCEu and this problem doesn't occur anymore, so you're right it's a Mouse Tweaks issue
