### ISSUE TITLE
Wood process not support oredict logWood

### ISSUE THREAD

**Issue by KELETU66666** [GregTechCEu/GregTech#1680]
### GregTech CEu Version

v2.6.0

### Addons Installed

gcym, gtfo, and this https://github.com/KELETU66666/GTNewHorizons3.0-Core-Mod

### Environment

SinglePlayer

### New Worlds

No

### Cross-Mod Interaction

No

### Expected Behavior

![image](https://user-images.githubusercontent.com/92129388/230706845-44fcbbd4-923a-437e-8dae-8b45ac6eb553.png)

### Actual Behavior

the mod log should compat with ceu in workbench.

### Steps to Reproduce

simply craft it.

### Additional Information

pls fix it

**Comment by Tictim** [comment]
It's working as expected; we dropped support for wood recipe nerfs outside vanilla woods and GT woods.

Wood recipes added by external mods are supposed to be manually adjusted. You may be able to utilize [`WoodRecipeLoader#registerWoodUnificationInfo`](https://github.com/GregTechCEu/GregTech/blob/55e00c245d8638ad567b6f857d655227eaf2df9a/src/main/java/gregtech/loaders/recipe/WoodRecipeLoader.java) for modifying wood recipes.
