### ISSUE TITLE
Is it possible to disable the generation of Oil Fountains? 

### ISSUE THREAD

**Issue by Soulerest** [GregTechCEu/GregTech#1681]
### Your Question

I want to create a modpack but to do that I need to disable the generation of Oil Fountains in other dimensions, is it possible to do so and how?

**Comment by ALongStringOfNumbers** [comment]
To stop the generation of the oil springs in certain dimensions you can take the following steps:
Go to the `raw_oil_sphere.json` in the `worldgen/vein/overworld` folder in the gregtech config folder
Add a `dimension_filter` entry and specify the dimension that you want the fluid springs to spawn in using one of the structures here: <https://github.com/GregTechCE/GregTech/wiki/Worldgen-JSON-Syntax#dimension-filter>

eg: 
```less
  "dimension_filter": [
    "name:the_end"
  ],
```

**Comment by ALongStringOfNumbers** [comment]
Closing this, as the question was answered
