### ISSUE TITLE
Add some Applied Energistics integrations

### ISSUE THREAD

**Issue by YiRanMushroom** [GregTechCEu/GregTech#1684]
### GregTech CEu Version

v2.5.4

### Related Problem

Sometimes with current mutiblock components, it's hard to design a good automation/logistic system to haddle complex crafts, and by adding blocks like stocker buses(which exists in GTNH) could reduce lags and simplify steps to design an automation/logistic system.

### Your Solution

Add those features or change some files to make it compatible with Gregtech Energistics (https://github.com/solidDoWant/GregTech-Energistics)

### Additional Information

Same features has already been achieved in GTNH, and there is also a mod contains some features like this in 1.12.2.
modname:[GregTech-Energistics](https://github.com/solidDoWant/GregTech-Energistics)
But it is only available in GTCE, because some relative classes has been changed in GTCEu.

**Comment by serenibyss** [comment]
Going to call this addressed by #1720, with likely more over time
