### ISSUE TITLE
Crafting Station History Recipe Input from JEI Recipe Input

### ISSUE THREAD

**Issue by deigil** [GregTechCEu/GregTech#1686]
### GregTech CEu Version

v2.5.4-beta

### Modpack Used

GTCEu Pack v1.6.2

### Addons Installed

Nothing extra added that would cause this functionality.

### Environment

Forge Docker Server

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Clicking the plus to add a JEI recipe to crafting station grid inputs that recipe.

### Actual Behavior

Clicking the plus to add a JEI recipe to crafting station grid inputs history recipe saved inside crafting station which is directly behind the JEI recipe viewer.

### Steps to Reproduce

Have some recipes saved in the crafting station. Click to view recipes of an item (for example GT axes). Clicking to add that recipe to the grid via the plus button which stands directly behind a saved recipe puts that saved recipe in instead of the desired craft.

**Comment by mateskr692** [comment]
I had the same issue caused a few days ago and it turned out to be because of Mouse Tweaks mod.
See #1675

**Comment by deigil** [comment]
> 

ahhh how exactly did you fix it it? You state it was caused by Mouse Tweaks but don't indicate how!

**Comment by mateskr692** [comment]
Did you open the issue I mentioned? There is the solution in the comments:
> This is a known issue with Mouse Tweaks, setting the scroll handling config to 0/non-smooth fixes it.

Some issues might still occur even with that, but completely disabling the Mouse Tweaks mod proves it's not GTCEu issue, in which case you should report that to the MouseTweak devs.
