### ISSUE TITLE
Machine Textures do not change when running and Audio for machines does not play

### ISSUE THREAD

**Issue by Watermel00n** [GregTechCEu/GregTech#1692]
### GregTech CEu Version

v2.6.0

### Environment

Singleplayer, Forge Server

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

When machine is running, I expected to see the texture change to the running texture and play the audio for the machine

### Actual Behavior

The texture stayed the same, regardless of the resource pack used, default or not.

### Steps to Reproduce

1. Place a wiremill and input power into it.
2. Put the programmed circuit 1 into it.
3. place copper ingots in the wiremill input slot

### Additional Information

1. This problem occurred on both curseforge and ATLauncher
2. This problem only applies to singleblock machines

**Comment by Watermel00n** [comment]
![2023-04-09_20 39 36](https://user-images.githubusercontent.com/95552493/230773681-3af1e397-591b-44ce-9698-e58859853937.png)
![2023-04-09_20 39 33](https://user-images.githubusercontent.com/95552493/230773686-540ecaff-2f49-44f9-911d-8d798acadb0d.png)

**Comment by Irgendwer01** [comment]
@Watermel00n can you give a list of all mods installed together with GTCEu?

**Comment by Watermel00n** [comment]
no mods were used

**Comment by TechLord22** [comment]
This issue will be fixed with #1690.
