### ISSUE TITLE
Localization related problems

### ISSUE THREAD

**Issue by ChromaPIE** [GregTechCEu/GregTech#1696]
### GregTech CEu Version

v2.6.1

### Related Problem

1. Text in the red box shown in the screenshot given below cant be localized

![image](https://user-images.githubusercontent.com/56111366/231179037-1a1ae06e-3676-42b3-8d8e-924e69756b52.png)

2. Localization keys for Canners' tooltips remained the old way, cause each to be shown as `gregtech.machine.canner.tooltip`.

### Your Solution

Just, you know, fix them, I guess

**Comment by TechLord22** [comment]
I cannot reproduce the second issue mentioned. That tooltip is added only if the following lang key is present in the currently loaded localization: `gregtech.machine.canner.tooltip`, and this key is not present in any lang files as of 20a8b4d578ce527320e1e084f0173542ebe7090e.
