### ISSUE TITLE
Processing arrays (and advanced) don't work with clean/sterile recipes

### ISSUE THREAD

**Issue by MorphRed** [GregTechCEu/GregTech#1697]
### GregTech CEu Version

v2.6.1

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Processing array and its advanced counterpart do their cleanroom and sterileroom recipes.

### Actual Behavior

Processing array and its advanced counterpart (while not shown but tested) aren't able to do any clean/sterile room recipes
https://user-images.githubusercontent.com/111656218/231227012-a8c132c7-c771-4818-b2be-fd9453b64fc1.mp4
https://user-images.githubusercontent.com/111656218/231227032-ef29f503-cf06-4915-88d4-993fb2790c49.mp4

### Steps to Reproduce

Do a recipe which needs a clean/sterile room requirement in the processing array

### Additional Information

Issue present since 2.6.0, I had someone else confirm to me that it still worked in 2.5.4

**Comment by IntegerLimit** [comment]
Confirmed.
