### ISSUE TITLE
Packagers cannot run certain recipes

### ISSUE THREAD

**Issue by YiRanMushroom** [GregTechCEu/GregTech#1704]
### GregTech CEu Version

v2.6.1

### Modpack Used

Nomifactory-gtceu port

### Environment

Singleplayer

### New Worlds

Unsure

### Cross-Mod Interaction

Unsure

### Expected Behavior

Using packager to do nuclearcraft recipes, want to produce ingots by package nuggets(i.e. americium nuggets -> americium ingot)

### Actual Behavior

The packager couldn't work with it(and couldn't work in PAs either), although recipes using gregtech ingredients can work normally.

### Steps to Reproduce

Try nuclearcraft recipes.

### Additional Information

May because of changing wire-related recipes or ghost circuits changes.
All can work correctly in v2.5.4.
Not sure weather other machines have similar problems when dealing with recipes relating other mods.

**Comment by IntegerLimit** [comment]
This is a NFu problem, and I have fixed it with https://github.com/Nomi-CEu/nomi-ceu/commit/6ed7e2528a1f662fde084a457690165f77602f97.
