### ISSUE TITLE
Rubber and Treated stairs and slab not work as Transparent blocks

### ISSUE THREAD

**Issue by marisathewitch** [GregTechCEu/GregTech#1721]
### GregTech CEu Version

v2.6.1-beta

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

Unsure

### Expected Behavior

Placing Rubber or Treated stairs or slab on top of chest allow open chest.

### Actual Behavior

Placing Rubber or Treated stairs or slab on top of chest not allow open chest, like stair or slab is full solid (non-transparent) block.

### Steps to Reproduce

1) Place minecraft chest
2) Place stair (any angle and form) or Slab (lower position)
3) Try open chest

### Additional Information

Regular minecraft block such as Oak stairs or slab allow open chest, because they transparent block.

**Comment by IntegerLimit** [comment]
This also happens with Treated and Rubber wood slabs.

**Comment by IntegerLimit** [comment]
Interestingly, this happens for both AE2 and GT Slabs and Stairs, but not Actually Additions's.
