### ISSUE TITLE
Quantum Chest V TOP display glitches when it is full

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/GregTech#1747]
### GregTech CEu Version

v2.6.1

### Modpack Used

GregTech Community Modpack v1.6.3

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

Yes

### Expected Behavior

TOP says Filled Quantum Chest (2,147,483,647 + 64 in the output slot = 2,147,483,671) has 2G items
![キャプチャ1975](https://user-images.githubusercontent.com/39122497/236430684-3898b228-4361-45b8-b5ed-b1a308836d61.PNG)

### Actual Behavior

Air
![キャプチャ1976](https://user-images.githubusercontent.com/39122497/236430980-595c29c8-9e2c-449a-a136-31dfd00d4b73.PNG)

### Steps to Reproduce

fill a quantum chest V

### Additional Information

I guess TOP cannot handle items more than integer max value

**Comment by DStrand1** [comment]
Unfortunately as you said here:
> I guess TOP cannot handle items more than integer max value
this is true, so there is nothing we can reasonably do about this.
