### ISSUE TITLE
large steam turbine keeps running when the rotor is broken

### ISSUE THREAD

**Issue by tesiar** [GregTechCEu/GregTech#1761]
### GregTech CEu Version

v2.6.1-beta

### Environment

singleplayer

### New Worlds

Unsure

### Cross-Mod Interaction

Unsure

### Expected Behavior

turbine stop when the rotor breaks

### Actual Behavior

after a rotor breaks, the turbine continues to operate, generating from 0 to 200 EU/s. this only works with HV/EV holders, with other types of holders the turbine works correctly
![turbine_interface](https://user-images.githubusercontent.com/44028350/236721462-a213aa0d-2d63-409c-b8a4-d8e326477d86.png)
![eu_ouput](https://user-images.githubusercontent.com/44028350/236721818-25fef92c-6df8-41d3-9064-8434d1304d02.png)

### Steps to Reproduce

1) Built turbine with HV holder, automatic maintenance hatch, UHV fluid access hatch, EV energy connector
2) Failed steam source, with sufficient capacity for continuous operation
3) Inserted aluminum rotor with durability 10/18400
4) Waited for the rotor to break (the turbine continues to work)
5) After a few minutes, I saw on the digital interface the energy output (gradually increasing from 0 to 200, in steps of 20), also if you connect the energy storage, it will be charged

### Additional Information

Sorry for the bad english, I used a translator
I tested all holders, but only HV/EV work incorrectly. 
I also tried this with a gas turbine, but even though it stops after the rotor breaks, it will not start working if a new one is inserted. You can fix this if you replace any turbine block. Similar problem with steam turbine with holders above EV.
In a steam turbine with HV / EV holders, after the appearance of the described bug, even if you replace any block other than the turbine block, it will continue to work.
If you empty the access hatch with steam, the turbine will stop (I mean when it works without a rotor), and start again if steam is applied. Steam is not consumed in "rotorless" mode.
If you re-enter the world, the bug also goes away.
When using an activity detector, it gives a redstone signal.
When trying to restart the turbine using a mallet or the machine controller, the bug does not go away.

**Comment by sjcl** [comment]
FYI, This issue can be reproduced not only with the Large Steam Turbine
![image](https://github.com/GregTechCEu/GregTech/assets/16951483/c0299634-ea60-48f9-af89-510f7dae64e9)
