### ISSUE TITLE
Crafting table can dupe anything

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/GregTech#1775]
### GregTech CEu Version

v2.6.2

### Modpack Used

GregTech Community Modpack v1.6.3 (updated GTCEu manually)

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

Yes

### Expected Behavior

Crafting recipe with tools does not make items dupe

### Actual Behavior

It makes any item dupe (I tried with many recipes)

### Steps to Reproduce

You need at least 64 of the same items which has crafting recipe with tools to do glitch

https://github.com/GregTechCEu/GregTech/assets/39122497/c5b71691-562a-4981-8e9b-7d1cca7eb2a2

### Additional Information

Apparently tools PR has issue

**Comment by TechLord22** [comment]
Upon investigation this seems to be a bug present in JEI itself. I have made a Pull Request to fix it here: https://github.com/mezz/JustEnoughItems/pull/3218

**Comment by TechLord22** [comment]
This should be fixed now, as of JEI version `4.16.1.1003`, so I am closing this issue.
