### ISSUE TITLE
machine blocks don't render when dropped

### ISSUE THREAD

**Issue by oliwier509** [GregTechCEu/GregTech#1855]
### GregTech CEu Version

2.6.2-beta

### Modpack Used

supersymmetry pre-release 1ccbcb8

### Addons Installed

none

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

Unsure

### Expected Behavior

the machine block when dropped has a visible texture

### Actual Behavior

the machine block has no texture when dropped

### Steps to Reproduce

1. select a machine, pipe or drum block
2. drop it on the ground

### Additional Information

![2023-06-17_11 43 01](https://github.com/GregTechCEu/GregTech/assets/53867161/c188530f-f375-4789-97e5-2f66176e0690)
![image](https://github.com/GregTechCEu/GregTech/assets/53867161/b024b2b3-f72f-4643-bf0c-ed34c3c5e8fc)

_No response_

**Comment by oliwier509** [comment]
This was fixed in the modpack.

**Comment by al1-ce** [comment]
@oliwier509 please reopen issue as I have same problem and I don't really want to spam on that

Note: Latest version of supersymmetry
![2023-07-22_20 25 16](https://github.com/GregTechCEu/GregTech/assets/60989682/c8783eae-6f24-44fe-93cb-dd9facea7a09)

**Comment by htmlcsjs** [comment]
are you using optifine

**Comment by al1-ce** [comment]
No, no new mods were added at all
