### ISSUE TITLE
Maintenance Hatch crashes game when holding Item Filter

### ISSUE THREAD

**Issue by Beagle1904** [GregTechCEu/GregTech#1859]
### GregTech CEu Version

2.6.0

### Modpack Used

Nomifactory (GTCEu Port)

### Environment

Forge Server and Singleplayer

### Side Crashed

Client

### New Worlds

Yes

### Steps to Reproduce

1. Spawn into a new creative world
2. Give yourself a maintenance hatch and an item filter (have confirmed that this works with Ore Dictionary Filters specifically, unsure about other types)
3. Place the maintenance hatch
4. Switch to the item filter and hover over the maintenance hatch

### Crash Report

https://mclo.gs/hgH3IjT

### Additional Information

This causes the client to crash, however on a forge server the world continues to run, and the player logging back in immediately leads to the same crash happening

**Comment by serenibyss** [comment]
Does this issue still occur on GTCEu 2.6.2?

**Comment by serenibyss** [comment]
(or Nomifactory CEu 1.6.1-beta-3a)
