### ISSUE TITLE
 (3x3x1 mode) GT electric drill will break item/fluid pipes, causing these pipes to be destroyed.

### ISSUE THREAD

**Issue by trainvoi** [GregTechCEu/GregTech#1873]
### GregTech CEu Version

2.5.6

### Modpack Used

Supersymmetry, latest prerelease

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Electric drill should not break pipes at all.

### Actual Behavior

 (3x3x1 mode) GT electric drill will break item/fluid pipes, causing these pipes to be destroyed. These pipes will not be dropped when being broken by the electric drill

### Steps to Reproduce

a pipe in the outer edge of the 3x3x1 zone, a block that is breakable using pickaxe/shovel tool in the center of the 3x3x1 square. Use the drill to break the center block, the pipes on the edge willbe broken.

**Comment by ALongStringOfNumbers** [comment]
I cannot reproduce the pipes not being dropped by the drill.

Why would you say that the drill should not be able to break pipes though?
