### ISSUE TITLE
Electric Blast Furnace

### ISSUE THREAD

**Issue by threestarsQAQ** [GregTechCEu/GregTech#1896]
### GregTech CEu Version

v2.6.2-beta

### Modpack Used

Nomifactory (GTCEu Port) 1.6.1-beta-3a

### Environment

singleplayer

### New Worlds

Unsure

### Cross-Mod Interaction

No

### Expected Behavior

![image](https://github.com/GregTechCEu/GregTech/assets/106313729/29aae618-77b0-469a-92ba-a02ab0c60b6b)
![image](https://github.com/GregTechCEu/GregTech/assets/106313729/94a69981-54f6-41bb-9ac4-757c128ee6a8)
![image](https://github.com/GregTechCEu/GregTech/assets/106313729/41d75ef4-006c-45bf-b243-67fee9f8bed1)
![image](https://github.com/GregTechCEu/GregTech/assets/106313729/badeaf78-0253-4852-972a-3962859c94df)
![image](https://github.com/GregTechCEu/GregTech/assets/106313729/52bcd02a-82eb-41d2-8bd9-c0061871db17)
![image](https://github.com/GregTechCEu/GregTech/assets/106313729/227bc6d2-8db3-4615-95a0-7cca82694619)
![2023-07-02_15 53 56](https://github.com/GregTechCEu/GregTech/assets/106313729/0bd36cfe-e227-4549-94b0-e028338f49d6)
![2023-07-02_15 54 21](https://github.com/GregTechCEu/GregTech/assets/106313729/087d89eb-6a61-4136-8cb8-9db581d1e776)
But when I rebuilt it was fine again and failed again after a while

### Actual Behavior

Originally, I wanted to make aluminum ingots, but it broke after using it.Power is enough
![image](https://github.com/GregTechCEu/GregTech/assets/106313729/9fbd771f-f4b4-4f95-a338-e303d8e389b8)
![image](https://github.com/GregTechCEu/GregTech/assets/106313729/6d4c520c-2ea6-4f47-a916-71b30f68a0e3)
this is save
[新的Default World.zip](https://github.com/GregTechCEu/GregTech/files/11928963/Default.World.zip)

### Steps to Reproduce

I don't know , I rebuilt it but it is broken

**Comment by threestarsQAQ** [comment]
I re-entered the game and it was fine again

**Comment by threestarsQAQ** [comment]
I re-entered the game and it was fine again

**Comment by ghzdude** [comment]
If you built your blast furnace crossing a chunk border, then there's a possibilty that the structure unforms when the chunks are loaded or reloaded (like when you open a single-player world). Usually, chunk-loading the chunks fixes the issue, but it sometimes still unforms anyways.
