### ISSUE TITLE
Wooden Pipe has duplicated recipe

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/GregTech#1939]
### GregTech CEu Version

v2.7.1

### Modpack Used

GregTech Community Modpack v1.7.0

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Wooden Pipe and Treated Wooden Pipe can only be made with saw

### Actual Behavior

![キャプチャ2055](https://github.com/GregTechCEu/GregTech/assets/39122497/382f1bf9-61b2-4ab2-95ed-137159ae8aad)

they have different recipe id

### Steps to Reproduce

none

**Comment by serenibyss** [comment]
Fixed by #1942
