### ISSUE TITLE
Long Distance Pipe cannot do math

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/GregTech#1943]
### GregTech CEu Version

v2.7.1

### Modpack Used

GregTech Community Modpack v1.7.0

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

long distance pipe can do length calculation

### Actual Behavior

![キャプチャ2056](https://github.com/GregTechCEu/GregTech/assets/39122497/3eb3cbda-c3f8-48a7-beab-e67490882d9c)
![キャプチャ2057](https://github.com/GregTechCEu/GregTech/assets/39122497/d9ef5d14-4721-4034-bbe7-8311a04effa6)
![キャプチャ2058](https://github.com/GregTechCEu/GregTech/assets/39122497/e1dc26e8-7ce0-4962-b343-d832ede90e62)

### Steps to Reproduce

idk
try connect and break pipe networks multiple times

**Comment by brachy84** [comment]
How did you make it say length of two blocks? Does it work?
I can reproduce it saying a larger number than it actually is. However here its TOP falsly displaying "Connected" even tho its not.
The number it displays is always the number of connected pipe blocks. TOP says its connected but the pipe wont transfer anything.
