### ISSUE TITLE
Breaking JEI support in Chinese

### ISSUE THREAD

**Issue by ChenHaoYan1234** [GregTechCEu/GregTech#1950]
### GregTech CEu Version

2.7.1

### Environment

single player

### New Worlds

Yes

### Cross-Mod Interaction

Yes

### Expected Behavior

![image](https://github.com/GregTechCEu/GregTech/assets/79736203/bfe43a87-6e82-491f-b954-a4999e359ba6)
It should show normal duration time.

### Actual Behavior

![image](https://github.com/GregTechCEu/GregTech/assets/79736203/9ba4580b-e9b7-41f9-a7d4-c5d80662bb19)
It gives me a format error.

### Steps to Reproduce

Open any gtceu recipe in JEI in Chinese.

**Comment by MrKono** [comment]
I think this problem is caused by #1911.
This PR changed the Format duration of JEI, but only modified en_us.lang.
