### ISSUE TITLE
[Suggestion] An even brighter light

### ISSUE THREAD

**Issue by SpeeeDCraft** [GregTechCEu/GregTech#197]
**Is your feature request related to a problem? Please describe.**
GregTech has high-tech mechanisms, wires, and other items. But there are no lamps, or other lighting items.

**Describe the solution you'd like**
I would like to add lamps or other lighting units or items to GTCEu that will be powered by electricity. That is, they will illuminate the territory only when they have enough energy. You can also implement several modes of operation for them (or several tiers). With the help of which, the lighting units will consume much more energy, but illuminate the territory, for example, 20x20 or 30x30, in short, a large one :D.

**Comment by serenibyss** [comment]
There are lamps now as of #1635
