### ISSUE TITLE
Liquid-Fueled Jetpack no longer able to fly

### ISSUE THREAD

**Issue by tier940** [GregTechCEu/GregTech#1983]
### GregTech CEu Version

v2.7.2

### Environment

Singleplayer

### New Worlds

No

### Cross-Mod Interaction

No

### Expected Behavior

Taking a walk in the sky with Liquid-Fueled Jetpack

### Actual Behavior

As the title says

### Steps to Reproduce

Equipped with Liquid-Fueled Jetpack

**Comment by ALongStringOfNumbers** [comment]
Have you used it before in the session? Could this be a duplicate of #1589?
