### ISSUE TITLE
Processing Array Void Items in Some Cases

### ISSUE THREAD

**Issue by YiRanMushroom** [GregTechCEu/GregTech#1999]
### GregTech CEu Version

v2.7.2

### Modpack Used

GTCM v1.7.0

### Environment

Singleplayer

### New Worlds

Unsure

### Cross-Mod Interaction

Unsure

### Expected Behavior

Use AE to import 12 polytetraflouroethylene bars into a import bus with a plate shape in a processing array with pattern 4*Polytetraflouroethylene bar -> 4*Polytetraflouroethylene sheet, with many Co-Processing Unit installed. Expected to get 12 Polytetraflouroethylene sheets.

### Actual Behavior

Only 8 was produced.

### Steps to Reproduce

If use a pattern 1*Polytetraflouroethylene bar -> 1*Polytetraflouroethylene sheet its okay, and 4*Rubber bar -> 4*Rubber sheet is also okay(so as PVC). Only PTFE had this bug, and this cannot be fixed by restarting the game.
When crafting 100 PTFE sheets, I can only get 52.
The behaviour is very constant and consistent, it 100% occurs in such case and always get the same amount of items.

### Additional Information

Maybe caused by the fixing of ME stocking buses/hatches in parallel Recipes.

**Comment by PrototypeTrousers** [comment]
Pics of the setup, including chunk borders (F3 + g)

**Comment by YiRanMushroom** [comment]
I am not in front of by PC, so I cannot send this to you. But I am sure that the whole multiblock is in one chunk. I used ME interfaces towards a import bus with a plate shape in a processing array. Fortunately I can access the log. You want it?

**Comment by YiRanMushroom** [comment]
I can give the screenshot in 30 minutes.

**Comment by YiRanMushroom** [comment]
The one in the front-middle.
P.S. This problem happens even if a non-me output bus is used

**Comment by PrototypeTrousers** [comment]
could not reproduce in master dev.
what tier and how many extruders are in the PA and what tier and how many energy hatches?

**Comment by YiRanMushroom** [comment]
The bug seem to be gone because I cannot reproduce it anymore. I still cannot find the reason, maybe it was caused by other bugs.

**Comment by YiRanMushroom** [comment]
I may close the issue if nothing goes wrong later
