### ISSUE TITLE
CraftTweaker Cash Caused by Gregtech 

### ISSUE THREAD

**Issue by caniplzjustlogin4godsakesthistakesforev** [GregTechCEu/GregTech#2029]
### GregTech CEu Version

 gregtech-1.12.2-2.7.2-beta

### Modpack Used

Custom

### Addons Installed

See log files for complete list
(486) mods installed 

### Environment

Crash was on startup 

### Side Crashed

Client

### New Worlds

No

### Steps to Reproduce

Crash on start-up during pre-initialization; see attached log files and crash report for more information

### Crash Report

[crash-2023-07-31_21.25.17-client.txt](https://github.com/GregTechCEu/GregTech/files/12231817/crash-2023-07-31_21.25.17-client.txt)
[latest.log](https://github.com/GregTechCEu/GregTech/files/12231820/latest.log)
[debug.log](https://github.com/GregTechCEu/GregTech/files/12231821/debug.log)

### Additional Information

This line is why I'm reporting this here first, If this is solely on CraftTweaker's side my apologies "[21:25:17] [Client thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerNativeClass:101]: java.lang.NoClassDefFoundError: gregtech/api/recipes/crafttweaker/CTRecipeBuilder"

**Comment by PrototypeTrousers** [comment]
also try updating multiblocktweaker

**Comment by caniplzjustlogin4godsakesthistakesforev** [comment]
Removing dev-tech fixes it, now I just have to figure out how to deal with 400+ opengl out of memory errors that cpmpletely crash my pc (unrealed to gregtech), closing issue
