### ISSUE TITLE
New multifluid tank may cause crash when loading old worlds

### ISSUE THREAD

**Issue by YiRanMushroom** [GregTechCEu/GregTech#2115]
### GregTech CEu Version

v2.7.4

### Environment

Singleplayer

### Side Crashed

Unsure

### New Worlds

No

### Steps to Reproduce

Basically, when fluids being transfered in/out of some multi-fluid bus, crash could happen, also happens when loading into an old world. Don't actually know how to reproduce, because it often crash when loading.

### Crash Report

https://gist.github.com/YiRanMushroom/201fa02eccf4f0c5daafb911ce04a40a

### Additional Information

Some Logic and Interface change in the update may cause the issue

**Comment by Nrmot** [comment]
Does the same crash happen in 2.7.3?

**Comment by YiRanMushroom** [comment]
Found the problem, not because of gregtech.

**Comment by Irgendwer01** [comment]
@YiRanMushroom If it's an mod-compat issue, it would be still nice to know which mod causes this.
