### ISSUE TITLE
Possible to update old tools?

### ISSUE THREAD

**Issue by joshop** [GregTechCEu/GregTech#2135]
### Your Question

Hello! I have a small GTCEU server that I play on with a few friends - the only mods installed are GTCEU itself, JEI and OneProbe (and, for the record, you guys are doing a great job making GregTech playable without needing any other quality of life or logistics mods). I started the server on version 2.3.4, but there have been a good few versions since then and I want to update. In version 2.5.0, though, it looks like some IDs changed surrounding tools, like drills previously having been `meta_tool`s but are now `drill_lv`, `drill_mv`, etc. Are there any provisions for updating the tools as opposed to just having all of my old tools be lost? Should I just spawn new ones in based on what I had before?

**Comment by blisterrrrr** [comment]
just backup your world and update gregtech

**Comment by joshop** [comment]
Launching the server on 2.7.4, I get the "type `/fml confirm` to confirm missing registry entries" prompt which mentions `meta_tool`s, and if I confirm and log onto the server all of my tools are gone.

**Comment by htmlcsjs** [comment]
Yes, that is intentional, id suggest spawning in new tools to replace them. There was no way iirc to make them backwards compatible with the jank as old system

**Comment by joshop** [comment]
Alright, good to know. Makes sense that there wouldn't be a way to easily convert, just making sure.
