### ISSUE TITLE
Suggestion allow titanium cells to store acids

### ISSUE THREAD

**Issue by QuickStick123** [GregTechCEu/GregTech#2148]
### GregTech CEu Version

v2.6.2-beta / Nomi-CEu1.6.1a

### Related Problem

https://github.com/Nomi-CEu/Nomi-CEu/issues/516

Basically titanium is well known for acid resistance afaik but doesn't let them be stored in the mod.

### Your Solution

Allow titanium to store acids.

**Comment by IntegerLimit** [comment]
Suggestion: Fix the title. Currently it looks more like tritanium, which may confuse people.

**Comment by a-a-GiTHuB-a-a** [comment]
Would this be considered a balancing change?

**Comment by ghzdude** [comment]
Gold drums were introduced to handle early-game transferring of acids, could you not use that?

**Comment by QuickStick123** [comment]
I feel it is more of a consistency issue for the later game as there should be more options especially ones that make sense. Gold drums sound cool though for the early game.
