### ISSUE TITLE
GTCEu crashes on clean install

### ISSUE THREAD

**Issue by Xreturns** [GregTechCEu/GregTech#2156]
### GregTech CEu Version

All versions

### Environment

Never Started

### Side Crashed

Unsure

### New Worlds

Unsure

### Steps to Reproduce

1) Enter the game
2) wait about 3 seconds

### Crash Report

https://gist.github.com/Xreturns/cebb9efeea4b1e1580d457b604b4d7eb
crash report not generated

### Additional Information

Could be due to incompatibilities with AMD drivers, as that is a persistent issue with my Minecraft modding experience.
24gb of ram, RX 5500 XT (Adrenaline drivers 23.11.1, if it matters), Ryzen 5 5500
crashes before Forge loading screen is displayed.

**Comment by Xreturns** [comment]
Tested on another device, and it ran fine. it must be something with the hardware on this computer specifically.

**Comment by TechLord22** [comment]
This crash looks like ASM collision. Without a full mod list, the specific conflict isn't going to be possible to diagnose.

I also see your Java 8 version is `1.8.0_51` which is very old. For reference, the latest Java 8 release at present is `1.8.0_392`. Your version is the default version shipped with the CurseForge Launcher. If you are using the CurseForge Launcher, I would first suggest trying another launcher such as PrismLauncher. If that alone does not work, also try an up to date version of Java 8 with a non-CurseForge launcher.

If neither of the above resolve this, we are currently in the process of converting our ASM into Mixins, which may resolve this conflict in the process. This work is in-progress in #2192.

**Comment by Xreturns** [comment]
I’ve discovered the issue. Somehow, curseforge downloaded Gregtech twice. It says “CodeChickenLib-1.12.2-3.2.3.358-universal.jar” but inspection reveals it to be a clone of Gregtech CEu 2.7.4 beta. Reverting to an older version of CodeChickenLib fixes this immediately. Thanks for the help, though!
