### ISSUE TITLE
Issues to fix for 2.8.1

### ISSUE THREAD

**Issue by serenibyss** [GregTechCEu/GregTech#2207]
- [x] ~~Crash with GT 2.8 + Forestry + MagicBees + Thaumcraft when the bee removal config option is enabled (default)~~ will need to be fixed in a future update
- [x] HPCA provides computation when working is disabled
- [x] Fix Data Access Hatch render breaking when facing up or down
- [x] Fluid issues
    - [x] Fluids from other mods causing desync between GT material fluid and fluid registry master fluid
    - [x] Groovyscript/CT issues, and difficulty in adding/editing materials with fluids due to unclear errors
    - [x] Issues with addons creating fluids in their own registries? May just be one of the above, needs investigation
    - [x] Crashes using old syntax `addProperty(PropertyKey.FLUID, new FluidProperty())`
- [x] Groovyscript 0.7.0 compat
- [x] Fix cover ticking issues in obf environment
- [ ] Update wiki(s) for changes to material builder (blastTemp -> blast, fluid changes)
- [x] Fix multiblock tank exception when opening UI

**Comment by brachy84** [comment]
- [ ] GroovyScript 0.7.0 compat
