### ISSUE TITLE
[Suggestion] List of Needed Sounds

### ISSUE THREAD

**Issue by TechLord22** [GregTechCEu/GregTech#221]
This issue is meant to serve as a todo list for machine sounds needed, and is meant to expand upon #180. If you have a sound that can be used, please make a comment on this issue saying what of the follow should be used for, and a link to the sound. Please remember that sounds need to be allowed for use and must also be royalty free.

Tools:
- [x] Saw
- [x] Hard Hammer (vanilla might have somehting)
- [x] Soft Hammer
- [x] Wrench
- [x] File (can be same as saw)
- [x] Crowbar (vanilla might have somehting)
- [x] Screwdriver
- [x] Mortar
- [x] Wirecutter (maybe no sound, tbd)
- [x] Knife (can be same as saw)
- [x] Drill
- [x] Chainsaw
- [x] Plunger (can be same as soft hammer)
- [x] Buzzsaw (can be same as chainsaw)
- [x] Spray Can
- [x] Tricorder Scanner

Primitive Multiblocks:
- [x] Coke Oven (maybe no sound)
- [x] Primitive Blast Furnace (maybe no sound)
- [x] Primitive Water Pump (maybe no sound)

Steam Machines:
- [x] Solid Fueled Boilers (vanilla might have something)
- [x] Liquid Fueled Boilers (can be same as solid)

Electric Machines:
- [x] Electric Furnace
- [x] Macerator
- [x] Alloy Smelter (can be same as electric furnace)
- [x] Arc Furnace (can be same as electric furnace/alloy smelter)
- [x] Assembbler
- [x] Autoclave
- [x] Bender
- [x] Brewery
- [x] Canner
- [x] Centrifuge
- [x] Chemical Bath
- [x] Chemical Reactor
- [x] Compressor (can be same as bender)
- [x] Cutter
- [x] Distillery
- [x] Electrolyzer
- [x] Electromagnetic Separator (can be same as Electrolyzer)
- [x] Extractor
- [x] Extruder
- [x] Fermenter
- [x] Fluid Heater
- [x] Fluid Solidifier (maybe no sound)
- [x] Forge Hammer (vanilla might have something)
- [x] Forming Press (can be same as compressor/bender)
- [x] Lathe (can be same as cutter)
- [x] Mixer (maybe no sound)
- [x] Ore Washer (can be same as chemical bath)
- [x] Packer/Unpacker (maybe no sound)
- [x] Polarizer (can be same as electromagnetic separator/electrolyzer)
- [x] Laser Engraver (can be same as polarizer/etc?)
- [x] Sifter
- [x] Thermal Centrifuge (can be same as regular centrifuge)
- [x] Wiremill
- [x] Circuit Assembler (can be same as assembler)
- [x] Replicator
- [x] Scanner
- [x] Gas Collector (maybe no sound)
- [x] Rock Breaker (maybe no sound)
- [x] Simple Ore Washer (same as chemical bath/ore washing plant)
- [x] Singleblock Miners
- [x] Singleblock Fluid Pumps

Generators:
- [x] Combustion Generator
- [x] Steam Turbine (maybe no sound)
- [x] Gas Turbine (maybe no sound)
- [x] Magic Energy Absorber (maybe removed)

Multiblocks:
- [x] Electric Blast Furnace (maybe no sound)
- [x] Vacuum Freezer (maybe no sound)
- [x] Implosion Compressor (vanilla has something)
- [x] Pyrolyse Oven
- [x] Distillation Tower (maybe no sound)
- [x] Cracking Unit
- [x] Multi Smelter (can be same as electric furnace/etc)
- [x] Large Combustion Engine (can be same as combustion generator)
- [x] Large Steam/Gas/Plasma Turbine (can be same as single block turbines, maybe no sound)
- [x] Large Boilers (can be same as small boilers)
- [x] Assembly Line (can be same as assembler, maybe no sound)
- [x] Fusion Reactor (maybe no sound)
- [x] Large Chemical Reactor (can be same as regular reactor)
- [x] Steam Oven (can be same as electric furnace)
- [x] Steam Grinder (can be same as macerator)
- [x] Multiblock Miners
- [x] Multiblock Fluid Pumps

**Comment by joendter** [comment]
I would suggest this sound for saw/kinfe (it is a knife on a wood piece)
https://cdn.discordapp.com/attachments/904846945095385138/907668234449354822/saw_knife.ogg
I made this sound and i will allow any use for anything.
