### ISSUE TITLE
Crash due to groove(it is not installed)

### ISSUE THREAD

**Issue by ivashka0001** [GregTechCEu/GregTech#2236]
### GregTech CEu Version

2.8.1

### Environment

Singleplayer 

### Side Crashed

Client

### New Worlds

No

### Steps to Reproduce

1. Launch client.
2. Crash 
![Screenshot 2023-12-01 114619](https://github.com/GregTechCEu/GregTech/assets/67455441/c9039d0a-7675-4add-94e6-f674a79d0392)

### Crash Report

[Crash-report](https://gist.github.com/ivashka0001/d28258d708dbbffcb15062b6abd072d9)
[latest.log](https://gist.github.com/ivashka0001/413a45116e54479be658f127c2b42702)

### Additional Information

I saw that this groove bug was included in the upcoming patch 2.8.2. Is it possible to fix it without touching the code, since I'm a bread, or will I have to wait for 2.8.2 to fix this crash?

**Comment by Brunnosh** [comment]
also having this issue, only gtceu and forge 2860 for 1.12

**Comment by brachy84** [comment]
You can temporarily install GroovyScript.

**Comment by ivashka0001** [comment]
> You can temporarily install GroovyScript.
Tried it with GroovyScript and it doesn't work either.
[debug.log](https://gist.github.com/ivashka0001/bad59f83d8019cccc06362561106c248)
[latest.log](https://gist.github.com/ivashka0001/1cd2753a877483dd898e17d21b423182)

**Comment by Irgendwer01** [comment]
> `> You can temporarily install GroovyScript.` Tried it with GroovyScript and it doesn't work either. [debug.log](https://gist.github.com/ivashka0001/bad59f83d8019cccc06362561106c248) [latest.log](https://gist.github.com/ivashka0001/1cd2753a877483dd898e17d21b423182)

@ivashka0001 You forgot to install Mixinbooter

**Comment by ivashka0001** [comment]
`> @ivashka0001 You forgot to install Mixinbooter`
I have it)) Doesn't work with newer version either.
![Screenshot 2023-12-02 005104](https://github.com/GregTechCEu/GregTech/assets/67455441/c147cd94-1163-4035-b146-6f5cfdc1154d)

**Comment by ghzdude** [comment]
that version of mixinbooter is very old, you probably need to update it
