### ISSUE TITLE
LCR doesnt craft some things under special conditions

### ISSUE THREAD

**Issue by sreny1** [GregTechCEu/GregTech#2254]
### GregTech CEu Version

2.6.2-beta

### Modpack Used

Nomifactory CEu 1.6.1a

### Addons Installed

none, that dont come with the pack

### Environment

Sponge Server

### New Worlds

Yes

### Cross-Mod Interaction

Unsure

### Expected Behavior

LCR crafts all recipes, even when having ingredients for other recipes

### Actual Behavior

LCR doesnt craft some thing under special conditions

### Steps to Reproduce

1. Build a LCR with quadruple input + output hatch + some input bus
2. put circuit 1 in the input bus
3. feed the input hatch with chlorine, nitrogen, benzene and hydrogen (this is meant to make ammonia and chlorobenzene)
4. give it any lv+ tier power
5. watch the LCR make ammonia, but not chlorobenzene
6. remove the hydrogen from input hatch
7. watch the LCR make chlorobenzene

### Additional Information

i suspect this is because the LCR is blocked from the hydrochloric acid recipe which would be crafted without a circuit and it doesnt go on to check for the chlorobenzene recipe
i was looking through the issues on here and found nothing related to this, so i assume its stil an issue, but have not checked with newer version

**Comment by htmlcsjs** [comment]
afaik, this is intended behaviour, recipe logic is optimised to repeat the last recipe if there is input, instead of scanning and searching for a new one, which is computationally expensive.

**Comment by sreny1** [comment]
sad, it used to work. now you really need 1 LCR per recipe?

**Comment by htmlcsjs** [comment]
yea, unless you either do some multiplexing on the input or want massive tps lag with large bases

**Comment by sreny1** [comment]
i dont remember it to be an issue, but sure..
