### ISSUE TITLE
Nuclear Fission Reactor Crash

### ISSUE THREAD

**Issue by whatsapp2** [GregTechCEu/GregTech#2336]
### GregTech CEu Version

gregtech-1.12.2-2.8.5-beta

### Environment

Singleplayer

### Side Crashed

Client

### New Worlds

Yes

### Steps to Reproduce

Build following reactor:
Fully-formed reactor view:
![image](https://github.com/GregTechCEu/GregTech/assets/25994176/f3bee1a6-ce5d-408a-a999-a4fe314ed36e)

Reactor view without the top lid:
![image](https://github.com/GregTechCEu/GregTech/assets/25994176/258bfe25-e609-4a18-8bce-7f3b59e51557)

Reactor view with the top lid hovering above:
![image](https://github.com/GregTechCEu/GregTech/assets/25994176/e7b2ec13-97b4-41df-89bf-399a80842273)

Reactor bottom view:
![image](https://github.com/GregTechCEu/GregTech/assets/25994176/a1283318-a65c-4a40-a092-0d8af0e0b466)

Whenver you try to toggle on the reactor, the game crashes. I've tested this 5 times with different configurations, introducing any kind of fuel rod, coolant or simply run the reactor empty, and it still crashes. I also tried doing different types of reactor configurations also used the JEI  multiblock preview reactor and it will crash if I use any fuel rod input/output in it. 

### Crash Report

https://gist.github.com/whatsapp2/3a7df8b98b49de3e11228e90561f6a17#file-gistfile1-txt

### Additional Information

World is irrecoverable after crash.

**Comment by Allison-Rodrigo** [comment]
Trying to reproduce, it really crashed irrecoverably with other similar designs like this one:

![crash foda](https://github.com/GregTechCEu/GregTech/assets/95299389/ad751ee9-7c31-4891-bcf4-aa16c10e8c6a)

This Setup, with only coolant channels and ports also causes the same issue:
![image](https://github.com/GregTechCEu/GregTech/assets/95299389/33b32526-9e73-4324-9609-be327bf13561)

Setups without cooling channels work don't cause this:
![not crashing setups](https://github.com/GregTechCEu/GregTech/assets/95299389/a89494ad-c070-4f53-aa12-f3a50a7e5ae6)

But as soon as i added cooling channels and the coolant ports it crashed the game

**Comment by tong-ge** [comment]
[crash-2024-01-19_00.24.41-server.txt](https://github.com/GregTechCEu/GregTech/files/13979206/crash-2024-01-19_00.24.41-server.txt)

**Comment by StarL0st** [comment]
@Zalgo239 may want to look at this
