### ISSUE TITLE
[Suggestion] Water wheel

### ISSUE THREAD

**Issue by SpeeeDCraft** [GregTechCEu/GregTech#237]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
It would be cool if there was a water wheel in the GT, with the help of it it would be possible to produce electricity, even if the smallest. The implementation of a similar one is in the ImmersiveEngeneering modification.

**Comment by Syrcan** [comment]
Such a feature belongs more to an addon or modpack.
