### ISSUE TITLE
Using LV batteries in an LV wiremill makes some recipes unstartable

### ISSUE THREAD

**Issue by saldejums** [GregTechCEu/GregTech#2378]
### GregTech CEu Version

v2.8.6-beta

### Addons Installed

Only CodeChicken Lib 1.12.2-3.2.3.358.

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Recipe starts even though the internal buffer does not exceed the necessary EU for the craft.

### Actual Behavior

Recipe does not start.

### Steps to Reproduce

Add an LV battery as the energy source in an LV wiremill and try to make either a 1x or 2x silver wire.

### Additional Information

Internal buffers only get charged to 1/3rd of the capacity through batteries. For LV machines that is 704EU (1/3rd of 2048 in increments of 32). 1x and 2x silver wire recipes require 749 EU. Other machines start the recipe even though they don't have the full amount of energy required (8t energy requirement check). Weirdly enough LV wiremills still can make 4x and higher amp cables with the use of LV batteries.

Not sure why internal buffers cannot be charged past 1/3rd using batteries.

**Comment by kumquat-ir** [comment]
Fixed in #2365, which will be in next release
