### ISSUE TITLE
[Suggestion] Arrays of solar panels

### ISSUE THREAD

**Issue by SpeeeDCraft** [GregTechCEu/GregTech#238]
**Is your feature request related to a problem? Please describe.**
GT mod is about technology, but for some reason there are no cool energy sources in it. By the type of solar panels, windmills.

**Describe the solution you'd like**
I've heard somewhere that GT developers don't add such infinite sources for some reason. I propose such a system, after assembling the solar panel, as it works, its efficiency will fall, and the strength or resource of the batteries will be exhausted. After that, they will need to be disposed of somehow. All timings can be configured in the config file. There will be just at least some reason to use solar modules that already exist in GT

**Additional context**
![image](https://user-images.githubusercontent.com/52341158/141601930-483fbb0e-8fec-403b-af5e-ee1c036223e4.png)
The orange wool shows the frame blocks.
The blue wool shows solar panel blocks or something.
In the center is an example of a controller.

**Comment by brachy84** [comment]
we are not environmental tech :trollface: 

but for real, we already talked about it [here](https://github.com/Gregicality/gregicality/issues/570#issuecomment-887683855)

**Comment by Syrcan** [comment]
Such a feature belongs more to an addon or modpack.
