### ISSUE TITLE
[Suggestion] Wind turbines

### ISSUE THREAD

**Issue by SpeeeDCraft** [GregTechCEu/GregTech#239]
**Is your feature request related to a problem? Please describe.**
Because it's not in GT :D

**Describe the solution you'd like**
Most likely this will be a multiblock machine. You can even add some animation when the rotor is placed in the turbine. As it used to be in ic2. Only implement it better. The rotors will gradually break down. Perhaps even the block holding the rotor will receive some damage. And they will need to be replaced regularly. Of course, all these parameters can be changed in the config. 
The strength of the rotor spin will depend on the weather and the height at which the rotors are installed. But the maximum height should be configurable in the config. The maximum height is the height of the world at which the increase in energy production is no longer growing.

For example:
Max: 120.
y = 60 - eu = 20
y = 80 - eu = 60
y = 100 - eu = 150
y = 120 - eu = 240
y = 140 - eu = 250
y = 200 - eu = 260

Also, when the maximum height is exceeded, the rotors break 3-4 times faster. 

**Additional context**
Approximately it should look like this, but of course I built it in 5 seconds, other representations are possible, but I wanted it to look realistic enough. I think this design should be huge. Since in reality, windmills are huge. Maybe 3-4 times more than in my screenshot.
![image](https://user-images.githubusercontent.com/52341158/141602266-8d7ea12b-fdd0-4f29-87f4-c01e8d7fd20a.png)

**Comment by Syrcan** [comment]
Such a feature belongs more to an addon or modpack.
