### ISSUE TITLE
Devtech problem with Gregtech (need RecipeMap$IChanceFunction.class file)

### ISSUE THREAD

**Issue by Shibidibop** [GregTechCEu/GregTech#2395]
### Your Question

Story: All time when I tried use this mod with Devtech mod, game crashed. I've made research trying chnge verion, addon version, next looking at simillar problem on github and nothing. Finally I was being searching error (am not great programer but i tried find anything what can say me what goes down). Devtech require RecipeMap$IChanceFunction.class to work together with GTCEu. I patched this using basoukou mod to get patch but HEY this file is fully compatibile with mod and can be simple added. Could be normally in mod and should be.

Now could i ask do you can put this file in mod in gregtech/api/recipes (RecipeMap$IChanceFunction.class is casual class copied from GTCE and i nothing changed withe them, cause I can't)

Would be nice...

data about mods:
- devtech v2.1.2
- gregtech v2.8.7
- crafttweaker v4.1.20.698
- GregicalityMultiblocks v1.2.8
include some more mods but i dont think they might cause anything else.

**Comment by brachy84** [comment]
Could just ask me nicely to update devtech

**Comment by Shibidibop** [comment]
I'm so sorry
