### ISSUE TITLE
Crash with Vintagium on joining world

### ISSUE THREAD

**Issue by MCTian-mi** [GregTechCEu/GregTech#2406]
### GregTech CEu Version

v2.8.7

### Environment

Singleplayer

### Side Crashed

Client

### New Worlds

Yes

### Steps to Reproduce

1) Install both CEu and Vintagium
2) Start the game and enter a world
3) Game crashes

### Crash Report

https://mclo.gs/Yk9a0zg

### Additional Information

Related: Asek3/sodium-1.12#17

**Comment by NostalgicLorikeet** [comment]
Can confirm this also happens to me. Any config changes or anything that can fix it?
