### ISSUE TITLE
quest book  and That One Probe Read Me items. missing. 

### ISSUE THREAD

**Issue by sircorneilous** [GregTechCEu/GregTech#2407]
### Your Question

i downloaded and installed the latest version of the mod. and when i make a new world i don't see the items in my hotbar. and i go in creative and look for the items and they where not their i even tried /give and nothing. whats wrong?

**Comment by h3nry-s71ckm1n** [comment]
...Are you not experienced in modding or what? You have to download The One Probe and Better Questing Unofficial to even get those items.

**Comment by sircorneilous** [comment]
Yes I am experienced with modding. I've been doing it for years.
(Downloading and installing them. Not developing them)
