### ISSUE TITLE
LD pipe networks do not work

### ISSUE THREAD

**Issue by fatboychummy** [GregTechCEu/GregTech#2418]
### GregTech CEu Version

1.1.3.b

### Modpack Used

GregTech Community Pack Modern v1.7.0

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

When placing a pipeline (longer than 50 blocks), fluid should be able to flow through it.

### Actual Behavior

Fluid does not flow through pipeline endpoints. Other types of fluid pipes actually even refuse to auto-connect (when placing with shift+rclick) to the pipeline endpoints.

### Steps to Reproduce

1. Place long pipeline (>50 blocks, I tested with ~100 and ~300 block pipelines).
2. Add endpoints (or do this part first, either way seems to result in the same).
3. Add a fluid tank source to your input endpoint and set it to output into the endpoint.
4. Add an empty fluid tank to your output endpoint.
5. Observe that no fluid gets outputted on the other side, and the fluid tank does not fill.

### Additional Information

<details><summary>Random tested setups of pipes</summary>

![image](https://github.com/GregTechCEu/GregTech/assets/39929480/b33a3284-31d1-4d8a-ad75-a37faaf014bf)
</details>

<details><summary>Other fluid pipes not connecting</summary>

https://github.com/GregTechCEu/GregTech/assets/39929480/51249235-465b-4645-a7f6-28a5cc19e592
</details>

**Comment by ghzdude** [comment]
i think this was meant to go to the modern ceu repo, found here: https://github.com/GregTechCEu/GregTech-Modern

**Comment by fatboychummy** [comment]
Sorry, this was meant to be on GregTech-Modern.
