### ISSUE TITLE
Regarding textures

### ISSUE THREAD

**Issue by Ezoteric** [GregTechCEu/GregTech#2421]
### Your Question

I got a couple of questions regarding the textures as I am doing the puredbcraft for them.

1. Are small ore blocks being used?
2. In assets\gtceu\textures\block\multiblock, most of them use the same textures, is this planned to be changed, if not, could you just make a generic folder so all the ones that use the same texture will use that 1  texture as having 20 of the same is an unnecessary extra load.
3. With the fluid/gas/etc, you have a couple that use their own texture and others use 1 generic file of their type, why is that and could this also just use that 1 generic for their type, again seems like an unnecessary extra load.

Just my 2 cent.

**Comment by screret** [comment]
1. no
2. no, this way texture packs can change a specific machine's look
3. it's fancier and makes the fluids more distinct; it's mostly done for common fluids

**Comment by Ezoteric** [comment]
Thanx for fast reply, and yes seems fair about Q2. 

one more Question is, are emissive layers being used? as i also saw a bunch of those and didnt notice anything ingame.

**Comment by screret** [comment]
yes they are. are you using optifine?

**Comment by Ezoteric** [comment]
Ok, i haven't checked everything indept yet so i could be i missed it.

I have 2 installs one with Optifine and the other with oculus.

**Comment by screret** [comment]
oculus? are you sure you're in the correct git?

**Comment by Ezoteric** [comment]
this is for 1.20 right

**Comment by screret** [comment]
no this is the 1.12 version

**Comment by screret** [comment]
GregTechCEu/GregTech-Modern is what you probably want

**Comment by Ezoteric** [comment]
Yeah i did press the issue button on curse on the gtceu for 1.20 i just checked

**Comment by Ezoteric** [comment]
weird ill try again, thnx anyway :P
