### ISSUE TITLE
Forestry module(Electrode)

### ISSUE THREAD

**Issue by ivashka0001** [GregTechCEu/GregTech#2430]
### Your Question

Hello, I encountered a problem with crafting an iron electrode. As I understand it, in the code that adds the integration of electrodes for forestry there is one “if” function.
![image](https://github.com/GregTechCEu/GregTech/assets/67455441/ba1dd212-e83b-4313-bf2e-cc22a04e51a2)

 It does not allow you to craft an iron electrode without an integrated IC2. How can I bypass this function and create a craft in CraftTweaker? Thanks in advance for your answer!

**Comment by serenibyss** [comment]
Unfortunately this is locked like this because Forestry does a similar check to enable the item. After another PR merges (#2192) I plan to bypass the Forestry check and not require other mods to be enabled for this compat

**Comment by ivashka0001** [comment]
Thanks for the answer! I'm waiting for your changes!)
