### ISSUE TITLE
Distillation tower is not working

### ISSUE THREAD

**Issue by METABYTECODE** [GregTechCEu/GregTech#2447]
### GregTech CEu Version

gtceu-1.20.1-1.2.0.a-build_587

### Modpack Used

ATM 9 / Only Forge+ GTCEU

### Environment

Single

### New Worlds

Yes

### Cross-Mod Interaction

Yes

### Expected Behavior

lightly steam cracked naphta -> 11 liquids

### Actual Behavior

![image](https://github.com/GregTechCEu/GregTech/assets/62258232/8256fa9e-28b8-41f6-8e89-11bff936e465)
![image](https://github.com/GregTechCEu/GregTech/assets/62258232/6cb11369-6707-406c-a49c-e8ca201a5e45)
The liquid is not processed,

### Steps to Reproduce

Build DisTower -> In input (lightly steam cracked naphta) -> machine is not star process

**Comment by ghzdude** [comment]
please move this issue to https://github.com/GregTechCEu/GregTech-Modern/issues
