### ISSUE TITLE
crash with NuclearCraft-2.18zzz-1.12.2

### ISSUE THREAD

**Issue by ders360** [GregTechCEu/GregTech#2454]
### GregTech CEu Version

GregTech: 2.8.7-beta

### Modpack Used

custom 

### Environment

startup 4/7

### Side Crashed

Client

### New Worlds

Yes

### Steps to Reproduce

have both GregTech: 2.8.7-beta and NuclearCraft-2.18zzz-1.12.2 installed at the same time

### Crash Report

[crash-2024-04-16_18.36.19-client.txt](https://github.com/GregTechCEu/GregTech/files/15003811/crash-2024-04-16_18.36.19-client.txt)
[latest.log](https://github.com/GregTechCEu/GregTech/files/15003812/latest.log)

### Additional Information

gregtech-1.12.2-2.0.3-beta works for some reason

**Comment by ghzdude** [comment]
you need to disable NuclearCraft's recipe compat with Gregtech.
![image](https://github.com/GregTechCEu/GregTech/assets/44148655/15ba51c9-b357-4888-8041-824babbef41f)

**Comment by ders360** [comment]
nope still crashes
[latest.log](https://github.com/GregTechCEu/GregTech/files/15003882/latest.log)

**Comment by ders360** [comment]
works if i roll nuclearcraft back to 2.16

**Comment by PSR2144-3933** [comment]
this one is already fixed in newer version. should be closed

**Comment by ALongStringOfNumbers** [comment]
NuclearCraft has now been updated, so compat should be working once again.
