### ISSUE TITLE
Bloom layer cannot be handled by Vintagium (Sodium 1.12), causing crash on world load

### ISSUE THREAD

**Issue by NostalgicLorikeet** [GregTechCEu/GregTech#2462]
### GregTech CEu Version

v2.8.7-beta

### Environment

Singleplayer

### Side Crashed

Client

### New Worlds

Yes

### Steps to Reproduce

1. Install Vintagium and GregTech together
2. Load world

### Crash Report

[](https://mclo.gs/bDy4rWc)

### Additional Information

[Vintagium can be downloaded here](https://github.com/Asek3/sodium-1.12/actions)  (not on curseforge)

GTCEu crashes the game alongside Vintagium because of the bloom it adds to certain blocks (although it crashes the game no matter what blocks are in the world, this was tested on a void superflat world)

[This](https://github.com/Asek3/sodium-1.12/blob/12.x/forge/src/main/java/me/jellysquid/mods/sodium/client/render/chunk/passes/BlockRenderPassManager.java) class is the one mentioned in the crash report. Vintagium can handle the SOLID, CUTOUT_MIPPED, CUTOUT, and TRANSLUCENT layers, but cannot do so for the "Bloom" layer added by GT.

According to Vintagium's dev, the problem lies [here](https://github.com/GregTechCEu/GregTech/blob/master/src/main/java/gregtech/asm/visitors/RegionRenderCacheBuilderVisitor.java) on your end

This issue has been reported to the developer of Vintagium, however they have indicated it is an issue on your end.

**Comment by htmlcsjs** [comment]
There would have to be support for adding other render layers in this, we _can_ hack it apart on GT's end but adding more extensible support here would be better imo. I will try and fix the crash by straight up disabling bloom if this is installed with GT in the mean time, (we currently do something similar with optifine)

**Comment by NostalgicLorikeet** [comment]
Thanks! I was looking forward to using the bloom lights, but it's nice to see a fix that could make the two compatible in the meantime. Looking thru Vintagium's code it seems like they intend on adding a better implementation for render layers based on code comments.

**Comment by htmlcsjs** [comment]
The fix does allow bloom to fully work, its more of that its using ASM and reflecting stuff, instead of a nice api on vintagium's end

**Comment by NostalgicLorikeet** [comment]
When I compile and add this to my pack there are some problems that seem to be caused by dependencies. Have any new dependencies been added since the last released version?

**Comment by kumquat-ir** [comment]
There is unreleased work (the ui rework) on the master branch that adds a couple new dependencies (modularui and mixinbooter) and hasnt been in any releases yet since its not done yet.

**Comment by NostalgicLorikeet** [comment]
I have both installed but I still get a crash
![image](https://github.com/GregTechCEu/GregTech/assets/29894500/95d87bf5-cf38-4a30-b8d1-7311ae7769f1)
![image](https://github.com/GregTechCEu/GregTech/assets/29894500/9cc9c75c-b182-4e13-8df8-192ce2d6b0b5)

**Comment by htmlcsjs** [comment]
a) i think you used the deobfiscated, developer build of the mod
b) [here](https://cdn.discordapp.com/attachments/824996297621897216/1234210424228942006/gregtech-1.12.2-2.8.7-vintagium-support.jar) is a building of gt that is just 2.8.7 with the patch cherrypicked in, you **do not** need ModularUI and Mixinbooter for this build

**Comment by NostalgicLorikeet** [comment]
Yeah, it had -dev in the filename but it was the only jar i could find that compiled. Also I was given that in the Discord, thanks!
