### ISSUE TITLE
Robot arm with Keep exact mode wont pull items from chest

### ISSUE THREAD

**Issue by Alex-265** [GregTechCEu/GregTech#2643]
### GregTech CEu Version

2.8.10-beta

### Modpack Used

Nomifactory CEu 1.7a

### Environment

Forge server

### New Worlds

Yes

### Cross-Mod Interaction

Unsure

### Expected Behavior

The robot arm should pull the item from the chest

### Actual Behavior

The items dont get pulled
https://youtu.be/oCxKz96B7o8

### Steps to Reproduce

Build a Storage crate with items needed for a recipe next to a machine. Insert a robot arm on the side and set it to keep exact

**Comment by ghzdude** [comment]
You need an item filter, since the machine already has 64 "items" in it already

**Comment by Alex-265** [comment]
thanks

**Comment by Alex-265** [comment]
thanks
