### ISSUE TITLE
crash with addons

### ISSUE THREAD

**Issue by Lendangame** [GregTechCEu/GregTech#2687]
### GregTech CEu Version

2.10,8

### Modpack Used

my

### Addons Installed

greg beyond core . food option . greg aditions unof

### Environment

single

### Side Crashed

Client

### New Worlds

No

### Steps to Reproduce

just launch the game

### Crash Report

https://mclo.gs/8046cc5

**Comment by Lendangame** [comment]
*nomifactry ceu with other mods

**Comment by Zorbatron** [comment]
[GregicAdditions Unofficial](https://www.curseforge.com/minecraft/mc-mods/gregicadditions-unofficial) is for GT:CE, not GT:CEu. Does it launch without it?

**Comment by Lendangame** [comment]
I know, but I was hoping it would work.

**Comment by Lendangame** [comment]
and are there any addons for gtceu besides zorbatron?

**Comment by Zorbatron** [comment]
You can look through this https://legacy.curseforge.com/minecraft/mc-mods/gregtech-ce-unofficial/relations/dependents. 
Not sure why curse doesn't let you filter only mods and not modpacks, but it should show most of them.

**Comment by Lendangame** [comment]
Thanks, sorry for bothering you.

**Comment by Zorbatron** [comment]
No problem :+1:

**Comment by Lendangame** [comment]
Hi, I didn't install any addon except zorbatron. They all crash minecraft. What should I do with it?

**Comment by Lendangame** [comment]
Hi, I didn't install any addon other than zorbatron, they all crash minecraft, what should I do with it?

**Comment by Lendangame** [comment]
Hi, if I'm installing any addon for gtceu, my minecraft crash :((

**Comment by IntegerLimit** [comment]
What addon are you using? Send the crash log as well.

**Comment by Lendangame** [comment]
for example gt wood ore processing or modpack cores, but that's okay

**Comment by Lendangame** [comment]
and mmodpack crash if i add neeves ae2
