### ISSUE TITLE
Large bronze boiler issue

### ISSUE THREAD

**Issue by Chryseus** [GregTechCEu/GregTech#270]
I made a large bronze boiler for use with creosote but noticed that it does not consume any fuel unless 16,000mb is provided making it impossible to use a single ULV hatch, this fuel is then consumed all at once, JEI says it should consume 160mb for 0.5 seconds, in testing I found it runs for 153 seconds on the 16 buckets of creosote at 100% throttle.

This problem may also apply to other large boilers but I've not checked yet.

**Comment by DStrand1** [comment]
Closed by #417
