### ISSUE TITLE
[Suggestion] Add a rechargable ZPM and an Armor Set above Gravi that is stronger

### ISSUE THREAD

**Issue by Shattered2909** [GregTechCEu/GregTech#276]
As the name implies, add a way to make a rechargable ZPM and an Armor Set above Quantum/Gravi that is made from Naquadah Alloy and takes 1 Rechargable ZPM per piece to craft. Maybe give it a little bit of Shielding like Thaumcrafts Runic Baubles?

**Comment by ALongStringOfNumbers** [comment]
As of now, ZPMs are rechargeable in CEu. So there is no need for an additional battery. The additional suite of armor can still be discussed though.

**Comment by Syrcan** [comment]
I believe QuarkTech is high tier enough for CEu. But another mod or addon may add something fancier and higher tier.
Since this is an old issue, I am closing it.
