### ISSUE TITLE
Slot/Widget Issues

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCEu/GregTech#351]
Issues with slots and widgets, gathered into one place for easy referencing.

### Crafting Station
- Memorized Recipes can only be locked with shift clicking on them with something in the player's cursor. Shift clicking on the recipe to lock it without first picking up an item will not lock the recipe.
- Highlighting of missing and present recipe components for recipes in the crafting station no longer works (Ask bru for clarification on this one, he was the one who made the feature and knows what exactly is supposed to happen)
- Crafting a recipe in the crafting station damages all tools of the same type in the players inventory, and also damages the tool in the recipe's memory.
- Shift clicking a recipe from JEI into the crafting station some times does not correctly populate the crafting grid widget on a server (not sure if happens on client, but I had it happen on a server). 
Example:
![2021-12-04_17-27](https://user-images.githubusercontent.com/31759736/146126874-68012882-fad3-429c-9aec-b59ff6f37602.png)

### General Issues
- Cannot drag a stack of items to evenly split them across slots in GT GUIs like the crafting station or crates. When these GUIs are open, you cannot do this in the player inventory either.
- Enchantment glint is applied to the entire slot in GT inventories (this was in a crate specifically):
![2021-12-14_22-17](https://user-images.githubusercontent.com/31759736/146127800-a8825113-4490-4a20-94ca-66df15d80c17.png)

### Some desired changes
- Make it so you cannot shift click items into the charging slot in machine GUIs, but still can place any item there normally.

**Comment by TechLord22** [comment]
When opening any GT owned inventory, picking up items with the mouse, and attempting to put them back into the player's inventory slots sometimes takes multiple tries (clicks) for the items to actually transfer.

**Comment by bruberu** [comment]
On the crafting station highlighting, any of the crafting station slots with a ghost item in them should be highlighted red if the crafting station cannot find any item that matches it in its inventory (to help players realize that oh, you need to move that rubber plate in before it actually crafts).

**Comment by Yefancy** [comment]
#366

**Comment by htmlcsjs** [comment]
This crash happened after the slot pr was merged:
[crash-2021-12-19_20.05.51-client.txt](https://github.com/GregTechCEu/GregTech/files/7741521/crash-2021-12-19_20.05.51-client.txt)
i was trying to shift click from a virtual gui (in this case a monitor)

**Comment by ALongStringOfNumbers** [comment]
Items are not the correct brightness when rendered in the GUI proxy view on the central monitor:
![2021-12-20_17-37](https://user-images.githubusercontent.com/31759736/146851396-bddb3d34-e578-45d4-b8db-80ce042dc606.png)

**Comment by Syrcan** [comment]
It looks like all (or most) of the concerns involved in this issue have been resolved.
I am closing it, I'd say to open a new issue if some of those are still a problem.
