### ISSUE TITLE
[BUG] Crash on startup

### ISSUE THREAD

**Issue by AffectAge** [GregTechCEu/GregTech#435]
**Describe the bug**
Crash onj startup

**Versions**
Forge: v14.23.5.2860
GTCE:  gregtech-1.12.2-2.0.1-beta

**Setup**
Playing Both
[crash-2021-12-30_14.37.24-client.txt](https://github.com/GregTechCEu/GregTech/files/7793144/crash-2021-12-30_14.37.24-client.txt)

**Comment by SpeeeDCraft** [comment]
Some strange modpack with TFC and GT, try TFG :trollface:

**Comment by AffectAge** [comment]
> Some strange modpack with TFC and GT :trollface:

Nothing new, such modpacks have been doing for years. And this one is for a geopolitical server with roleplaying.
