### ISSUE TITLE
[Suggestion] Configuration for the hardness of the vein indicator

### ISSUE THREAD

**Issue by SpeeeDCraft** [GregTechCEu/GregTech#453]
**Is your feature request related to a problem? Please describe.**
Adding a parameter such as the hardness of the indicator to the config. All so that it can be broken by hand.

**Describe the solution you'd like**
The vein indicator can be broken by hand(config).

**Additional context**
This would be useful to modpack makers. And me, of course :trollface: 
For example, in TFC, you cannot get a pickaxe at the initial stages of the game to dig up indicators. And what I described above could solve the problem.

**Comment by brachy84** [comment]
Fixed in #474. The rocks can now be mine by hand. Just right click works too
