### ISSUE TITLE
Will the original attached mod be supported?

### ISSUE THREAD

**Issue by xingchengs** [GregTechCEu/GregTech#460]
Will the original attached mod be supported?

**Comment by htmlcsjs** [comment]
May I ask, what original attached mod?

**Comment by xingchengs** [comment]
As your gregicality

**Comment by brachy84** [comment]
Yes, gregicality will be split into two mods: Gregicality: Multiblocks and Gregicality: Science
GCY:M is planned to be released soon which will contain multiblock stuff.
