### ISSUE TITLE
[BUG/FEATURE] A primitive pump pumps only vanilla water.

### ISSUE THREAD

**Issue by SpeeeDCraft** [GregTechCEu/GregTech#464]
**Describe the bug**
A primitive pump pumps only vanilla water.

**Versions**
Forge: 2860
GTCE: 2.0.2-beta
_Modpack:_ TFG R3.0

**Setup**
Playing Solo/Multiplayer/**Both**

**Steps To Reproduce**
1) I built a primitive pump
2) But I get vanilla water

**Expected behavior**
A primitive pump was supposed to extract water from TFC (salty or fresh).

**Additional context**
I would suggest adding a configuration where you can specify what kind of liquid the primitive pump produces. This will be useful not only for my modpack.
Like this:
```
# The liquid produced by a primitive pump.
# Useful for mods like TerraFirmaCraft with different Fluids for Water
# Default: water
S:PrimitivePumpFluid <
   salt_water
>
```

**Comment by Syrcan** [comment]
I haven't seen motivation to implement this since this came up.
If motivation arises again we can re-open it and maybe implement it.
