### ISSUE TITLE
Rendering screen crash w/ Building Gadgets

### ISSUE THREAD

**Issue by PsychoSwan** [GregTechCEu/GregTech#468]
While in the terminal, certain actions crash the game due to some issue with building gadgets & GT CEu
[crash-2022-01-04_22.14.28-client.txt](https://github.com/GregTechCEu/GregTech/files/7811810/crash-2022-01-04_22.14.28-client.txt)

**Comment by kumquat-ir** [comment]
This issue has already been fixed in dev, and the fix will be in the next release

**Comment by PsychoSwan** [comment]
Alright. I guess you can close this if it's already been fixed for the next release.
