### ISSUE TITLE
Credit

### ISSUE THREAD

**Issue by draknyte1** [GregTechCEu/GregTech#498]
It would be nice to credit me for all the things *borrowed* from GT++.

**Comment by Rongmario** [comment]
You're still alive?

**Comment by draknyte1** [comment]
> You're still alive?

And still actively developing things.

**Comment by htmlcsjs** [comment]
we took no assets nor code for gt++

**Comment by Rongmario** [comment]
DM me if you want to throw a hissy fit.

**Comment by draknyte1** [comment]
> we took no assets nor code form gt++ afaik

Besides the point.

**Comment by htmlcsjs** [comment]
_borrowed_ has way different connotations than inspired, can you be more specific

**Comment by ManOfVeg** [comment]
no

**Comment by screret** [comment]
> Copyright does not protect ideas, concepts, systems, or methods of doing something.
From https://www.copyright.gov/help/faq/faq-protect.html

**Comment by Leclowndu93150** [comment]
Lmao
