### ISSUE TITLE
List of Terminal guides

### ISSUE THREAD

**Issue by Regian24** [GregTechCEu/GregTech#508]
Here's one I made for JEI

It is probably impossible to try to play GregTech without using JEI. 
So here are some tips on how to use JEI to its full potential.

- Bookmark items regularly (default key A) so you don't have to type the names every time you want to look them up. 
- Most of the items have multiple crafting recipes! Don't stop at the first recipe and think that item is impossible. Sometimes a material is only available from tiny dusts, sometimes it's available from a fluid solution. It takes some practice. Oil processing and nuclear chemistry are pretty bad about this.
- Take advantage of the Material Tree page in JEI. The Material Tree shows you a diagram of how you make every part (plates, ingots, rods, etc.) from a material. 
- You can press @ to see only items from that mod. For example, if you search for @gregtech, you will only see items from GregTech.
- You can press $ to see only items from a specific entry in the Ore Dictionary. For example, if you search for $logWood, you will only see wooden logs.

**Comment by Syrcan** [comment]
😢
