### ISSUE TITLE
Crash when fluid pipe is placed between a pumped drum and two machines

### ISSUE THREAD

**Issue by mechobree** [GregTechCEu/GregTech#532]
**Describe the bug**
I was making my pipe network for steam, placed a pump on a drum, and the block above it had a steam turbine, to the north was a steam macerator. Once i placed down the pipe my game crashed and I can no longer load into the world.

**Versions**
Forge: 14.23.5.2860
GTCE: 2.0.4-beta
_Modpack:_ [TerraFirmaGreg](https://www.curseforge.com/minecraft/modpacks/terrafirmagreg) Version R3.0.5 with added [mods](https://pastebin.com/2LM93Bqy) 
[Crash Report](https://pastebin.com/Yy27QwKt)

**Setup**
Playing Solo (on a world that was updated from the old gtce and gregicality)

**Steps To Reproduce**
1) Place a drum that is actively gaining steam (and is full)
2) place an lv pump to the left side, place a steam turbine above the block to the left of the drum
3) add a steam macerator behind the block next to the pump
4) place the pipe (small bronze in my case) next to the drum where the pump is

**Expected behavior**
The pipe to work and steam goes into both the turbine and the macerator :)

**Screenshots**
![javaw_01 17 22 23 45 27](https://user-images.githubusercontent.com/29335214/149872497-224b54ef-71e6-4476-970b-64f7bf07cc7e.png)
This is the setup (minus the creative tank, I used that as the steam provider in this case), for some reason I could not replicate it on a new save, perhaps it was because the machines that were placed were originally from the other gregtech version?

**Comment by TechLord22** [comment]
To clarify, when you said "the machines that were placed were originally from the other gregtech version," do you mean that the world you originally crashed in was created with regular GTCE, and not the unofficial one?

**Comment by brachy84** [comment]
What in the name of fuck

**Comment by mechobree** [comment]
> To clarify, when you said "the machines that were placed were originally from the other gregtech version," do you mean that the world you originally crashed in was created with regular GTCE, and not the unofficial one?

[I'm referring to this one](https://www.curseforge.com/minecraft/mc-mods/gregtechce)
It was after updating the modpack in question, the creator switched between that one and this one

**Comment by SpeeeDCraft** [comment]
I have said that upgrading old worlds, from the old GTCE to new worlds with GTCEu, can cause the death of your world. I doubt if this can be fixed somehow. And in general, does anyone want to fix it. This is not advisable. Just transfer things from memory from one world to another. My friends and I did exactly that.

**Comment by SpeeeDCraft** [comment]
For the sake of interest, I would like to ask. Why add to TFG, Immersive Engineering if there is a GT in the modpack?

**Comment by mechobree** [comment]
> 



> I have said that upgrading old worlds, from the old GTCE to new worlds with GTCEu, can cause the death of your world. I doubt if this can be fixed somehow. And in general, does anyone want to fix it. This is not advisable. Just transfer items from memory from one world to another. My friends and I did exactly that. I very much doubt that this is a GTCEu bug.

Yeah, was planning on doing that anyways, but figured I'd send over a report on the off chance it was dumb luck of encountering a bug, if it's just due to the unstable nature of conflictions then I'll just close this issue

**Comment by mechobree** [comment]
> 



> For the sake of interest, I would like to ask. Why u add to TFG, Immersive Engineering if there is a GT in the modpack?

I was originally planning to use their wires for long distance power transfer if I could transfer EU->IE but eventually decided not to, now I just have it for the decoration aspects

**Comment by SpeeeDCraft** [comment]
You can use the Engineers Decor mod, it adds a lot of decor related to Immersive Engineering. But in this case, you will not need to install Immersive Engineering, which will increase FPS and reduce RAM usage.

> > 
> 
> > For the sake of interest, I would like to ask. Why u add to TFG, Immersive Engineering if there is a GT in the modpack?
> 
> I was originally planning to use their wires for long distance power transfer if I could transfer EU->IE but eventually decided not to, now I just have it for the decoration aspects
