### ISSUE TITLE
[BUG] Autocraft AE2 - GTCEu

### ISSUE THREAD

**Issue by Castanea43** [GregTechCEu/GregTech#533]
Hi, 
bug or problem with AE2 autocrafting for tools, ex : wrench, iron_bar, ... but don't test yet for autocrafting machines

Error message : 
`[Client thread/INFO] [minecraft/GuiNewChat]: [CHAT] Error: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.lang.NullPointerException`

Forge: 
14.23.5.2860
GregTech CE: Unoffcial 2.0.4-beta
GTFO 1.0.1
GregiMultiblocks 1.0.2
AE2 : appliedenergistics2-trousers_edition-rv6-stable-7-v49t-texture-hotfix.jar
LazyAE2 latest
AE2FC latest
AE2WTlib latest
Wireless Crafting Terminal 1.12.2-3.12.97
AE Additions 1.3.4

Bug on Solo & Multi

**Comment by kumquat-ir** [comment]
Can you send your `latest.log`?

**Comment by Castanea43** [comment]
Yes, it's a big file but search with my pseudo on Discord : NagaViP3R
Have a look on the end line ~18318
https://uptobox.com/glrk1pw6qppa

**Comment by Castanea43** [comment]
Problem resolved with GTCEu 2.0.5
