### ISSUE TITLE
[Suggestion] Allow Coke Oven Hatches to be shared between multiblocks

### ISSUE THREAD

**Issue by DStrand1** [GregTechCEu/GregTech#557]
#544 removed the ability for Coke Oven Hatches to be shared by multiple Coke Ovens, since the Hatch would just choose one controller and only work for it. I suggest that we allow them to share again, and fix the Hatches selecting only one controller

**Comment by DStrand1** [comment]
Sorry sweaty but your issue is stale XD

**Comment by htmlcsjs** [comment]
🤨
