### ISSUE TITLE
[Suggestion] Folding ingots, plates and other in heap

### ISSUE THREAD

**Issue by SpeeeDCraft** [GregTechCEu/GregTech#558]
**Is your feature request related to a problem? Please describe.**
It's beautiful.

**Describe the solution you'd like**
A feature in which you can stack gears / plates / ingots and more in heaps as shown in the screenshot.

**Additional context**
![image](https://user-images.githubusercontent.com/52341158/150636477-05861a52-a350-4dd3-9659-54b13ea27580.png)

Why did I write this here and not just install the Charset mod? Because installing the Charset mod greatly increases the launch time of the game, especially with GT, which has a lot of different elements that can be folded. Implementing this in GT itself would be a cool feature.

**Comment by Regian24** [comment]
wasnt this a thing in GT6

**Comment by Syrcan** [comment]
Closing as this is an old issue and there was no motivation to implement it.
