### ISSUE TITLE
[1.12.2][Crash] Startup crash if SuperMartijn642sCoreLib is installed

### ISSUE THREAD

**Issue by accessdenied0** [GregTechCEu/GregTech#560]
**Describe the bug**
Conflict with SuperMartijn642sCoreLib

**Versions**
Forge: 14.23.5.2860
GTCE: 1.12.2-2.0.6-beta
Mod crashes with: SuperMartijn642sCoreLib 1.0.16a-mc1.12

**Steps To Reproduce**
1) I did install: Rechiselled with all mods: SuperMartijn642sCoreLib 1.0.16a-mc1.12 and supermartijn642configlib-1.0.9-mc1.12
2) Started the game: It crashed in Pre-Initialization Phase, 30-60secs in the Screen. 

**Expected behavior**
Game starts up

**Additional context**
The game seems to cause an injection issue with SuperMartijn642sCoreLib causing it to crash. [I liked the issue here.](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/issues/7) (Crash-Log is over there)

**Comment by Syrcan** [comment]
This appears to have been resolved.
