### ISSUE TITLE
How do I change the texture?

### ISSUE THREAD

**Issue by MrKono** [GregTechCEu/GregTech#573]
I used the wiki as a reference to add the original material, but I can't change the texture. (Always like Aluminum, not like Copper or Chrome). Is ".iconSet()" unfinished or does the wiki describe it differently?

Version
gregtech-1.12.2-2.0.6-beta
CraftTweaker2-1.12-4.1.20.673

**Comment by m2r1k5** [comment]
Try using lowercase for the iconSet() string (`"shiny"` instead of `"SHINY"`).
This bug has been reported earlier and is being worked on

**Comment by MrKono** [comment]
I see.
Thank you very much.
