### ISSUE TITLE
[BUG] Unable to form any Large Turbine in multiplayer

### ISSUE THREAD

**Issue by LunaFreyjaNox** [GregTechCEu/GregTech#589]
**Describe the bug**
I try to build Large plasma turbine, but you can't built with terminal, and if you manualy built it, your turbine dosen't work.

**Versions**
Forge: 14.23.5.2860
GTCE: 2.1.0 beta
Custom modpack

**Setup**
Playing in multiplayer
Existing world

**Steps To Reproduce**
1) Build Large Plasma turbine or other Large Turbine

**Screenshots**
[https://imgur.com/SX2QPMc](url)

**Additional context**
This problem seems to take place only a multiplayer,
and seems to have appeared since the 2.1.0 update, moreover, if you put any Turbine controller in survival mode, it drops after a few seconds and another copy of the block is duplicated in the inventory

**Comment by ALongStringOfNumbers** [comment]
This should have been fixed in #582 which is included in the release of 2.1.1.
