### ISSUE TITLE
[Suggestion] Crafttweaker method for adjusting the hardness of the block

### ISSUE THREAD

**Issue by SpeeeDCraft** [GregTechCEu/GregTech#594]
**Is your feature request related to a problem? Please describe.**
In TFC, the stone blocks have a very high hardness index, which is why GT picks and GT mining hammers dig the TFC rock for too long. I would like to have a hardness setting for GT ore using Crafttweaker.

**Describe the solution you'd like**
Have a ore hardness setting via crafttweaker.

**Comment by brachy84** [comment]
You can set block hardness already with crafttweaker https://docs.blamejared.com/1.12/en/Vanilla/Blocks/IBlockDefinition

**Comment by SpeeeDCraft** [comment]
> You can set block hardness already with crafttweaker https://docs.blamejared.com/1.12/en/Vanilla/Blocks/IBlockDefinition


Yeah, I get it, it solves my problems.
