### ISSUE TITLE
[Suggestion]Add option to convert RF/FE to EU

### ISSUE THREAD

**Issue by LunaFreyjaNox** [GregTechCEu/GregTech#601]
**Is your feature request related to a problem? Please describe.**
add an option to convert RF/FE to EU via the transformer, the input of the transformer is used as an input for a cable carrying RF/FE

**Describe the solution you'd like**
Use transformer device to convert RF/FE to EU, but with low ratio (10 RF to 1 EU),

**Additional context**
You can convert EU to RF/FE, why you can't reverse this

**Comment by DStrand1** [comment]
Added in v2.1.2
