### ISSUE TITLE
[BUG] Chlorine dupe in part of PBI Process

### ISSUE THREAD

**Issue by m2r1k5** [GregTechCEu/GregTech#623]
The offending part is the following chain of reactions:
1 Benzene + 2 Chlorine -> 1 Chlorobenzene + 1 HCl
1 PhCl + 2 Nitration Mixture -> 1 2-Nitrochlorobenzene + 1 Dil. H2SO4
1 2-NCB (+ 1/9 Cu) -> 1 3,3-Dichlorobenzidine
1 3,3-DCB + 2 Ammonia -> 1 3,3-Diaminobenzene + 2 HCl
therefore, giving 3 Cl when we started with 2.

**Comment by pablocnvs** [comment]
The step that needs to be fixed is the third, since you need 2 molecules of the 2-NCB
