### ISSUE TITLE
[Suggestion] Floppa easter egg

### ISSUE THREAD

**Issue by ThePansmith** [GregTechCEu/GregTech#632]
**A clear and concise description of what the problem is.**

There is no floppa easter egg, this is a surprise given the state of the discord.

**Describe the solution you'd like**
Naming a cat one of the following names would replace its texture with a floppa skin.

Names:
- Floppa 
- Caracal
- Flop
- [Gregory ](https://genius.com/artists/Floppa) 

**Additional context**
Floppa

**Comment by htmlcsjs** [comment]
flop :trollface:

**Comment by ThePansmith** [comment]
> flop :trollface:

![5211520-zencbvez-v4](https://user-images.githubusercontent.com/70342772/153264595-f70a6f31-c6d1-4839-bda4-ec658abc468f.jpg)

**Comment by tolyabi228** [comment]
FlOPPa alloy hint in achievement
>my first github comment lol

**Comment by htmlcsjs** [comment]
FlOPPa in CEu when :trollface:

**Comment by Syrcan** [comment]
floppa

**Comment by ThePansmith** [comment]
flop

**Comment by brachy84** [comment]
flop
