### ISSUE TITLE
[BUG] Processing Array doesn't do parallelization in certain condition

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/GregTech#642]
**Describe the bug**
Processing Array sometimes only works with single machine put inside its interface.
After the experiment, I found that recipes with fluid inputs has higher chance to cause this problem. 

**Versions**
Forge: 14.23.5.2860
GTCE: 2.1.1-beta
_Modpack:_ GregTech Expert 2 V0.13.3

**Setup**
Multiplayer

**Steps To Reproduce**
I'm sorry I can't reproduce it in the creative mode so I'll post a video in the survival mode
https://user-images.githubusercontent.com/39122497/153704994-0d4bf1fc-9ac0-4f1a-b216-7e0c45486f32.mp4
HV output bus is empty (I forgot to include it in the vid)
1) setup your Processing Array with more than 1 machine inside the Machine Access Interface
2) power it and feed it ingredients through ME interface
3) problem appears

**Expected behavior**
it runs at normal speed

**Comment by Quarri6343** [comment]
After hours of experiments, I found this bug is reproduceable in a new world, so let me rewrite the description

**Describe the bug**
If you automate the Processing Array with the Volumetric Interface, in certain condition,
the Processing Array will be broken and won't do any parallel job unless you create a new world.
 
**Versions**
Forge: 14.23.5.2860
GTCE: 2.1.1-beta
Modpack: GregTech Expert 2 V0.13.3

**Setup**
SinglePlayer or Multiplayer

**Steps To Reproduce**
1. Create a new world
2. Setup a new Processing Array with 16 HV chemical reactors inside the Machine Access Interface
3. Power it with IV power
4. Attach the buffer from Volumetric Flask mod to the input hatch of the Processing Array directly, then connect the input bus and the buffer with gregtech item pipes.
5. Attach the Volumetric Interface from the same mod to the buffer directly
6. Encode a pattern that uses both item and fluid as ingredient with ME system.
For an example: an Epoxy Resin Sheet + Gold foil x 8 + 250mb volumetric flask ( sulfuric acid ) x 2=>an Epoxy Circuit Board
7. Put your pattern inside the Volumetric Interface you placed
8. run an auto crafting job with ME system
9. the Processing Array do nothing unless you remove 15 chemical reactors from the Machine Access Interface
10. This problem lasts forever (you can't do manual crafting either at this point)

if you are having trouble reading this long procedure, please do the following setup or watch the video in the previous comment
![2022-02-12_22 25 52](https://user-images.githubusercontent.com/39122497/153716709-373ffc7a-542d-47c0-8a56-98317a8fec9c.png)

**Expected behavior**
Processing Array do parallel crafting

**Comment by Syrcan** [comment]
Took a little bit of time investigating, and that's something that should be fixed in the current PR #329 ([this line change](https://github.com/GregTechCEu/GregTech/pull/329/files#diff-e4cca3bc71a500f62832bba51b2996711688ab368617f36f0e3b7f9ccd1dd697R352)), which we want to merge for next release.

**Comment by Quarri6343** [comment]
Thanks you! I was just worrying that that PR actually fixes everything or not
