### ISSUE TITLE
[BUG] It is not possible to recycle materials that are marked as metal in TFC

### ISSUE THREAD

**Issue by SpeeeDCraft** [GregTechCEu/GregTech#673]
**Describe the bug**
Using CT, you can give any item metal units from TFC. But if you do this, recipes from GT with their use stop working.

**Versions**
Forge: 2860
GTCEu: 2.1.1 
_Modpack:_ TFG R3.1.1v2

**Setup**
Playing Solo/Multiplayer/**Both**

**Steps To Reproduce**
1) Install TFC, GT, Crafttweaker
2) With the help of crafttweaker, issue units of metal (for example, copper dust), (I attached the script below).
3) Try to recycle this dust.

**Expected behavior**
The dust had to be recycled.

**Screenshots**
Without CT script:
![image](https://user-images.githubusercontent.com/52341158/154943562-c66ba84f-71be-4ab0-b597-5a5c6d377164.png)

With CT script(no proccess):
![image](https://user-images.githubusercontent.com/52341158/154941831-bfe3500c-82bf-4637-8b52-d48efb254088.png)

Script:
![image](https://user-images.githubusercontent.com/52341158/154943297-916ab0fa-c915-4b65-a4f6-8ccf773502c9.png)

**Comment by Xikaro** [comment]
the problem is the same in GTCEu: 2.1.4

**Comment by SpeeeDCraft** [comment]
The error was described a little incorrectly, and this error requires more in-depth testing. As soon as we find out exactly what the problem is, we will report it again.
