### ISSUE TITLE
[BUG] The Energy Converter is broken

### ISSUE THREAD

**Issue by tier940** [GregTechCEu/GregTech#692]
**Describe the bug**
it memorizes the original rotation and doesn't work after you rotate it with a wrench.

**Versions**
Forge: 14.23.5.2860
GTCE: gregtech-1.12.2-2.1.2-beta.jar
_Modpack:_ GregTech Expert 2

**Setup**
Playing: Both
World: New and Generated

**Steps To Reproduce**
1) See the video

**Expected behavior**
Allowing for rotation.

**Screenshots**
https://user-images.githubusercontent.com/11691836/155722960-a0278bed-a816-48cd-909b-148230f0f129.mp4

**Comment by ChromaPIE** [comment]
Reproduced. Converters always feeds the machine adjacent to its north side, regardless of where the actual output is.

**Comment by tier940** [comment]
I've updated to a newer version (rv6-stable-7-extended_life-v50f), but it hasn't fixed the problem...
