### ISSUE TITLE
[Question] Creating Material + Tool crafting

### ISSUE THREAD

**Issue by Shazuli** [GregTechCEu/GregTech#693]
**Hey**

So I would like to create some extra complimentary resources for Botania. I have the items I want loaded now, but I don't know how to connect them to the existing Botania items. Manasteel- and Terrasteel Ingots got automatically added to the material tree, but the last metal Elementium will not. And then there's that it's missing its translation string giving it the name "material.terrasteel Dust" or "material.manasteel Plate".

When I try to add a recipe that uses a GT tool it will damage the tool and then make it invalid for crafting again. Default vanilla Gregtech recipes works fine but all other recipes I add has this problem.
```
recipes.remove(<botania:managlasspane>);

recipes.addShaped(<botania:managlasspane> * 2,[
    [<ore:craftingToolSaw>,<botania:managlass>]
]);
```

**Comment by brachy84** [comment]
First of all, it's better to ask those questions on [Discord](https://discord.com/invite/bWSWuYvURP).
So as far as i understand you added Manasteel and Terrasteel materials, but you don't want the ingots? You need to remove them manually via crafttweaker.
I don't understand your problem with Elemntium.
Unfortunatly, default tool ore dicts don't work correctly. Either use the normal item id, or add new ore dicts to each tool and use those
