### ISSUE TITLE
[BUG]  The prospector does not work in GC dimensions

### ISSUE THREAD

**Issue by SpeeeDCraft** [GregTechCEu/GregTech#694]
**Describe the bug**
The prospector does not work in other dimensions

**Versions**
Forge: 2860
GTCE: 2.1.2
_Modpack:_ TFG R3.1.2 Lite

**Setup**
Playing Solo/Multiplayer/**Both**

**Steps To Reproduce**
1) Create configuration files so that ores are generated, for example, on the moon from the GC mod.
2) Enter the world and fly to the moon.
3) Results.

**Screenshots**
![image](https://user-images.githubusercontent.com/52341158/155730098-fe22707a-0b7c-4f71-94b5-e06587f4859d.png)

**Comment by brachy84** [comment]
Does it happen in all "other" dimensions or just gc dimensions?

**Comment by SpeeeDCraft** [comment]
I'll check it out and write about it

**Comment by SpeeeDCraft** [comment]
Prospector does not work only in GC(and galaxt space) dimensions.

**Comment by ALongStringOfNumbers** [comment]
Closing this as it should be fixed as of #1015
