### ISSUE TITLE
[BUG/QUESTION] Ores from cutom StoneTypes don't have processing recipes

### ISSUE THREAD

**Issue by SpeeeDCraft** [GregTechCEu/GregTech#696]
**Describe the bug**
Ores that were created using StoneTypes are not processed in mechanisms.

**Versions**
Forge: 2860
GTCE: 2.1.2
_Modpack:_ TFG R3.1.2 Lite
_Addons:_ DevTech 2.0.2

**Setup**
Playing Solo/Multiplayer/**Both**

**Expected behavior**
The ores had to be processed.

**Screenshots**
Default ore:
![image](https://user-images.githubusercontent.com/52341158/155731561-a1f5970c-5ac7-46f0-8ee2-434cfa75dad5.png)
Generated stonetype ore:
![image](https://user-images.githubusercontent.com/52341158/155731656-b5176096-612c-4f9f-9314-ee8837094c43.png)

**Additional context**
Maybe I did something wrong. Maybe I need to add some flag, I don't rule it out. If so, please explain how to make the generated ores processed in macerators and the like.

Script file: https://github.com/SpeeeDCraft/TerraFirmaGreg-1.12.2/blob/TFG-Lite-R3.0/TFG-LITE/scripts/GregTech/CustomMaterials.zs

**Comment by brachy84** [comment]
I think it is DevTechs fault

**Comment by brachy84** [comment]
According to you config, the block will never drop, so it doesn't need recipes. Correct me if i'm wrong

**Comment by SpeeeDCraft** [comment]
I have changed the configuration that is responsible for this. Ores began to drop in the rocks I needed. But there is still no recycling.

**Comment by SpeeeDCraft** [comment]
This is not a mod error, so I will close it.

https://discord.com/channels/701354865217110096/913431960397955092/969440236822200360
