### ISSUE TITLE
[QUESTION/BUG?] Ores are not processed in steam  macerators.

### ISSUE THREAD

**Issue by MrKono** [GregTechCEu/GregTech#699]
Steam Macerator / High Pressure Steam Macerator cannot process XX Ore and Crushed XX Ore.
Steam Grinder can  process XX Ore and Crushed XX Ore.
Other steam machines can run their recipes.

Are these bugs or a specification change? 

Version
2.1.2 & 2.1.3

Playing Solo

(I use translation site.)

**Comment by Syrcan** [comment]
Thank you for the issue.
The fix is in #700.

**Comment by MrKono** [comment]
OK.
Thank you for your support
