### ISSUE TITLE
[BUG] Startup fail with certain mods when changing oredicts

### ISSUE THREAD

**Issue by tracer4b** [GregTechCEu/GregTech#702]
**Describe the bug**
On CEu versions 2.1.2 and 2.1.3, starting Minecraft will fail due to errors with mods (Simply Jetpacks 2, Ender IO, perhaps more) complaining about removed oredict entries. This doesn't happen with version 2.1.1.

**Versions**
Forge: 14.23.5.2860
GTCE: 2.1.2 - 2.1.3
_Modpack:_ nomi-ceu, import attached
_Addons:_ GCYM 1.1.1

**Steps To Reproduce**
1) Remove an offending ingot from an Oredict entry
2) Launch the game
3) Crash happens in loading step 4

**Expected behavior**
no crash

**Additional context**
When loading Simply Jetpacks 2, the following crash occurs: [crash-2022-02-25_20.47.19-client.txt](https://github.com/GregTechCEu/GregTech/files/8146729/crash-2022-02-25_20.47.19-client.txt
When SJ2 is appeased, Ender IO errors with this screeen: ![image](https://user-images.githubusercontent.com/61507029/155845699-472c0861-bf5d-48c1-9828-8016a4b0d4de.png)
Neither issue happens when loading with CEu version 2.1.1 and GCYM version 1.1.0, but it does happen with CEu versions 2.1.2 and 2.1.3 and GCYM version 1.1.1.

All nomi-ceu files: [nomi-ceu-0.6.3-bkup.zip](https://github.com/GregTechCEu/GregTech/files/8146726/nomi-ceu-0.6.3-bkup.zip)
Oredict script: [_oreDict.zs](https://github.com/GregTechCEu/GregTech/files/8146741/_oreDict.txt)

**Comment by Syrcan** [comment]
Was this fixed?

**Comment by tracer4b** [comment]
It was my fault, not CEu's
