### ISSUE TITLE
[Suggestion] JourneyMap Integration

### ISSUE THREAD

**Issue by ChromaPIE** [GregTechCEu/GregTech#722]
**Describe the solution you'd like**
So that players can ''tag'' veins from surface rocks by creating a JourneyMap waypoint with proper vein name and the waypoint color same as the material's

Would be better with a custom icon, just like what Mineral Tracker mod does.

**Comment by Syrcan** [comment]
Let's leave that task to addon devs. I don't think this belongs to GregTech itself.
Good feature though, would love to see it in 1.12.
