### ISSUE TITLE
[BUG]many Multiblocks formation bugs

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/GregTech#758]
**Describe the bug**
・you can form the Steam Oven with 9 Steam hatches because there is no max number of it
・you can form the Central Monitor with so many Energy Hatches because the number of the solid machine casing is limited in very low number (however the there should be a limit on the Energy Hatch side)
・The Fusion Reactor says "Minimum: 0 output hatch"
it is weird because the input hatch is Minimum 2 and you can't run it without the output hatch
・You cannot form the fusion reactor with the UHV Energy Hatch because it is hardcoded
https://github.com/GregTechCEu/GregTech/blob/6fdcb793cb1f2875687dfcce9eb4d96244a3ed5a/src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFusionReactor.java#L108-L111

**Versions**
Forge: 14.23.5.2860
GTCEu: gregtech-1.12.2-2.1.4-beta.jar
Modpack: GregTech Community Pack

**Screenshots**
![キャプチャ1168](https://user-images.githubusercontent.com/39122497/157150692-9cbf3e7a-5024-4c93-aee3-e303a8fafe5b.PNG)
![キャプチャ1169](https://user-images.githubusercontent.com/39122497/157150703-ac4c407b-169a-48f1-8123-143ef90d4a24.PNG)
![キャプチャ1170](https://user-images.githubusercontent.com/39122497/157151625-19e43c37-9285-4e7e-9c5b-c4a52a9d094d.PNG)

**Comment by ALongStringOfNumbers** [comment]
Not forming the Fusion Reactor with a UHV energy hatch is intended. The Fusion Reactor allows for three tiers of energy inputs for an MK1, those being LuV, ZPM, and UV. ZPM and UV for an MK2, and UV for an MK3. These energy inputs contribute to the heat capacity of the structure, giving different amounts of heat per tier of the controller.

**Comment by Quarri6343** [comment]
`Not forming the Fusion Reactor with a UHV energy hatch is intended`
ok
how can I overclock the Fusion Reactor MK III as written in the tooltips?
![キャプチャ1172](https://user-images.githubusercontent.com/39122497/157153778-6ea11b2e-73f5-45a0-a6b3-a3bbc256bdde.PNG)

` it was decided to remove the minimum number of output hatches/buses in all multiblock structures in the voiding rework PR`
ya I know
but why not display nothing just like the output bus in the other multiblocks?
![キャプチャ1173](https://user-images.githubusercontent.com/39122497/157154167-52597e4c-3c6c-4d1a-b074-d6397c028a38.PNG)

**Comment by ALongStringOfNumbers** [comment]
> `Not forming the Fusion Reactor with a UHV energy hatch is intended` ok how can I overclock the Fusion Reactor MK III as written in the tooltips? ![キャプチャ1172](https://user-images.githubusercontent.com/39122497/157153778-6ea11b2e-73f5-45a0-a6b3-a3bbc256bdde.PNG)

By providing 4A of UV, so that the multiblock will overclock. Like the other multiblock structures, providing the fusion reactor with enough Amps of a tier of power to equal the next tier will make the recipe overclock. There is no special behavior despite being a somewhat special multiblock. In addiiton, not all MK3 recipes take UV power in the first place, so those recipes would already be overclocking with the UV hatches

**Comment by Quarri6343** [comment]
oh I can now understand it
thank you!

**Comment by Quarri6343** [comment]
・you can form the Ore Drilling Rig with many Input hatches because there is no max number of it
the Output Hatch of the Fluid Drilling Rig is fine (Maximum 1)
![キャプチャ1191](https://user-images.githubusercontent.com/39122497/158010064-fd0d105f-53d6-43fd-af7a-7eeb573415d5.PNG)
