### ISSUE TITLE
[BUG] the(every?) Disassember from the other mods disassembles recipes using GT tools into the neutronium tools

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/GregTech#759]
**Versions**
Forge: 14.23.5.2860
GTCEu: gregtech-1.12.2-2.1.4-beta.jar
Modpack: GregTech Expert 2

**Setup**
SP/MP
New world generated

**Steps To Reproduce**
1. Place down the Disassembler from any mod like OpenComputers
2. Disassemble an item which has tools in its recipe

**Video**
https://user-images.githubusercontent.com/39122497/157155533-6590864e-a777-4541-b139-5bdede326cca.mp4

**Expected behavior**
Disassembler disassembles recipes using tools into the tool of very cheap variant or output nothing

**Comment by Rongmario** [comment]
This cannot be reliably fixed on our side, use OpenComputer's `settings.conf` and edit `disassemblerInputBlacklist` to blacklist GT tools.

**Comment by Quarri6343** [comment]
ok
Thanks for your reply
I have already disabled the disassembler itself
