### ISSUE TITLE
[Question] about Ender Fluid Link Cover

### ISSUE THREAD

**Issue by ChromaPIE** [GregTechCEu/GregTech#761]
In recent gameplay I decided to completely replace AE2 Fluid P2Ps and storage buses with EFLink Covers to cull the cable complexity, obviously it's kinda struggling, since it costs way too many materials and much time than a simple piece of P2P, however I ended up crying it doesn't worth it.

For gadgets used for tranfering, the number one priority is ought to be the rate it transfers, and the ability of interdimensionality and distance limitlessness should be put into the second place, this makes sense to why Pump Covers cost more as its variant speeds up fluid transfer. This is literally the reason why my fellas and I found it disappointing, no matter how wireless it is, the _8000mB/t_ still makes it less considerable, and less of an amazing feature especially when you once believed that it definitely kicks out Ender Storage mod.

8000mB/t, an awkward number. Fairly enough for pre-HV, during which there's not even an EFLink, but once you get HV, when you managed to set up those large steam boilers and turbines with extremely high producing/draining rate, you'll realize yourself exhausting these tiny little covers. Now, 8000 turns out to be not enough for transfering fluids around the base, remote Drilling Rigs and Air Collectors can take advantage of it though, but it would be weird for this seemingly powerful gadget cuz it shouldn't have been designed just for Rigs and Collectors. Yes it would be of great use in pure Greg, but, well, pure Greg...

So here's my idea. Simply editing the rate or make it a MV or even LV thing is bad, cuz both can't solve what I've mentioned above. I suggest adding an extra slot in its GUI where you can enhance the EFLC, with **pumps**, each increases the transfer rate by the pump's capability, or it can be other rules once reasonable, the core idea is to make its transfer rate upgradable, instead of stucking at an awkward number throughout the whole progression. Interdimensionality, distance limitlessness, that's impressive, make it last from HV to MAX plz.

**Comment by Quarri6343** [comment]
you can always use the Central Monitor
Although it has no interdimentionality, it can transfer INFINITE amount of the fluid per tick wirelessly
I have a suggestion to partially disable it because it makes the ender fluid link cover useless
https://github.com/GregTechCEu/GregTech/issues/714

**Comment by ChromaPIE** [comment]
> you can always use the Central Monitor Although it has no interdimentionality, it can transfer INFINITE amount of the fluid per tick wirelessly I have a suggestion to partially disable it because it makes the ender fluid link cover useless #714

Covers take no block spaces but only one machine side, not to mention that I can even attach one to where the wire/cable is, it's 100% space efficient, even a smallest monitor is way too huge, and it drains energy. EFLC, if don't count that 8000mB/t in, is undoubtedly a godsend. The transfer rate is the one and only fatal shortcoming.

**Comment by Quarri6343** [comment]
Wdym?
You can attatch the Wireless Digital Interface Cover just like EFLC, of cource it takes no block spaces
All you need to do is replace your EFLCs with that cover and build a Central Monitor somewhere in your dimention to link those covers

`it drains energy`
is 5EU/t per screen too much for you...?

**Comment by ChromaPIE** [comment]
> You can attatch the Wireless Digital Interface Cover just like EFLC, of cource it takes no block spaces
> All you need to do is replacing your EFLCs with that cover and build a Central Monitor somewhere in your dimention to link those covers

Well in case I didn't make that clear, imagine you got a titanium boiler and a Large Steam Turbine, with a water source, say the Infinity Water Cover, and several EFLCs, if with fast enough transfer rate, you can literally make everthing running. No extra pipes, no Monitors or any extra multiblocks required. Energy output not considered, there are only three multiblocks, nothing else. It's insane to build a 5x2 monitor and stuff only to make things wireless.

**Comment by Quarri6343** [comment]
` It's insane to build a 5x2 monitor and stuff only to make things wireless.`
I don't think so
If you make a single cheap big monitor (5x2 is too small to automate things), you can make your almost entire base wireless
not only the turbine and the boiler, your LCR arrays, your passive EBFs, ...etc
I think it is better than spamming expensive EFLCs everywhere

`there are only two multiblocks`
If your base only have two multiblocks, you are playing the wrong way i guess...

**Comment by ChromaPIE** [comment]
Okay you didn't actually get what this issue is all about.
