### ISSUE TITLE
[BUG]Game crashes when someone breaks the Central Monitor while you are looking at it

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/GregTech#766]
**Describe the bug**
#765 has the `NullPointerException: Updating screen events` error
However this bug has the `NullPointerException: Rendering screen` error
So I separate these as two bug reports

**Versions**
Forge: 14.23.5.2860
GTCEu: gregtech-1.12.2-2.1.4-beta.jar
Modpack: GregTech Expert 2

**Setup**
SP
New world generated

**Steps To Reproduce**

https://user-images.githubusercontent.com/39122497/157264257-b939564c-b8da-4f13-8fb8-5ce1f51759ad.mp4

**Crash Report**
[crash-2022-03-08_23.49.01-client.txt](https://github.com/GregTechCEu/GregTech/files/8207230/crash-2022-03-08_23.49.01-client.txt)

**Comment by Quarri6343** [comment]
thanks 👍

**Comment by Yefancy** [comment]
thanks for debug
