### ISSUE TITLE
[BUG] EV 4A Dynamo Hatch acts as an Energy Hatch

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/GregTech#770]
**Describe the bug**
Like he said,
https://github.com/GregTechCEu/GregTech/pull/639#issuecomment-1060615843
the EV 4A Dynamo Hatch is an Energy Hatch

**Versions**
Forge: 14.23.5.2860
GTCEu: gregtech-1.12.2-2.1.4-beta.jar
Modpack: GregTech Expert 2

**Screenshots**
![2022-03-09_15 59 14](https://user-images.githubusercontent.com/39122497/157390599-9c56235b-9a86-44bb-bee4-3bc2c55d516e.png)

**Comment by DStrand1** [comment]
Fixed in 869647b1e5bbfee721e0c81dbb5876afd41ee8a2

**Comment by Quarri6343** [comment]
thanks I didn't realize that
