### ISSUE TITLE
[BUG] Game Crashes with the Recipe Chart App

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/GregTech#780]
**Describe the bug**
when you try to refer the recipe of the wood log in the Recipe Chart App, the game immediately crashes

**Versions**
Forge: 14.23.5.2860
GTCEu: gregtech-1.12.2-2.1.4-beta-1d04a44b84c5d5189afeb1dc86787f507770a391-patched.jar
Modpack: GregTech Expert 2

**Setup**
SP
New world generated

**Steps To Reproduce**

https://user-images.githubusercontent.com/39122497/157797569-58870984-9836-460a-a10a-02fd37458c08.mp4

**Crash Report**
[crash-2022-03-11_12.31.37-client.txt](https://github.com/GregTechCEu/GregTech/files/8228860/crash-2022-03-11_12.31.37-client.txt)

**Comment by ALongStringOfNumbers** [comment]
I cannot repeat this crash, and the crash report linked is not working. Can this issue be repeated in the latest development environment?

**Comment by Quarri6343** [comment]
it cannot be repeated in the latest development environment
however it still happens in the modpack so it may be caused by the other mod
I have to wait for the next version to decide whether close this issue

**Comment by Quarri6343** [comment]
probably got fixed
