### ISSUE TITLE
[BUG] Monitor Screen GUI dupes any item in certain condition

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/GregTech#782]
Describe the bug
Remember to press home button twice to close the GUI or #765 happens
Also, you have to shift left click duped items in your inventory or the items willdisappear

**Versions**
Forge: 14.23.5.2860
GTCEu: gregtech-1.12.2-2.1.4-beta.jar
Modpack: GregTech Expert 2

**Setup**
SP/Creative Mode?
New world generated

**Steps To Reproduce**

https://user-images.githubusercontent.com/39122497/157887792-eea7d84a-23ca-4c60-957b-b6015d39395a.mp4

**Comment by Quarri6343** [comment]
you can do the same thing with the Crafting Station
this can be a much easier option
![キャプチャ1195](https://user-images.githubusercontent.com/39122497/157906648-ccb1adcf-8768-4de6-91b8-f6e0d555300d.PNG)
![キャプチャ1196](https://user-images.githubusercontent.com/39122497/157906652-26827e33-f3c3-4556-8342-54c76b6897d4.PNG)

**Comment by ALongStringOfNumbers** [comment]
This issue appears to be fixed in the latest version, although there is still some weirdness in interacting with the crafting station. Please comment if you manage to reproduce the bug, and we will reopen this issue.
