### ISSUE TITLE
[Question] When I use Shadow of Greg with GTCEu I get this crash, why isnt it compatible and is it even needed? (Is the content of shadow of greg inside GTCEu? or at least particially)

### ISSUE THREAD

**Issue by MrProton657** [GregTechCEu/GregTech#783]
crash report: https://pastebin.com/y36Wbqzq

**Comment by htmlcsjs** [comment]
SoG is incompatible with GTCEu, same with any existing CE addons that didn't get updated. However, it's not detrimental as most of SoG's addons have been integrated into ceu

**Comment by MrProton657** [comment]
Thanks, thats what I wanted to know.

**Comment by ALongStringOfNumbers** [comment]
As said above, SoG is incompatible with GTCEu. However, almost all of the content has been merged into GTCEu, bar the single block Naquadah generators.
