### ISSUE TITLE
GUI improvements

### ISSUE THREAD

**Issue by Xikaro** [GregTechCEu/GregTech#784]
**Is your feature request related to a problem? Please describe.**
Is it possible to add logic and GUI like in Thermal Expansion? I'm talking about the possibility of configuring the inputs and outputs separately, so that you can, for example, automate with ae2, since at the moment single-block machines do not allow picking up and pushing objects from one side

**Describe the solution you'd like**
![configuracion-thermal-expansion_-_3](https://user-images.githubusercontent.com/55663835/157995410-6e7ae2d3-a1ad-4054-91ce-8da25a4192bc.PNG)

**Additional context**
I would really like to have similar functionality in GTCEU, as it is very convenient

**Comment by Syrcan** [comment]
The ability to have input and output separate already exists. This is done by placing covers, such as Conveyor Module and Pump. They can be configured to import or extract, accept filters, and more.
For automation with AE2, you can use the Screwdriver on the output side to enabled input through it (this is a bit of a hidden feature but it will be present as a tooltip soon).

As for GUI tabs, we have already discussed them internally, and so far we are against implementing them.
Machines are already extremely modular thanks to covers.

**Comment by Xikaro** [comment]
Thank you very much, very comprehensive answer.
