### ISSUE TITLE
[BUG] Vanilla ladder are cheaper without an assembler, and other inconsistencies

### ISSUE THREAD

**Issue by LemADEC** [GregTechCEu/GregTech#791]
**Describe the bug**
In crafting table, you get 3 ladders from 7 sticks. When using an assembler, you only get 2 from using 7 sticks.
Vanilla boats have no recipes in assembler. I suggest 3 planks and 2 sticks.
Vanilla sign has the same price in assembler. I suggest 1 plank and 1 stick per sign.
Vanilla wooden door has the same price in assembler. I suggest 3 planks to get 2 doors.
Vanilla stairs have the same price in assembler. I suggest 6 slabs to get 4 stairs, as found in the Quark mod.

**Versions**
Forge: 14.23.5.2860
GTCEu: 1.12.2-2.1.4
Other mods: jei_1.12.2-4.16.1.302 & CodeChickenLib-1.12.2-3.2.3.358

**Setup**
_Does this issue happen on Singleplayer, a Server, or both_: both
_Does this issue happen on a newly generated world_: yes

**Steps To Reproduce**
1) check recipes in JEI

**Expected behavior**
More outputs or less inputs when using assembler compared to crafting table recipes.

**Comment by Quarri6343** [comment]
```
Expected behavior
More outputs or less inputs when using assembler compared to crafting table recipes.
```
Since wooden products have recycling recipes,
tweaking the assembler recipes will cause https://github.com/GregTechCEu/GregTech/issues/756 happen again
I suggest leaving these recipe until the recycle system rework

**Comment by TechLord22** [comment]
#1581 fixes the issue with ladders, and adds boat assembler recipes. 

The other items listed are intended. The assembler does not have to offer a higher yield than alternatives, and the recipes exist in order to add a method of automating them without requiring mods such as AE2.
