### ISSUE TITLE
[Suggestion]Outputing non-consumed item

### ISSUE THREAD

**Issue by iijunxz** [GregTechCEu/GregTech#794]
**Is your feature request related to a problem? Please describe.**
When i'm using Applied Energistics 2 to automatize producing, I found that machines like extruder need an extruder shape to change output, but AE2 can't change it by itself, that means it need multipie machines to put material into different shapes. 

**Describe the solution you'd like**
Add a button in GUI to switch whether to output non-consumed item into a new exportable slot.

**Additional context**
![图片](https://user-images.githubusercontent.com/38577322/158048637-acc7766a-4a2f-430b-8fd4-89c0d8c6b68d.png)
Just like this

**Comment by MadMan310** [comment]
make more machines :trollface:

**Comment by ChromaPIE** [comment]
Weird af. Making more machines isn't a big deal at all if you play it right.

**Comment by Quarri6343** [comment]
Building a Processing Array is better than making more machines
It can have many separated input buses so you can automate many recipes with different shapes with single extruder
