### ISSUE TITLE
Add compatibility

### ISSUE THREAD

**Issue by Maximnety** [GregTechCEu/GregTech#801]
Hello, I think you will agree that your mod is very complex, the same applies to automation, how about adding support for the Open Computers mod? Then, robots will be able to interact with the mechanisms, greatly simplifying the work with them and adding autocraft.

**Comment by Quarri6343** [comment]
[this mod](https://github.com/GregTechCEu/Gregification) will add supports for OpenComputers
however it is not released yet because everyone is busy on other projects i guess
