### ISSUE TITLE
[Suggestion]Facilitate Automation

### ISSUE THREAD

**Issue by Xikaro** [GregTechCEu/GregTech#820]
**Is your feature request related to a problem? Please describe.**

I would like to offer an example of facilitating the automatic processing of materials, using the example of an ore washing machine, which uses different configurations of circuit in the recipe, for the same type of ore

To automate via ae, this is difficult because when using ore dict export bus, the bus does not recognize the circuit configuration in the machine
![Screenshot_76](https://user-images.githubusercontent.com/55663835/159112579-b4def8f5-6328-4e87-859f-1089339b618e.png)
![Screenshot_75](https://user-images.githubusercontent.com/55663835/159112584-589f0c4e-74a1-48e6-8fd5-b284e1964244.png)
![Screenshot_74](https://user-images.githubusercontent.com/55663835/159112585-a44bacbf-0057-4c19-95d7-498ed5b10e76.png)
![Screenshot_77](https://user-images.githubusercontent.com/55663835/159112586-7e261170-d708-4fc6-abc7-cce33aaa5698.png)

**Describe the solution you'd like**

The solution to this problem can be the binding of different types of ore to a specific configuration of circuite.

For instance:
<ore:crushedGold> configuration 1
<ore:dustPurePollucite> configuration 2
<ore:dustImpureTungstate> configuration 3
(All names are taken randomly)

Similarly, in other machines where this problem occurs.

**Comment by Syrcan** [comment]
Here are how the Ore Washer recipes work:
Regular washing (with byproducts): water and configuration 1, or distilled water.
Quick washing (no byproducts): water and configuration 2.

I do not understand why the the oredict export bus is any relevant.

On a side note, the OreDict Export Bus from ExtraCells is considered to be extremely laggy. It kills the TPS. On public servers they ban it. I would highly recommend against using it.
