### ISSUE TITLE
[BUG] Cables lost the insulation stay hot forever in certain condition

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/GregTech#835]
**Describe the bug**
#567 makes the wire and the cable change color when overvolted
However, sometimes the uninsulated cable stays hot forever

**Versions**
master branch [3b1f165](https://github.com/GregTechCEu/GregTech/commit/3b1f1650c564c1c4852fa904d7355a7b1daabd40)

**Setup**
dev environment

**Steps To Reproduce**
1) prepare two cables (this bug does not happen with wires)
2) keep overvolting cables until one of the two cables lost insulation

**Clip**

https://user-images.githubusercontent.com/39122497/159531174-88b06230-68f4-4f49-9c34-83672e83efb4.mp4

**Comment by ALongStringOfNumbers** [comment]
This should have been fixed by #841, let me know if it was not and I will re-open the issue.
