### ISSUE TITLE
Automatization

### ISSUE THREAD

**Issue by Maximnety** [GregTechCEu/GregTech#837]
Hello, how about adding to multiblock mechanisms the possibility of using a redstone signal, a new input redstone hatch, instead of an integrated circuit. This will greatly simplify automation (although it won't change the situation much with AE2) since, it will not be necessary to make dozens of mechanisms for different purposes using different integrated circuits.

**Comment by Syrcan** [comment]
Integrated circuits are too essential to the recipe design to make this change.
