### ISSUE TITLE
[BUG] LV Solar Panel should require Laminated Glass instead of Tempered Glass

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/GregTech#843]
**Describe the bug**
LV Solar Panel is IV-LuV tier so it should require IV-LuV tier glass

**Versions**
master branch [3b1f165](https://github.com/GregTechCEu/GregTech/commit/3b1f1650c564c1c4852fa904d7355a7b1daabd40)

**Screenshots**
![キャプチャ1234](https://user-images.githubusercontent.com/39122497/159880126-cc4b971e-4dbb-4be3-b024-cbca50a59c5c.PNG)

**Comment by Syrcan** [comment]
Maybe yes... but solar cover... I am closing this to clean up the number of issues.
