### ISSUE TITLE
[BUG] When using the GT wrench to rotate the Ender Utilities block, the contents are emptied

### ISSUE THREAD

**Issue by KasumiNova** [GregTechCEu/GregTech#861]
**Describe the bug**
Using the GT wrench to rotate the Ender Utilities blocks, the contents are emptied.

**Versions**
Forge: 14.23.5.2860
GTCEu: 2.1.4-beta
_Modpack:_ [StarryNight Pray](https://github.com/Project-StarryNight/StarryNight_Pray)

**Setup**
_Does this issue happen on Singleplayer, a Server, or both_: Both
  _Does this issue happen on a newly generated world_: Both

**Steps To Reproduce**
1) Place a rotatable block of Ender Utilities.
2) Put something in, such as memory cards, items.
3) Rotate them with a GT wrench (electric or regular).
4) Open them and the contents disappear.

**Expected behavior**
This will result in unnecessary item loss for the player.

**Videos**
[Google Drive](https://drive.google.com/file/d/1AKoR06-R5Vicjk4nP6tprlPmmPj0WffJ/view?usp=sharing)

**Additional context**
The wrench of other mods does not cause this problem, I think it is a problem of GT.

**Comment by Preta-Crowz** [comment]
In additional, EnU blocks are not rotated right and always set the facing to north.
Also, it will sets Rotation from its NBT to 2.

But anyway, wrench will detect it as "rotated" and no longer work unless player tries to rotate it to other direction.

**Comment by Preta-Crowz** [comment]
![debugLog](https://user-images.githubusercontent.com/16697820/162556792-02b9d535-5183-49a7-9234-573285cfffeb.png)
It seems EnU storage has rotation on property and NBT both.

> In additional, EnU blocks are not rotated right and always set the facing to north. Also, it will sets Rotation from its NBT to 2.
> 
> But anyway, wrench will detect it as "rotated" and no longer work unless player tries to rotate it to other direction.

**Comment by Syrcan** [comment]
This looks more of a EnderUtilities problem with Forge wrench, as that's how our Wrench compat has been implemented iirc.
