### ISSUE TITLE
[Suggestion] Advanced Explosion Config

### ISSUE THREAD

**Issue by Preta-Crowz** [GregTechCEu/GregTech#879]
**Is your feature request related to a problem? Please describe.**
In config, `doExplosions` is described as "Disabled Explosion" but it only disables destroy and still explodes.

**Describe the solution you'd like**
Make this config to more detail like enum.
My idea is : 0 - Disable Explosion, 1 - Enable Explosion without Destroy, 2 - Enable Full Explosion

**Comment by TechLord22** [comment]
This has been implemented in #959, so I'm closing this issue.
