### ISSUE TITLE
[Suggestion] Add config option to enable tiers past UHV

### ISSUE THREAD

**Issue by Annwan** [GregTechCEu/GregTech#885]
**Is your feature request related to a problem? Please describe.**
I would like to enable machine tiers past UHV in my modpack, currently it requires editing the source code and using a patched version of the mod. Which is long and tedious to setup.

**Describe the solution you'd like**
When reading through the code I found it is all controlled by the boolean flag `HT` in `gregtech.api.GTValues`
https://github.com/GregTechCEu/GregTech/blob/2d9796a2b9610b0ade861d5b24c8765db95a2083/src/main/java/gregtech/api/GTValues.java#L137
Would it be possible to expose it as a configuration option?

**Comment by Preta-Crowz** [comment]
Found other reference about this value but it's unused on GTCEu itself.
https://github.com/GregTechCEu/GregTech/blob/2d9796a2b9610b0ade861d5b24c8765db95a2083/src/main/java/gregtech/common/metatileentities/MetaTileEntities.java#L811-L820

These functions are control Maps and there's comment on definition.
https://github.com/GregTechCEu/GregTech/blob/2d9796a2b9610b0ade861d5b24c8765db95a2083/src/main/java/gregtech/common/metatileentities/MetaTileEntities.java#L129-L131
