### ISSUE TITLE
[BUG] Duplicated refinery gas recipe

### ISSUE THREAD

**Issue by 209CATrus** [GregTechCEu/GregTech#886]
**Describe the bug**

**Versions**
Forge: 
GTCEu: 
_Modpack:_ if applicable add a link to modpack (CurseForge preferred), version, and any modification applied
_Addons:_ if applicable add all addon names and corresponding versions

**Setup**
_Does this issue happen on Singleplayer, a Server, or both_:
_Does this issue happen on a newly generated world_:

**Steps To Reproduce**
1) I did X
2) And then Y

**Expected behavior**

**Screenshots**

**Additional context**

_Please fill in as much useful information as possible. Also please remove all unused sections._

LOIS I'M IN THE GTCEU ISSUE SECTION
![изображение](https://user-images.githubusercontent.com/26685838/163030128-9de1fc76-a19f-4776-bcdf-92f4edf00e61.png)
![изображение](https://user-images.githubusercontent.com/26685838/163030182-39270907-6bac-46d0-9206-2569c3c930eb.png)

**Comment by htmlcsjs** [comment]
cannot reproduce, likely you have an outdated version of the mod or the pack you are running is skuffed, and i cant test that due to having no information in the report
