### ISSUE TITLE
[BUG] USELESS REFINERY GAS HYDROCRACKING RECIPE

### ISSUE THREAD

**Issue by 209CATrus** [GregTechCEu/GregTech#887]
**Describe the bug**

**Versions**
Forge: 
GTCEu: 
_Modpack:_ if applicable add a link to modpack (CurseForge preferred), version, and any modification applied
_Addons:_ if applicable add all addon names and corresponding versions

**Setup**
_Does this issue happen on Singleplayer, a Server, or both_:
_Does this issue happen on a newly generated world_:

**Steps To Reproduce**
1) I did X
2) And then Y

**Expected behavior**

**Screenshots**

**Additional context**

_Please fill in as much useful information as possible. Also please remove all unused sections._

![изображение](https://user-images.githubusercontent.com/26685838/163030314-966b8acd-974e-4b43-917a-5868f077e344.png)
![изображение](https://user-images.githubusercontent.com/26685838/163030344-aa647a9b-8844-4a61-9bf9-64ef66fa3c39.png)
Medium hydrocracked refinery gas recipe will do

**Comment by htmlcsjs** [comment]
cannot reproduce, likely you have an outdated version of the mod or the pack you are running is skuffed, and i cant test that due to having no information in the report
