### ISSUE TITLE
[Suggestion]Add large transformer

### ISSUE THREAD

**Issue by LunaFreyjaNox** [GregTechCEu/GregTech#889]
Like Gregicality, add large transformer to allow to switch from a lower or higher voltage without switching to the intermediate voltage.
Example: step down HV to LV without use MV tier, or step up EV to ZPM whitout use IV and LuV tier.

Add multiblock like Gregicality

**Comment by ALongStringOfNumbers** [comment]
We don't really have plans for such a multiblock, but the upcoming Power Substation should cover the desires here somewhat
