### ISSUE TITLE
[BUG] Discharge Mode of batteries can be activated with 0 energy stored

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/GregTech#892]
**Describe the bug**
while empty equipment cannot enter discharge mode, empty batteries can

**Versions**
[2d9796a](https://github.com/GregTechCEu/GregTech/commit/2d9796a2b9610b0ade861d5b24c8765db95a2083)

**Setup**
dev env

**Expected behavior**
Empty battery cannot discharge

**Screenshots**
![キャプチャ1282](https://user-images.githubusercontent.com/39122497/163679264-f8a9efad-c9ad-4b6e-be31-252e448c52bb.PNG)

**Comment by Syrcan** [comment]
That is fine, it's just a status on the battery. If you fill it up with energy after enabling discharge mode it will keep that state which can be useful.
