### ISSUE TITLE
[BUG] Chemical Bath has meanless white wool recipe

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/GregTech#895]
**Describe the bug**
chemical white dye + white wool -> white wool
this also happens with white concrete

**Versions**
[2d9796a](https://github.com/GregTechCEu/GregTech/commit/2d9796a2b9610b0ade861d5b24c8765db95a2083)

**Setup**
dev env

**Screenshots**
![キャプチャ1284](https://user-images.githubusercontent.com/39122497/163680242-c2d8fd55-ec42-4210-b59e-6c824f4bcb3d.PNG)

**Comment by htmlcsjs** [comment]
autogen recipe moment
