### ISSUE TITLE
[BUG] putting hydrogen in exu drums will crash

### ISSUE THREAD

**Issue by iouter** [GregTechCEu/GregTech#913]
**Describe the bug**
putting hydrogen in exu drums will crash.
crash-report:https://paste.ubuntu.com/p/57Gt8vBGVS/

**Versions**
Forge: 14.23.5.2860
GTCEu: 2.1.4-beta
_Modpack: [nomi-ceu](https://www.curseforge.com/minecraft/modpacks/nomi-ceu) ( updated gtceu and some other mods )
_Addons:_ if applicable add all addon names and corresponding versions

**Setup**
_Does this issue happen on Singleplayer, a Server, or both_: both
_Does this issue happen on a newly generated world_: 

**Steps To Reproduce**
1) I put hydrogen in the exu stone drum. 
2) And then crashed.

**Comment by iouter** [comment]
gtceu updated to 2.2.1-beta still crashed.

**Comment by htmlcsjs** [comment]
cannot reproduce in a test environment with ceu + xu2 + jei.

looking at your crash, it seems like the one probe is what fails

**Comment by htmlcsjs** [comment]
cannot repoduce with top, and the crash doesnt link to ceu, going to close
