### ISSUE TITLE
[BUG] GCM multis not processing despite having all ingredients

### ISSUE THREAD

**Issue by dtcameron** [GregTechCEu/GregTech#920]
**Describe the bug**

GCM multis not processing recipes, despite there being enough items to process.

**Versions**
Forge: 
GTCEu: 2.2.1-beta
GCML 1.1.2
_Modpack:_ https://github.com/tracer4b/nomi-ceu/releases/tag/1.1.3 plus updating CEu to latest

**Setup**
_Does this issue happen on Singleplayer, a Server, or both_: Singleplayer, Server not tested
_Does this issue happen on a newly generated world_: Untested

**Steps To Reproduce**
0) Set up a GCM multi with parallel control and distinct busses
1) Place (Request via ae2) items to be processed in a GCM mult
2) If the bug occurs then the multi will stop processing after some time

**Expected behavior**
I expected all the valid inputs to be processed

**Screenshots**
Bus with items to make a valid recipe in it. 🖼
GCM multi fully formed and operational. 🖼

**Comment by TechLord22** [comment]
Does updating GTCEu to `v2.2.3` resolve this issue? Numerous fixes were added in the v2.2.2+ releases. If updating does not fix any problem you have, please update this issue accordingly. 

Additionally, I can't seem to open your images attached to this issue.

**Comment by TechLord22** [comment]
As discussed on discord, this is fixed as of #919.
