### ISSUE TITLE
[BUG] Recipes do not work with items that have the TFC metal property

### ISSUE THREAD

**Issue by SpeeeDCraft** [GregTechCEu/GregTech#934]
**Describe the bug**
This is a more extended version of what I wrote here once before.
**Any item marked as TFC metal in CraftTweaker cannot be used in GT recipes.
In fact, other items, for example, food from TFC cannot be used in recipes of GTCEu machines, because of the storage duration property, most likely.**

**Versions**
Forge: 2860
GTCEu: 2.2.1
_Modpack:_ TerraFirmaGreg R3.2.3d Lite
_Addons:_ -

**Setup**
_Does this issue happen on Singleplayer, a Server, or both_: **Both**
_Does this issue happen on a newly generated world_: In already created and which will be created.

**Steps To Reproduce**
1) Mark any item as TFC metal in CraftTweaker.
2) Log into the game and try to use the item in the GTCEu machine.

**Expected behavior**
The recipe with the problematic item had to be fulfilled.

**Screenshots**
With an iron rod, everything works fine since nothing has been done with it.
![image](https://user-images.githubusercontent.com/52341158/167279084-b42441fc-1934-4c8c-a5f5-13a0c597fe02.png)
Here the steel rod is issued units of metal.
![image](https://user-images.githubusercontent.com/52341158/167279103-1669665e-65cc-4779-9381-bb3924b1feb2.png)
![image](https://user-images.githubusercontent.com/52341158/167279105-6fc0158a-6162-4b69-b76d-ee639c418e56.png)
And the same with a impure pile of copper dust.
![image](https://user-images.githubusercontent.com/52341158/167279125-0c7c27d7-e8b1-4f12-8af0-47c293dd59ea.png)

**Additional context**
CT Script:
![image](https://user-images.githubusercontent.com/52341158/167279114-f0d4acdf-f08f-4f9c-8acb-68ef5936e645.png)

**Comment by SpeeeDCraft** [comment]
I did some more tests and found out that this happens when registering an Oredict for an item. I tested with new items added using DevTech. So, we have a piece of ore, and the TFC metal property has been issued for it, and recipes with it work fine in GTCEu machines, but if you give this item an oredict, absolutely any, it stops working in GTCEu machines.

**Comment by SpeeeDCraft** [comment]
I just tested it, version, which is in #666 
Dust centrifugation works exactly. The polarization of the rods was not checked.

**Comment by PrototypeTrousers** [comment]
whats the output of the /ct hand and /gt hand commands ?

**Comment by SpeeeDCraft** [comment]
I didn't really understand, do I need to take an object in my hand and enter a command? If so, what is the subject? The one that started centrifuging?

**Comment by SpeeeDCraft** [comment]
Now I have also checked the polarization of the rods, the recipe of which does not work on the regular version of GTCEu, now everything works.

**Comment by SpeeeDCraft** [comment]
ct and gt hand command on impure copper pile:
![image](https://user-images.githubusercontent.com/52341158/169679997-9910d13b-bdde-40a0-94d5-958f99ac9cb1.png)

**Comment by PrototypeTrousers** [comment]
and what does the steel rod with the units of metal outputs?

**Comment by SpeeeDCraft** [comment]
The translator translates very poorly and sometimes I don't understand what you are writing :(
I gave the TFC metal units to the steel rod, on the current version of GTCEu(2.2.3), the recipe with polarization would not work, but in PR #666 this recipe worked, if you also need screenshots of ct hand and gt hand, write about it.

**Comment by PrototypeTrousers** [comment]
Yes, i need the screenshot of the information of /ct hand and /gt hand while you have the steel rod in your hand

**Comment by SpeeeDCraft** [comment]
![image](https://user-images.githubusercontent.com/52341158/169682194-fc1e4bce-202c-4efb-9b1e-c821754ac097.png)
