### ISSUE TITLE
[BUG] The crafting station turns some items into others

### ISSUE THREAD

**Issue by SpeeeDCraft** [GregTechCEu/GregTech#935]
**Describe the bug**
Red steel ingots are obtained from copper ingots.

**Versions**
Forge: 2860
GTCEu: 2.2.1
_Modpack:_ TerraFirmaGreg R3.2.3d Lite
_Addons:_ -

**Setup**
_Does this issue happen on Singleplayer, a Server, or both_: Both
_Does this issue happen on a newly generated world_: Both

**Steps To Reproduce**
Everything is on the video

https://user-images.githubusercontent.com/52341158/167279309-23d7a5c2-9cd0-4e0b-bf76-0bc5ade2802a.mp4

Also, after performing actions on the video, this error appears in the console:
[message.txt](https://github.com/GregTechCEu/GregTech/files/8646235/message.txt)

**Comment by Syrcan** [comment]
Does this still happen?

**Comment by Xikaro** [comment]
Yep

**Comment by ALongStringOfNumbers** [comment]
Does this still happen after 1255, which is in the latest released version?

**Comment by SpeeeDCraft** [comment]
Everything seems to be working fine now, I'll close it.
