### ISSUE TITLE
[BUG] Steam Boiler only Explodes when the Overvoltage Explosion config is on

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/GregTech#958]
**Describe the bug**
following codes shows the steam boiler explosion is handled by the [machines.doExplosions](https://github.com/GregTechCEu/GregTech/blob/b0967895d05c6c63ae6aef0efbdc721dbf5a972c/src/main/java/gregtech/common/ConfigHolder.java#L77-L78) config
since steam boiler contains no power, it needs to be fixed (I'm fixing it!)
https://github.com/GregTechCEu/GregTech/blob/236eba02edb6c7cc95a81735af69f65ec7b3004c/src/main/java/gregtech/common/metatileentities/steam/boiler/SteamBoiler.java#L228-L229
https://github.com/GregTechCEu/GregTech/blob/53aa97a024598ed04990a2b02a356feaec8d800f/src/main/java/gregtech/api/metatileentity/MetaTileEntity.java#L1360-L1364

**Versions**
GTCEu: 2.2.3

**Setup**
dev env

**Comment by Syrcan** [comment]
No that's intended.
What is wrong here is the description of the `doExplosion` config "Whether machines should explode when overloaded with power.". It should be any explosion, and that includes the boiler.

**Comment by Quarri6343** [comment]
I see
thanks
