### ISSUE TITLE
[BUG] Weird Interactions between the GT Console Terminal App and Crafting Station

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCEu/GregTech#966]
**Describe the bug**
There are several weird interactions between the GT Console Terminal App and the Crafting Station.

----

There are ghost duplicate blocks.
Place two blocks in the Crafting Station, then open the Console App on the crafting station and select "Open Machine GUI", and there will be 4 blocks in the GUI. After you place 2 blocks into your inventory, when you grab the third block, the first two blocks will disappear.

----

You can place blocks in incorrect slots.
In the Console App, you can place blocks into the memory slots of the Crafting Station. Although when you open the Crafting Station GUI after exiting the App, the blocks will be in regular inventory slots.

----

**Versions**
Forge: 14.23.5.2847
GTCEu: commit 2c9490d

**Setup**
_Does this issue happen on Singleplayer, a Server, or both_:
_Does this issue happen on a newly generated world_:

**Steps To Reproduce**
1) Place down a crafting station
2) Place a few blocks into the GUI
3) Shift click on the crafting station with the terminal and pull up the GT Console App
4) See apparently duplicated blocks (which are just ghost blocks)

**Expected behavior**
No ghost blocks, and not being able to place blocks into inaccessible slots

**Comment by lordclips** [comment]
![The bug in question](https://media.giphy.com/media/XDoKOv3AkI3Y6miBbV/giphy.gif)

I was able to reproduce this fairly easy and it seems like the issue actually gets worse the more you do it. I have a rough idea of where the actual issue *starts* but I'm not exactly sure how deep the issue goes and I can't really find anything specifically that's causing it just yet.

Regardless, video shows that it does indeed exist. From a fork made yesterday with no changes since forking on master.

**Comment by lordclips** [comment]
For brevity, though, I'm guessing it's an issue with ModularUI trying to deal with the special cases for both the actual crafting grid and memory slots, though that doesn't really answer why it spreads like the damn plague.

**Comment by lordclips** [comment]
@TechLord22 is it worth keeping this around despite the pending ModularUI changes just incase it crops back up? I was planning on digging into it some more stepwise but if the rewrite on its own might fix it that'll change things somewhat
