### ISSUE TITLE
[Suggestion] Add Inventory Sorting Integration to Crates

### ISSUE THREAD

**Issue by shawnbyday** [GregTechCEu/GregTech#988]
**Is your feature request related to a problem? Please describe.**
This feature request is not related to an actual problem. It would be nice to be able to sort the GregTech crates. It helps see how much free space there is by stacking things and ordering them. In the larger crates this would be a huge quality of life improvement.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/33701188/170639078-e5abb216-5387-467b-8ff6-12b3049f1751.png)

**Comment by brachy84** [comment]
Part of #986
