### ISSUE TITLE
[BUG] Packager causes massive lag

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/GregTech#999]
**Describe the bug**
Someone told me that packager causes ridiculous lag spike in his server
![unknown](https://user-images.githubusercontent.com/39122497/171139313-79182313-7b6d-4afa-97df-6787c70faa87.png)
After some investigation, I found it is probably because of the recipe lookup method
It does not happen with other machine

**Versions**
GTCEu: 2.3.0

**Setup**
dev env

**Steps To Reproduce**
1) place a powered packager
2) grab many kind of dusts from JEI and pour all of them into the packager

**Expected behavior**
a new packager
![2022-05-31_18 09 13](https://user-images.githubusercontent.com/39122497/171140969-095ab9a6-110a-4ad4-ab6a-a2218e3dd5f0.png)

**Screenshots**
a used packager
![2022-05-31_18 08 56](https://user-images.githubusercontent.com/39122497/171140842-e982a938-a17c-4d5b-9c7a-ad20379a3483.png)

**Comment by ALongStringOfNumbers** [comment]
I am hoping this may be fixed by #666 but @PrototypeTrousers would have to comment on it

**Comment by PrototypeTrousers** [comment]
i would appreciate a spark profile of this.

**Comment by Quarri6343** [comment]
looks like MTECreativeEnergy is the true evil
https://spark.lucko.me/oaRo0dw8K3
